# Five-microgrid ablation study: trust-region samples vs. global random samples

This notebook runs one complete experiment from top to bottom. It does not load an old trust-region run. The four methods compared at the end are:

1. the original global L2O models solved with the NN solver;
2. trust-region residual correction initialized from the original NN solution;
3. global L2O models retrained on original + trust-region samples;
4. global L2O models retrained on original + equally many global random samples.

The full run is expensive because it includes five lower-level models, a trust-region run, two rounds of training, and three 10,000-step NN solves.

In [1]:
import time
from pathlib import Path

import numpy as np
import pandas as pd
import pandapower.networks as pn

import follower_solver
from L2Otraining import TrainingConfig, train
from stackelberg.followers.bg import create_cigre_residential_network
from stackelberg.followers.ip import create_industrial_park_network
from stackelberg.instances import resolve_follower_configuration
from stackelberg.network import create_case33bw_20kv
from stackelberg.nn_solver import (
    NNSolverExperimentConfig,
    run_nn_solver_experiment,
)
from stackelberg.randomness import make_rng, set_global_seed
from stackelberg.trust_region import (
    TrustRegionExperimentConfig,
    run_trust_region_experiment,
)

PROJECT_ROOT = Path.cwd().resolve()
DATA_DIR = PROJECT_ROOT / "data"
MODEL_DIR = PROJECT_ROOT / "NNmodel"
RESULTS_DIR = PROJECT_ROOT / "results"

if not (PROJECT_ROOT / "L2Otraining.py").is_file():
    raise RuntimeError("Run this notebook with the project root as the working directory.")

DATA_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

T = 24
SEED = 42
NN_STEPS = 10_000
NN_LEARNING_RATE = 1e-2
NN_SAVE_EVERY = 200
TRAINING_EPOCHS = 500
LOWER_TIME_LIMIT = 30.0
LOWER_MIP_GAP = 1e-3
NEW_DATA_CHECKPOINT_INTERVAL = 100
NEW_DATA_SEEDS = {
    "SB1": 4201,
    "SB2": 4202,
    "BG1": 4203,
    "BG2": 4204,
    "IP1": 4205,
}

SCENARIOS = ["SB1", "SB2", "BG1", "BG2", "IP1"]
MG_BUSES = [17, 32, 15, 21, 1]
UPPER_NET = create_case33bw_20kv()
LOWER_NETS = [
    pn.create_cigre_network_lv(),
    pn.create_cigre_network_lv(),
    create_cigre_residential_network(),
    create_cigre_residential_network(),
    create_industrial_park_network(),
]
X0 = np.full((len(SCENARIOS), T), 0.75, dtype=float)

follower_ids, scenario_types, follower_kwargs = resolve_follower_configuration(
    SCENARIOS
)
if follower_ids != SCENARIOS:
    raise RuntimeError(f"Resolved follower order {follower_ids} does not match {SCENARIOS}.")

INSTANCE_NETWORKS = dict(zip(SCENARIOS, LOWER_NETS))
INSTANCE_TYPES = dict(zip(SCENARIOS, scenario_types))
INSTANCE_SOLVER_KWARGS = dict(zip(SCENARIOS, follower_kwargs))

instance_table = pd.DataFrame(
    {
        "follower_id": SCENARIOS,
        "scenario_type": scenario_types,
        "mg_bus": MG_BUSES,
        "solver_kwargs": follower_kwargs,
    }
).set_index("follower_id")
display(instance_table)

            scenario_type  mg_bus           solver_kwargs
follower_id
SB1                    SB      17                      {}
SB2                    SB      32     {'load_scale': 1.1}
BG1                    BG      15  {'date': '2023-01-01'}
BG2                    BG      21  {'date': '2023-07-01'}
IP1                    IP       1  {'date': '2023-01-01'}

In [2]:
def load_aligned_arrays(x_path, y_path, *, expected_rows=None, expected_width=T):
    """Load and validate one aligned price/response dataset."""
    x_path = Path(x_path)
    y_path = Path(y_path)
    if not x_path.is_file() or not y_path.is_file():
        raise FileNotFoundError(f"Expected both {x_path} and {y_path}.")

    x_data = np.load(x_path)
    y_data = np.load(y_path)
    if x_data.ndim != 2 or y_data.ndim != 2:
        raise ValueError(f"Expected 2-D arrays, got X{x_data.shape} and Y{y_data.shape}.")
    if x_data.shape != y_data.shape:
        raise ValueError(f"X/Y shape mismatch: X{x_data.shape} and Y{y_data.shape}.")
    if x_data.shape[1] != expected_width:
        raise ValueError(f"Expected width {expected_width}, got {x_data.shape[1]}.")
    if len(x_data) == 0:
        raise ValueError(f"Dataset is empty: {x_path.name}.")
    if expected_rows is not None and len(x_data) != expected_rows:
        raise ValueError(
            f"Expected {expected_rows} rows in {x_path.name}, got {len(x_data)}."
        )
    if not np.isfinite(x_data).all() or not np.isfinite(y_data).all():
        raise ValueError(f"Non-finite values found in {x_path.name} or {y_path.name}.")
    if np.any(x_data < -1e-12) or np.any(x_data > 1.5 + 1e-12):
        raise ValueError(f"Prices in {x_path.name} must lie in [0, 1.5].")
    return x_data, y_data


def atomic_save_npy(path, array):
    """Replace a NumPy file only after the complete array is serialized."""
    path = Path(path)
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    with temporary_path.open("wb") as file:
        np.save(file, np.asarray(array))
    temporary_path.replace(path)


for scenario in SCENARIOS:
    load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy",
        DATA_DIR / f"Y_{scenario}.npy",
    )
    for suffix in (".pth", ".json"):
        model_path = MODEL_DIR / f"L2O_{scenario}{suffix}"
        if not model_path.is_file():
            raise FileNotFoundError(model_path)

print("Validated original datasets and L2O checkpoints for all five instances.")

Validated original datasets and L2O checkpoints for all five instances.

## 1. Original global models and NN solver

All three NN-solver runs use the same initial price matrix and the same 10,000-step optimization budget.

In [3]:
original_nn_config = NNSolverExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=X0,
    steps=NN_STEPS,
    lr=NN_LEARNING_RATE,
    save_every=NN_SAVE_EVERY,
    history_path=str(RESULTS_DIR / "NN_solver_original_ablation_history.csv"),
    evaluate_true=True,
    save_results=True,
)
original_nn_result = run_nn_solver_experiment(original_nn_config)
original_nn_prices = np.asarray(
    original_nn_result["optimal pi"], dtype=float
).reshape(len(SCENARIOS), T)

print("Original NN history:", original_nn_result["history_path"])
print("Original NN true objective:", original_nn_result["true_obj"])
print("Original NN runtime (s):", original_nn_result["runtime_seconds"])
display(pd.DataFrame(original_nn_prices, index=SCENARIOS))

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[0] loss=5821.5625, obj=-123.5207, eq=5.9380, soc=0.0647, bound=0.0646, true_loss=-0.1048
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[200] loss=134.8586, obj=-64.2317, eq=0.1953, soc=0.0351, bound=0.0242, true_loss=-2.8603
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[400] loss=34.6558, obj=-50.4435, eq=0.0834, soc=0.0158, bound=0.0111, true_loss=-9.2918
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[600] loss=-6.4125, obj=-41.3949, eq=0.0342, soc=0.0073, bound=0.0029, true_loss=-13.7951
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[800] loss=-22.1621, obj=-38.5958, eq=0.0161, soc=0.0037, bound=0.0009, true_loss=-18.5969
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1000] loss=-30.4826, obj=-41.0920, eq=0.0104, soc=0.0024, bound=0.0005, true_loss=-24.4366
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1200] loss=-36.6646, obj=-45.4323, eq=0.0086, soc=0.0019, bound=0.0003, true_loss=-30.4735
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1400] loss=-43.1530, obj=-51.2311, eq=0.0079, soc=0.0017, bound=0.0003, true_loss=-36.9781
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1600] loss=-50.8415, obj=-58.5202, eq=0.0075, soc=0.0018, bound=0.0002, true_loss=-44.3523
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1800] loss=-56.7740, obj=-64.4431, eq=0.0075, soc=0.0017, bound=0.0002, true_loss=-50.5828
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2000] loss=-62.8580, obj=-69.8078, eq=0.0068, soc=0.0016, bound=0.0002, true_loss=-56.0700
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2200] loss=-68.0616, obj=-75.3269, eq=0.0071, soc=0.0016, bound=0.0002, true_loss=-61.7989
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2400] loss=-73.1932, obj=-80.5792, eq=0.0072, soc=0.0016, bound=0.0002, true_loss=-66.7924
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2600] loss=-77.9233, obj=-84.5466, eq=0.0065, soc=0.0016, bound=0.0002, true_loss=-70.7673
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2800] loss=-81.1030, obj=-88.1120, eq=0.0069, soc=0.0015, bound=0.0002, true_loss=-74.7186
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3000] loss=-83.5923, obj=-91.3616, eq=0.0076, soc=0.0016, bound=0.0002, true_loss=-78.0879
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3200] loss=-87.7011, obj=-94.1365, eq=0.0063, soc=0.0015, bound=0.0002, true_loss=-80.7362
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3400] loss=-89.3474, obj=-96.4757, eq=0.0070, soc=0.0016, bound=0.0002, true_loss=-82.8563
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3600] loss=-92.0595, obj=-98.8464, eq=0.0066, soc=0.0016, bound=0.0002, true_loss=-84.7285
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3800] loss=-92.8540, obj=-100.4959, eq=0.0075, soc=0.0016, bound=0.0002, true_loss=-86.3176
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4000] loss=-94.2521, obj=-101.9559, eq=0.0075, soc=0.0016, bound=0.0002, true_loss=-87.4202
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4200] loss=-96.2219, obj=-103.1974, eq=0.0068, soc=0.0016, bound=0.0002, true_loss=-88.9616
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4400] loss=-96.8510, obj=-104.2570, eq=0.0072, soc=0.0016, bound=0.0002, true_loss=-90.2600
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4600] loss=-97.8953, obj=-105.1560, eq=0.0071, soc=0.0016, bound=0.0002, true_loss=-91.2341
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4800] loss=-99.8904, obj=-106.2216, eq=0.0062, soc=0.0016, bound=0.0002, true_loss=-92.1669
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5000] loss=-99.4805, obj=-106.8703, eq=0.0072, soc=0.0016, bound=0.0002, true_loss=-92.9917
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5200] loss=-100.5159, obj=-107.8769, eq=0.0072, soc=0.0017, bound=0.0002, true_loss=-93.7739
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
SB1,0.970181,0.972706,0.975164,1.000694,0.959616,0.969702,1.160907,1.497205,1.497323,0.998421,...,1.047077,1.499775,1.496677,1.499511,1.337253,1.495676,1.489284,1.496565,1.093230,0.966810
SB2,0.984327,1.489236,0.971531,0.980285,0.946286,0.950465,0.998462,0.976595,1.498717,1.498230,...,1.016355,1.498472,1.497773,1.498430,1.498577,1.499142,1.497796,1.451597,1.440844,1.184781
BG1,1.499816,1.499887,1.499895,1.499872,1.499943,1.499931,1.499945,1.499928,1.499881,1.499913,...,1.499950,1.499931,1.499941,1.499935,1.499918,1.499891,1.499909,1.499468,1.499928,1.499742
BG2,1.499647,1.499705,1.499627,1.499876,1.499915,1.499792,1.499918,1.499930,1.499858,1.499912,...,1.499942,1.499920,1.499952,1.499877,1.499927,1.499919,1.499869,1.499671,1.499878,1.499435
IP1,1.496455,1.492518,1.494619,1.495886,1.491641,1.457786,1.486227,1.497947,1.498367,1.497680,...,1.498705,1.498223,1.498699,1.496387,1.490192,1.497343,1.496753,1.495072,1.498292,1.497317

## 2. Trust region and fresh trust-region training samples

The trust region starts at the original NN solution. `save_true_responses=True` retains the high-fidelity residual-fit designs, including each local center, and the controller removes duplicate rows across iterations before export. The resulting files replace the known-invalid `_tr` datasets.

In [4]:
tr_config = TrustRegionExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=original_nn_prices,
    lower_time_limit=LOWER_TIME_LIMIT,
    lower_mip_gap=LOWER_MIP_GAP,
    tr_params={
        "R_0": 0.05,
        "R_max": 1.0,
        "gamma_dec": 0.7,
        "gamma_inc": 1.5,
        "eta_1": 0.1,
        "eta_2": 0.75,
    },
    algo_params={
        "n_samples": 60,
        "K_max": 60,
        "sampling_method": "lhs",
        "residual_update_mode": "accumulate",
        "rbf_geometry_condition_max": 1e12,
        "solve_params": {
            "steps_init": 0,
            "steps_warm": 2000,
            "lr": 1e-2,
            "penalty_weights": {
                "eq": 1000.0,
                "ineq": 100.0,
                "soc": 100.0,
                "bound": 10.0,
            },
            "tr_weight": 1e6,
            "verbose": True,
        },
    },
    residual_model_params={
        "model_type": "rbf",
        "rbf_kernel": "cubic",
        "rbf_smoothing": 1e-3,
        "rbf_degree": 1,
        "rbf_scale": "trust_radius",
        "rbf_epsilon": None,
    },
    save_results=True,
    output_dir=str(RESULTS_DIR),
    save_true_responses=True,
    true_response_dir=str(DATA_DIR),
    true_response_tag="tr",
)
tr_result = run_trust_region_experiment(tr_config)
tr_prices = np.asarray(tr_result["x_opt"], dtype=float).reshape(
    len(SCENARIOS), T
)
tr_history = pd.DataFrame(tr_result["history"])
if tr_history.empty:
    raise RuntimeError("Trust-region history is empty.")
tr_last = tr_history.iloc[-1]
tr_objective = float(
    tr_last["F_candidate"]
    if str(tr_last["decision"]).startswith("accept")
    else tr_last["F_current"]
)
tr_composite_queries = int(
    tr_result["n_iter"] * (tr_config.algo_params["n_samples"] + 1)
)

print("Trust region converged:", tr_result["converged"])
print("Trust region iterations:", tr_result["n_iter"])
print("Trust region true objective:", tr_objective)
print("Trust region composite high-fidelity queries:", tr_composite_queries)
print("Saved paths:", tr_result.get("saved_paths"))

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Using global surrogate to solve initial point...
Initial surrogate solve used steps_init=0. Time taken to solve initial point 0.0488 seconds.
Iteration 0 | R=0.0500
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0500...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 9.0349e+05
Follower 1 RBF interpolation condition number: 6.7260e+05
Follower 2 RBF interpolation condition number: 6.2751e+05
Follower 3 RBF interpolation condition number: 6.5868e+05
Follower 4 RBF interpolation condition number: 4.0290e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   0] F_current=-98.4807 | F_candidate=-98.2625 | F_tilde_current=-98.4415 | F_tilde_candidate=-99.9100 | Ared=-0.2182 | Pred=1.4684 | rho=-0.1486 | decision=reject | R=0.0500 | residual_update=accumulate | n_residuals=0
Rejecting step 0...
Time taken to solve iteration 0 468.9705 seconds.
Iteration 1 | R=0.0350
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0350...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 8.7045e+05
Follower 1 RBF interpolation condition number: 5.5494e+05
Follower 2 RBF interpolation condition number: 6.1558e+05
Follower 3 RBF interpolation condition number: 6.1752e+05
Follower 4 RBF interpolation condition number: 2.9906e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   1] F_current=-98.4807 | F_candidate=-98.2752 | F_tilde_current=-98.4500 | F_tilde_candidate=-99.4542 | Ared=-0.2054 | Pred=1.0042 | rho=-0.2046 | decision=reject | R=0.0350 | residual_update=accumulate | n_residuals=0
Rejecting step 1...
Time taken to solve iteration 1 468.7574 seconds.
Iteration 2 | R=0.0245
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0245...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 8.2432e+05
Follower 1 RBF interpolation condition number: 3.9312e+05
Follower 2 RBF interpolation condition number: 6.1120e+05
Follower 3 RBF interpolation condition number: 6.1479e+05
Follower 4 RBF interpolation condition number: 1.9751e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   2] F_current=-98.4807 | F_candidate=-98.6721 | F_tilde_current=-98.4600 | F_tilde_candidate=-99.2854 | Ared=0.1914 | Pred=0.8254 | rho=0.2319 | decision=accept_keep | R=0.0245 | residual_update=accumulate | n_residuals=1
Accepting step 2 and keeping...
Time taken to solve iteration 2 468.5125 seconds.
Iteration 3 | R=0.0245
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0245...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0406e+06
Follower 1 RBF interpolation condition number: 9.7020e+05
Follower 2 RBF interpolation condition number: 6.0620e+05
Follower 3 RBF interpolation condition number: 6.1657e+05
Follower 4 RBF interpolation condition number: 3.9250e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   3] F_current=-98.6721 | F_candidate=-97.9304 | F_tilde_current=-98.6479 | F_tilde_candidate=-99.4713 | Ared=-0.7417 | Pred=0.8234 | rho=-0.9009 | decision=reject | R=0.0245 | residual_update=accumulate | n_residuals=1
Rejecting step 3...
Time taken to solve iteration 3 473.9690 seconds.
Iteration 4 | R=0.0171
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0171...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0029e+06
Follower 1 RBF interpolation condition number: 9.3950e+05
Follower 2 RBF interpolation condition number: 6.1085e+05
Follower 3 RBF interpolation condition number: 6.2313e+05
Follower 4 RBF interpolation condition number: 3.1295e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   4] F_current=-98.6721 | F_candidate=-98.8228 | F_tilde_current=-98.6582 | F_tilde_candidate=-99.2137 | Ared=0.1507 | Pred=0.5555 | rho=0.2712 | decision=accept_keep | R=0.0171 | residual_update=accumulate | n_residuals=2
Accepting step 4 and keeping...
Time taken to solve iteration 4 471.7012 seconds.
Iteration 5 | R=0.0171
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0171...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 9.6833e+05
Follower 1 RBF interpolation condition number: 9.1015e+05
Follower 2 RBF interpolation condition number: 6.2487e+05
Follower 3 RBF interpolation condition number: 6.2900e+05
Follower 4 RBF interpolation condition number: 6.4288e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   5] F_current=-98.8228 | F_candidate=-98.7019 | F_tilde_current=-98.7964 | F_tilde_candidate=-99.6185 | Ared=-0.1209 | Pred=0.8220 | rho=-0.1471 | decision=reject | R=0.0171 | residual_update=accumulate | n_residuals=2
Rejecting step 5...
Time taken to solve iteration 5 477.4824 seconds.
Iteration 6 | R=0.0120
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0120...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 9.8458e+05
Follower 1 RBF interpolation condition number: 8.9551e+05
Follower 2 RBF interpolation condition number: 6.2984e+05
Follower 3 RBF interpolation condition number: 6.1231e+05
Follower 4 RBF interpolation condition number: 6.7451e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   6] F_current=-98.8228 | F_candidate=-98.8591 | F_tilde_current=-98.8059 | F_tilde_candidate=-99.5256 | Ared=0.0364 | Pred=0.7197 | rho=0.0505 | decision=accept_shrink | R=0.0120 | residual_update=accumulate | n_residuals=3
Accepting step 6 and shrinking...
Time taken to solve iteration 6 477.0788 seconds.
Iteration 7 | R=0.0084
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0084...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0477e+06
Follower 1 RBF interpolation condition number: 9.4226e+05
Follower 2 RBF interpolation condition number: 6.3485e+05
Follower 3 RBF interpolation condition number: 6.1953e+05
Follower 4 RBF interpolation condition number: 8.3526e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   7] F_current=-98.8591 | F_candidate=-98.8712 | F_tilde_current=-98.8599 | F_tilde_candidate=-98.4193 | Ared=0.0120 | Pred=-0.4407 | rho=-inf | decision=accept_shrink | R=0.0084 | residual_update=accumulate | n_residuals=4
Accepting step 7 and shrinking...
Time taken to solve iteration 7 486.1780 seconds.
Iteration 8 | R=0.0059
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0059...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 9.1238e+05
Follower 1 RBF interpolation condition number: 9.8985e+05
Follower 2 RBF interpolation condition number: 6.2826e+05
Follower 3 RBF interpolation condition number: 6.3475e+05
Follower 4 RBF interpolation condition number: 8.6347e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   8] F_current=-98.8712 | F_candidate=-98.8778 | F_tilde_current=-98.8702 | F_tilde_candidate=-98.8089 | Ared=0.0066 | Pred=-0.0612 | rho=-inf | decision=accept_shrink | R=0.0059 | residual_update=accumulate | n_residuals=5
Accepting step 8 and shrinking...
Time taken to solve iteration 8 485.2062 seconds.
Iteration 9 | R=0.0041
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0041...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.5571e+05
Follower 1 RBF interpolation condition number: 9.5804e+05
Follower 2 RBF interpolation condition number: 6.4456e+05
Follower 3 RBF interpolation condition number: 6.2124e+05
Follower 4 RBF interpolation condition number: 8.7223e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   9] F_current=-98.8778 | F_candidate=-99.4980 | F_tilde_current=-98.8780 | F_tilde_candidate=-99.2737 | Ared=0.6203 | Pred=0.3956 | rho=1.5678 | decision=accept_expand | R=0.0041 | residual_update=accumulate | n_residuals=6
Accepting step 9 and expanding...
Time taken to solve iteration 9 490.0114 seconds.
Iteration 10 | R=0.0062
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0062...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.2541e+04
Follower 1 RBF interpolation condition number: 9.3605e+05
Follower 2 RBF interpolation condition number: 6.1424e+05
Follower 3 RBF interpolation condition number: 6.0495e+05
Follower 4 RBF interpolation condition number: 9.5229e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  10] F_current=-99.4980 | F_candidate=-98.8422 | F_tilde_current=-99.4941 | F_tilde_candidate=-98.9150 | Ared=-0.6559 | Pred=-0.5792 | rho=-inf | decision=reject | R=0.0062 | residual_update=accumulate | n_residuals=6
Rejecting step 10...
Time taken to solve iteration 10 487.1041 seconds.
Iteration 11 | R=0.0043
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0043...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.9877e+04
Follower 1 RBF interpolation condition number: 9.8449e+05
Follower 2 RBF interpolation condition number: 6.0967e+05
Follower 3 RBF interpolation condition number: 6.4782e+05
Follower 4 RBF interpolation condition number: 8.9002e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  11] F_current=-99.4980 | F_candidate=-99.0981 | F_tilde_current=-99.4954 | F_tilde_candidate=-98.9779 | Ared=-0.3999 | Pred=-0.5175 | rho=-inf | decision=reject | R=0.0043 | residual_update=accumulate | n_residuals=6
Rejecting step 11...
Time taken to solve iteration 11 487.6268 seconds.
Iteration 12 | R=0.0030
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0030...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.8818e+04
Follower 1 RBF interpolation condition number: 1.0009e+06
Follower 2 RBF interpolation condition number: 6.2705e+05
Follower 3 RBF interpolation condition number: 6.1791e+05
Follower 4 RBF interpolation condition number: 8.3766e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  12] F_current=-99.4980 | F_candidate=-99.1706 | F_tilde_current=-99.4960 | F_tilde_candidate=-99.0518 | Ared=-0.3274 | Pred=-0.4442 | rho=-inf | decision=reject | R=0.0030 | residual_update=accumulate | n_residuals=6
Rejecting step 12...
Time taken to solve iteration 12 492.5104 seconds.
Iteration 13 | R=0.0021
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0021...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.6556e+04
Follower 1 RBF interpolation condition number: 9.6125e+05
Follower 2 RBF interpolation condition number: 6.1934e+05
Follower 3 RBF interpolation condition number: 5.9414e+05
Follower 4 RBF interpolation condition number: 7.2455e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  13] F_current=-99.4980 | F_candidate=-99.0650 | F_tilde_current=-99.4962 | F_tilde_candidate=-99.2799 | Ared=-0.4330 | Pred=-0.2163 | rho=-inf | decision=reject | R=0.0021 | residual_update=accumulate | n_residuals=6
Rejecting step 13...
Time taken to solve iteration 13 491.1892 seconds.
Iteration 14 | R=0.0015
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0015...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.8259e+04
Follower 1 RBF interpolation condition number: 9.0022e+05
Follower 2 RBF interpolation condition number: 6.1546e+05
Follower 3 RBF interpolation condition number: 5.7975e+05
Follower 4 RBF interpolation condition number: 5.5900e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  14] F_current=-99.4980 | F_candidate=-99.2021 | F_tilde_current=-99.4970 | F_tilde_candidate=-99.4439 | Ared=-0.2959 | Pred=-0.0531 | rho=-inf | decision=reject | R=0.0015 | residual_update=accumulate | n_residuals=6
Rejecting step 14...
Time taken to solve iteration 14 489.0673 seconds.
Iteration 15 | R=0.0010
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0010...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.6269e+04
Follower 1 RBF interpolation condition number: 8.0500e+05
Follower 2 RBF interpolation condition number: 6.1326e+05
Follower 3 RBF interpolation condition number: 5.3709e+05
Follower 4 RBF interpolation condition number: 3.7477e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  15] F_current=-99.4980 | F_candidate=-99.1425 | F_tilde_current=-99.4972 | F_tilde_candidate=-99.5170 | Ared=-0.3556 | Pred=0.0198 | rho=-17.9529 | decision=reject | R=0.0010 | residual_update=accumulate | n_residuals=6
Rejecting step 15...
Time taken to solve iteration 15 493.7571 seconds.
Iteration 16 | R=0.0007
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0007...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.4056e+04
Follower 1 RBF interpolation condition number: 6.3183e+05
Follower 2 RBF interpolation condition number: 5.6233e+05
Follower 3 RBF interpolation condition number: 5.0800e+05
Follower 4 RBF interpolation condition number: 2.2466e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  16] F_current=-99.4980 | F_candidate=-99.3376 | F_tilde_current=-99.4973 | F_tilde_candidate=-99.5605 | Ared=-0.1604 | Pred=0.0632 | rho=-2.5374 | decision=reject | R=0.0007 | residual_update=accumulate | n_residuals=6
Rejecting step 16...
Time taken to solve iteration 16 488.3611 seconds.
Iteration 17 | R=0.0005
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0005...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.2765e+04
Follower 1 RBF interpolation condition number: 4.6297e+05
Follower 2 RBF interpolation condition number: 5.0993e+05
Follower 3 RBF interpolation condition number: 4.0418e+05
Follower 4 RBF interpolation condition number: 1.2211e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  17] F_current=-99.4980 | F_candidate=-99.3397 | F_tilde_current=-99.4980 | F_tilde_candidate=-99.4722 | Ared=-0.1583 | Pred=-0.0258 | rho=-inf | decision=reject | R=0.0005 | residual_update=accumulate | n_residuals=6
Rejecting step 17...
Time taken to solve iteration 17 488.6750 seconds.
Iteration 18 | R=0.0004
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0004...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.9030e+04
Follower 1 RBF interpolation condition number: 2.9877e+05
Follower 2 RBF interpolation condition number: 4.0250e+05
Follower 3 RBF interpolation condition number: 3.0252e+05
Follower 4 RBF interpolation condition number: 6.0868e+04
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  18] F_current=-99.4980 | F_candidate=-99.5735 | F_tilde_current=-99.4980 | F_tilde_candidate=-99.5657 | Ared=0.0755 | Pred=0.0678 | rho=1.1145 | decision=accept_expand | R=0.0004 | residual_update=accumulate | n_residuals=7
Accepting step 18 and expanding...
Time taken to solve iteration 18 500.5094 seconds.
Iteration 19 | R=0.0005
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0005...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.1917e+04
Follower 1 RBF interpolation condition number: 4.3292e+05
Follower 2 RBF interpolation condition number: 5.0132e+05
Follower 3 RBF interpolation condition number: 4.5430e+05
Follower 4 RBF interpolation condition number: 1.8056e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  19] F_current=-99.5735 | F_candidate=-99.3365 | F_tilde_current=-99.5729 | F_tilde_candidate=-99.4486 | Ared=-0.2370 | Pred=-0.1243 | rho=-inf | decision=reject | R=0.0005 | residual_update=accumulate | n_residuals=7
Rejecting step 19...
Time taken to solve iteration 19 507.5244 seconds.

In [5]:
current_tr_responses = tr_result.get("true_responses", {})
if set(current_tr_responses) != set(SCENARIOS):
    raise RuntimeError(
        f"Expected current-run TR samples for {SCENARIOS}, got "
        f"{sorted(current_tr_responses)}."
    )

tr_sample_counts = {}
sample_rows = []
for scenario in SCENARIOS:
    original_x, original_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy",
        DATA_DIR / f"Y_{scenario}.npy",
    )
    tr_x, tr_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_tr.npy",
        DATA_DIR / f"Y_{scenario}_tr.npy",
    )
    in_memory_x = np.asarray(current_tr_responses[scenario]["X"], dtype=float)
    in_memory_y = np.asarray(current_tr_responses[scenario]["Y"], dtype=float)
    np.testing.assert_allclose(tr_x, in_memory_x)
    np.testing.assert_allclose(tr_y, in_memory_y)

    tr_sample_counts[scenario] = len(tr_x)
    sample_rows.append(
        {
            "scenario": scenario,
            "original_samples": len(original_x),
            "trust_region_samples": len(tr_x),
            "tr_combined_samples": len(original_x) + len(tr_x),
        }
    )

tr_sample_count_table = pd.DataFrame(sample_rows).set_index("scenario")
display(tr_sample_count_table)

          original_samples  trust_region_samples  tr_combined_samples
scenario
SB1                  10000                  1392                11392
SB2                  10000                  1342                11342
BG1                  10000                  1097                11097
BG2                  10000                  1064                11064
IP1                  10000                  1309                11309

## 3. Retrain global models on original + trust-region samples

Each follower instance remains separate. Training writes `L2O_XX_tr.pth/.json` and leaves the original checkpoints unchanged.

In [6]:
def training_config(scenario):
    return TrainingConfig(
        scenario=scenario,
        hidden_dim=128,
        residual_blocks=3,
        batch_size=64,
        learning_rate=1e-3,
        epochs=TRAINING_EPOCHS,
        validation_fraction=0.2,
        seed=SEED,
    )


tr_training_results = {}
for scenario in SCENARIOS:
    print(f"\nTraining {scenario} on original + trust-region samples")
    tr_training_results[scenario] = train(
        scenario,
        config=training_config(scenario),
        data_tag="tr",
        model_tag="tr",
        include_original=True,
    )
    for suffix in (".pth", ".json"):
        expected_model = MODEL_DIR / f"L2O_{scenario}_tr{suffix}"
        if not expected_model.is_file():
            raise FileNotFoundError(expected_model)

display(pd.DataFrame(tr_training_results).T.rename_axis("scenario"))

Training SB1 on original + trust-region samples
SB1: concatenated original 10000 + tr 1392 samples -> 11392
SB1 epoch   10/500: train=0.043312, validation=0.045060
SB1 epoch   20/500: train=0.032151, validation=0.033518
SB1 epoch   30/500: train=0.028143, validation=0.029543
SB1 epoch   40/500: train=0.021942, validation=0.022977
SB1 epoch   50/500: train=0.016209, validation=0.016810
SB1 epoch   60/500: train=0.010084, validation=0.010510
SB1 epoch   70/500: train=0.012549, validation=0.013118
SB1 epoch   80/500: train=0.019697, validation=0.020156
SB1 epoch   90/500: train=0.014559, validation=0.014865
SB1 epoch  100/500: train=0.040199, validation=0.040524
SB1 epoch  110/500: train=0.020302, validation=0.020560
SB1 epoch  120/500: train=0.007437, validation=0.007669
SB1 epoch  130/500: train=0.004328, validation=0.004538
SB1 epoch  140/500: train=0.005286, validation=0.005548
SB1 epoch  150/500: train=0.009669, validation=0.009763
SB1 epoch  160/500: train=0.003923, validation=0.004146
SB1 epoch  170/500: train=0.006871, validation=0.007061
SB1 epoch  180/500: train=0.002761, validation=0.002937
SB1 epoch  190/500: train=0.003595, validation=0.003802
SB1 epoch  200/500: train=0.004835, validation=0.004968
SB1 epoch  210/500: train=0.003736, validation=0.003888
SB1 epoch  220/500: train=0.002409, validation=0.002566
SB1 epoch  230/500: train=0.003587, validation=0.003756
SB1 epoch  240/500: train=0.002165, validation=0.002294
SB1 epoch  250/500: train=0.005703, validation=0.005823
SB1 epoch  260/500: train=0.003141, validation=0.003264
SB1 epoch  270/500: train=0.003778, validation=0.003886
SB1 epoch  280/500: train=0.003871, validation=0.003959
SB1 epoch  290/500: train=0.001946, validation=0.002058
SB1 epoch  300/500: train=0.001788, validation=0.001898
SB1 epoch  310/500: train=0.002552, validation=0.002633
SB1 epoch  320/500: train=0.002888, validation=0.002983
SB1 epoch  330/500: train=0.003849, validation=0.003933
SB1 epoch  340/500: train=0.001300, validation=0.001398
SB1 epoch  350/500: train=0.002022, validation=0.002109
SB1 epoch  360/500: train=0.002019, validation=0.002102
SB1 epoch  370/500: train=0.000998, validation=0.001093
SB1 epoch  380/500: train=0.000841, validation=0.000933
SB1 epoch  390/500: train=0.001025, validation=0.001119
SB1 epoch  400/500: train=0.005912, validation=0.006006
SB1 epoch  410/500: train=0.001193, validation=0.001268
SB1 epoch  420/500: train=0.000983, validation=0.001055
SB1 epoch  430/500: train=0.001498, validation=0.001566
SB1 epoch  440/500: train=0.000667, validation=0.000747
SB1 epoch  450/500: train=0.000821, validation=0.000883
SB1 epoch  460/500: train=0.001301, validation=0.001366
SB1 epoch  470/500: train=0.000818, validation=0.000882
SB1 epoch  480/500: train=0.000869, validation=0.000929
SB1 epoch  490/500: train=0.000905, validation=0.000981
SB1 epoch  500/500: train=0.000776, validation=0.000830

Training SB2 on original + trust-region samples
SB2: concatenated original 10000 + tr 1342 samples -> 11342
SB2 epoch   10/500: train=0.044056, validation=0.045840
SB2 epoch   20/500: train=0.037902, validation=0.039616
SB2 epoch   30/500: train=0.028355, validation=0.029922
SB2 epoch   40/500: train=0.019456, validation=0.020332
SB2 epoch   50/500: train=0.014225, validation=0.014817
SB2 epoch   60/500: train=0.013244, validation=0.013800
SB2 epoch   70/500: train=0.012774, validation=0.013147
SB2 epoch   80/500: train=0.013656, validation=0.013941
SB2 epoch   90/500: train=0.010914, validation=0.011223
SB2 epoch  100/500: train=0.024892, validation=0.024585
SB2 epoch  110/500: train=0.042625, validation=0.041428
SB2 epoch  120/500: train=0.006013, validation=0.006298
SB2 epoch  130/500: train=0.005072, validation=0.005303
SB2 epoch  140/500: train=0.006160, validation=0.006319
SB2 epoch  150/500: train=0.003307, validation=0.003561
SB2 epoch  160/500: train=0.005661, validation=0.005827
SB2 epoch  170/500: train=0.006261, validation=0.006329
SB2 epoch  180/500: train=0.003868, validation=0.004031
SB2 epoch  190/500: train=0.006124, validation=0.006192
SB2 epoch  200/500: train=0.003278, validation=0.003478
SB2 epoch  210/500: train=0.001882, validation=0.002098
SB2 epoch  220/500: train=0.002463, validation=0.002654
SB2 epoch  230/500: train=0.001760, validation=0.001961
SB2 epoch  240/500: train=0.001684, validation=0.001870
SB2 epoch  250/500: train=0.003508, validation=0.003591
SB2 epoch  260/500: train=0.003194, validation=0.003283
SB2 epoch  270/500: train=0.001910, validation=0.002061
SB2 epoch  280/500: train=0.002063, validation=0.002196
SB2 epoch  290/500: train=0.002765, validation=0.002842
SB2 epoch  300/500: train=0.002352, validation=0.002424
SB2 epoch  310/500: train=0.004041, validation=0.004041
SB2 epoch  320/500: train=0.001486, validation=0.001616
SB2 epoch  330/500: train=0.001509, validation=0.001627
SB2 epoch  340/500: train=0.001216, validation=0.001327
SB2 epoch  350/500: train=0.001765, validation=0.001869
SB2 epoch  360/500: train=0.000926, validation=0.001049
SB2 epoch  370/500: train=0.002289, validation=0.002366
SB2 epoch  380/500: train=0.001171, validation=0.001281
SB2 epoch  390/500: train=0.000909, validation=0.001014
SB2 epoch  400/500: train=0.001036, validation=0.001149
SB2 epoch  410/500: train=0.000941, validation=0.001057
SB2 epoch  420/500: train=0.001187, validation=0.001284
SB2 epoch  430/500: train=0.000934, validation=0.001048
SB2 epoch  440/500: train=0.000770, validation=0.000887
SB2 epoch  450/500: train=0.000817, validation=0.000937
SB2 epoch  460/500: train=0.001570, validation=0.001664
SB2 epoch  470/500: train=0.001209, validation=0.001296
SB2 epoch  480/500: train=0.000951, validation=0.001051
SB2 epoch  490/500: train=0.000666, validation=0.000780
SB2 epoch  500/500: train=0.000830, validation=0.000938

Training BG1 on original + trust-region samples
BG1: concatenated original 10000 + tr 1097 samples -> 11097
BG1 epoch   10/500: train=0.021847, validation=0.022861
BG1 epoch   20/500: train=0.011281, validation=0.011768
BG1 epoch   30/500: train=0.006515, validation=0.006743
BG1 epoch   40/500: train=0.010494, validation=0.010914
BG1 epoch   50/500: train=0.005227, validation=0.005419
BG1 epoch   60/500: train=0.003477, validation=0.003592
BG1 epoch   70/500: train=0.013337, validation=0.013842
BG1 epoch   80/500: train=0.029017, validation=0.030214
BG1 epoch   90/500: train=0.004923, validation=0.005117
BG1 epoch  100/500: train=0.076088, validation=0.079516
BG1 epoch  110/500: train=0.003803, validation=0.003942
BG1 epoch  120/500: train=0.133607, validation=0.137706
BG1 epoch  130/500: train=0.003933, validation=0.004068
BG1 epoch  140/500: train=0.002314, validation=0.002392
BG1 epoch  150/500: train=0.004427, validation=0.004582
BG1 epoch  160/500: train=0.006152, validation=0.006409
BG1 epoch  170/500: train=0.011324, validation=0.011773
BG1 epoch  180/500: train=0.001986, validation=0.002059
BG1 epoch  190/500: train=0.003796, validation=0.003941
BG1 epoch  200/500: train=0.003247, validation=0.003385
BG1 epoch  210/500: train=0.002539, validation=0.002656
BG1 epoch  220/500: train=0.007016, validation=0.007334
BG1 epoch  230/500: train=0.018491, validation=0.019332
BG1 epoch  240/500: train=0.002737, validation=0.002869
BG1 epoch  250/500: train=0.003879, validation=0.004053
BG1 epoch  260/500: train=0.017746, validation=0.018586
BG1 epoch  270/500: train=0.002583, validation=0.002698
BG1 epoch  280/500: train=0.001599, validation=0.001673
BG1 epoch  290/500: train=0.002500, validation=0.002610
BG1 epoch  300/500: train=0.001706, validation=0.001788
BG1 epoch  310/500: train=0.001090, validation=0.001147
BG1 epoch  320/500: train=0.009967, validation=0.010414
BG1 epoch  330/500: train=0.000972, validation=0.001028
BG1 epoch  340/500: train=0.002169, validation=0.002280
BG1 epoch  350/500: train=0.009001, validation=0.009352
BG1 epoch  360/500: train=0.001220, validation=0.001289
BG1 epoch  370/500: train=0.003121, validation=0.003232
BG1 epoch  380/500: train=0.000973, validation=0.001029
BG1 epoch  390/500: train=0.001062, validation=0.001109
BG1 epoch  400/500: train=0.001151, validation=0.001191
BG1 epoch  410/500: train=0.000712, validation=0.000761
BG1 epoch  420/500: train=0.000624, validation=0.000664
BG1 epoch  430/500: train=0.000575, validation=0.000622
BG1 epoch  440/500: train=0.000483, validation=0.000527
BG1 epoch  450/500: train=0.000582, validation=0.000636
BG1 epoch  460/500: train=0.000557, validation=0.000616
BG1 epoch  470/500: train=0.000475, validation=0.000527
BG1 epoch  480/500: train=0.000575, validation=0.000627
BG1 epoch  490/500: train=0.000470, validation=0.000524
BG1 epoch  500/500: train=0.000545, validation=0.000597

Training BG2 on original + trust-region samples
BG2: concatenated original 10000 + tr 1064 samples -> 11064
BG2 epoch   10/500: train=0.020343, validation=0.020557
BG2 epoch   20/500: train=0.009760, validation=0.009702
BG2 epoch   30/500: train=0.005079, validation=0.005092
BG2 epoch   40/500: train=0.006951, validation=0.006822
BG2 epoch   50/500: train=0.006804, validation=0.006667
BG2 epoch   60/500: train=0.017148, validation=0.016434
BG2 epoch   70/500: train=0.005342, validation=0.005254
BG2 epoch   80/500: train=0.005632, validation=0.005526
BG2 epoch   90/500: train=0.005282, validation=0.005207
BG2 epoch  100/500: train=0.008445, validation=0.008182
BG2 epoch  110/500: train=0.002333, validation=0.002356
BG2 epoch  120/500: train=0.003308, validation=0.003310
BG2 epoch  130/500: train=0.004009, validation=0.003969
BG2 epoch  140/500: train=0.002461, validation=0.002475
BG2 epoch  150/500: train=0.003182, validation=0.003161
BG2 epoch  160/500: train=0.041912, validation=0.040157
BG2 epoch  170/500: train=0.002143, validation=0.002162
BG2 epoch  180/500: train=0.004804, validation=0.004675
BG2 epoch  190/500: train=0.001872, validation=0.001892
BG2 epoch  200/500: train=0.002346, validation=0.002340
BG2 epoch  210/500: train=0.002994, validation=0.002963
BG2 epoch  220/500: train=0.003502, validation=0.003437
BG2 epoch  230/500: train=0.003818, validation=0.003735
BG2 epoch  240/500: train=0.016161, validation=0.015533
BG2 epoch  250/500: train=0.002494, validation=0.002473
BG2 epoch  260/500: train=0.001657, validation=0.001673
BG2 epoch  270/500: train=0.004113, validation=0.004021
BG2 epoch  280/500: train=0.003587, validation=0.003552
BG2 epoch  290/500: train=0.006935, validation=0.006706
BG2 epoch  300/500: train=0.001920, validation=0.001919
BG2 epoch  310/500: train=0.001535, validation=0.001548
BG2 epoch  320/500: train=0.003109, validation=0.003052
BG2 epoch  330/500: train=0.015732, validation=0.015072
BG2 epoch  340/500: train=0.001621, validation=0.001626
BG2 epoch  350/500: train=0.002532, validation=0.002498
BG2 epoch  360/500: train=0.001504, validation=0.001519
BG2 epoch  370/500: train=0.000885, validation=0.000927
BG2 epoch  380/500: train=0.000817, validation=0.000853
BG2 epoch  390/500: train=0.002233, validation=0.002209
BG2 epoch  400/500: train=0.001030, validation=0.001062
BG2 epoch  410/500: train=0.000698, validation=0.000739
BG2 epoch  420/500: train=0.000685, validation=0.000731
BG2 epoch  430/500: train=0.001312, validation=0.001345
BG2 epoch  440/500: train=0.001064, validation=0.001103
BG2 epoch  450/500: train=0.000672, validation=0.000714
BG2 epoch  460/500: train=0.000694, validation=0.000740
BG2 epoch  470/500: train=0.000621, validation=0.000676
BG2 epoch  480/500: train=0.000617, validation=0.000664
BG2 epoch  490/500: train=0.000581, validation=0.000638
BG2 epoch  500/500: train=0.000495, validation=0.000549

Training IP1 on original + trust-region samples
IP1: concatenated original 10000 + tr 1309 samples -> 11309
IP1 epoch   10/500: train=1.413934, validation=1.591767
IP1 epoch   20/500: train=1.120366, validation=1.322676
IP1 epoch   30/500: train=0.952367, validation=1.155403
IP1 epoch   40/500: train=0.875138, validation=1.084070
IP1 epoch   50/500: train=0.744753, validation=0.967259
IP1 epoch   60/500: train=0.659942, validation=0.896831
IP1 epoch   70/500: train=0.933407, validation=1.198984
IP1 epoch   80/500: train=0.615294, validation=0.897033
IP1 epoch   90/500: train=0.577732, validation=0.866221
IP1 epoch  100/500: train=0.610511, validation=0.895862
IP1 epoch  110/500: train=0.970302, validation=1.283096
IP1 epoch  120/500: train=0.591095, validation=0.928472
IP1 epoch  130/500: train=0.576801, validation=0.922320
IP1 epoch  140/500: train=0.681782, validation=1.042679
IP1 epoch  150/500: train=0.990976, validation=1.391308
IP1 epoch  160/500: train=0.624251, validation=0.998748
IP1 epoch  170/500: train=0.776306, validation=1.162330
IP1 epoch  180/500: train=0.646985, validation=1.015460
IP1 epoch  190/500: train=0.378975, validation=0.759667
IP1 epoch  200/500: train=0.755493, validation=1.169225
IP1 epoch  210/500: train=0.613502, validation=1.024776
IP1 epoch  220/500: train=1.005210, validation=1.444374
IP1 epoch  230/500: train=0.573442, validation=0.987013
IP1 epoch  240/500: train=0.528444, validation=0.929451
IP1 epoch  250/500: train=0.405678, validation=0.814141
IP1 epoch  260/500: train=1.414718, validation=1.888454
IP1 epoch  270/500: train=0.929791, validation=1.375525
IP1 epoch  280/500: train=0.474635, validation=0.884921
IP1 epoch  290/500: train=0.338872, validation=0.773034
IP1 epoch  300/500: train=0.859407, validation=1.285301
IP1 epoch  310/500: train=0.558523, validation=1.001774
IP1 epoch  320/500: train=0.447794, validation=0.878861
IP1 epoch  330/500: train=0.505824, validation=0.952798
IP1 epoch  340/500: train=0.460490, validation=0.907670
IP1 epoch  350/500: train=0.678854, validation=1.121776
IP1 epoch  360/500: train=0.642914, validation=1.106630
IP1 epoch  370/500: train=0.825123, validation=1.287064
IP1 epoch  380/500: train=0.496658, validation=0.939529
IP1 epoch  390/500: train=1.115947, validation=1.623051
IP1 epoch  400/500: train=0.709362, validation=1.186246
IP1 epoch  410/500: train=0.408220, validation=0.861498
IP1 epoch  420/500: train=0.853061, validation=1.313173
IP1 epoch  430/500: train=0.425222, validation=0.889730
IP1 epoch  440/500: train=0.635090, validation=1.103964
IP1 epoch  450/500: train=0.531730, validation=1.002791
IP1 epoch  460/500: train=0.812013, validation=1.290459
IP1 epoch  470/500: train=0.711949, validation=1.204349
IP1 epoch  480/500: train=0.360466, validation=0.820899
IP1 epoch  490/500: train=0.419570, validation=0.889732
IP1 epoch  500/500: train=0.777192, validation=1.257545

          train_mse  validation_mse
scenario
SB1        0.000776        0.000830
SB2        0.000830        0.000938
BG1        0.000545        0.000597
BG2        0.000495        0.000549
IP1        0.777192        1.257545

In [14]:
tr_nn_config = NNSolverExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=X0,
    steps=20000,
    lr=NN_LEARNING_RATE,
    save_every=NN_SAVE_EVERY,
    history_path=str(RESULTS_DIR / "NN_solver_tr_ablation_history.csv"),
    evaluate_true=True,
    save_results=True,
    model_tag="tr",
)
tr_nn_result = run_nn_solver_experiment(tr_nn_config)
tr_nn_prices = np.asarray(tr_nn_result["optimal pi"], dtype=float).reshape(
    len(SCENARIOS), T
)

print("TR-retrained NN history:", tr_nn_result["history_path"])
print("TR-retrained NN true objective:", tr_nn_result["true_obj"])
print("TR-retrained NN runtime (s):", tr_nn_result["runtime_seconds"])

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[0] loss=5804.0781, obj=-122.5196, eq=5.9195, soc=0.0647, bound=0.0646, true_loss=2.2705
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[200] loss=139.5479, obj=-68.7493, eq=0.2044, soc=0.0369, bound=0.0250, true_loss=-4.5952
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[400] loss=32.2781, obj=-54.8262, eq=0.0853, soc=0.0167, bound=0.0100, true_loss=-11.0933
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[600] loss=-11.4048, obj=-46.8446, eq=0.0347, soc=0.0076, bound=0.0027, true_loss=-17.0358
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[800] loss=-29.8241, obj=-49.0194, eq=0.0187, soc=0.0044, bound=0.0010, true_loss=-24.6689
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1000] loss=-40.8956, obj=-54.1651, eq=0.0130, soc=0.0031, bound=0.0004, true_loss=-30.5078
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1200] loss=-49.7419, obj=-59.6312, eq=0.0097, soc=0.0023, bound=0.0002, true_loss=-37.1331
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1400] loss=-56.6627, obj=-65.5022, eq=0.0086, soc=0.0020, bound=0.0001, true_loss=-44.5269
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1600] loss=-63.5943, obj=-71.0857, eq=0.0073, soc=0.0018, bound=0.0001, true_loss=-51.6916
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1800] loss=-69.7310, obj=-76.7978, eq=0.0069, soc=0.0017, bound=0.0001, true_loss=-57.6418
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2000] loss=-73.0037, obj=-80.0479, eq=0.0069, soc=0.0017, bound=0.0001, true_loss=-61.8337
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2200] loss=-75.1197, obj=-82.6186, eq=0.0073, soc=0.0017, bound=0.0001, true_loss=-64.6303
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2400] loss=-77.1794, obj=-83.9618, eq=0.0066, soc=0.0017, bound=0.0001, true_loss=-64.9360
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2600] loss=-78.4080, obj=-85.2529, eq=0.0067, soc=0.0017, bound=0.0001, true_loss=-65.9245
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2800] loss=-79.4956, obj=-86.4419, eq=0.0068, soc=0.0017, bound=0.0001, true_loss=-66.6163
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3000] loss=-80.5249, obj=-87.6886, eq=0.0070, soc=0.0016, bound=0.0001, true_loss=-67.9133
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3200] loss=-83.5551, obj=-90.7446, eq=0.0070, soc=0.0016, bound=0.0001, true_loss=-71.2674
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3400] loss=-86.9012, obj=-94.0034, eq=0.0069, soc=0.0017, bound=0.0001, true_loss=-73.6818
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3600] loss=-90.4678, obj=-97.9051, eq=0.0073, soc=0.0018, bound=0.0001, true_loss=-76.9467
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3800] loss=-95.6941, obj=-102.9599, eq=0.0071, soc=0.0019, bound=0.0001, true_loss=-78.2661
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4000] loss=-104.5456, obj=-112.3011, eq=0.0076, soc=0.0018, bound=0.0002, true_loss=-80.1222
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4200] loss=-110.1945, obj=-118.4973, eq=0.0081, soc=0.0018, bound=0.0002, true_loss=-81.7580
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4400] loss=-117.0351, obj=-125.1447, eq=0.0079, soc=0.0017, bound=0.0001, true_loss=-82.7139
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4600] loss=-119.8050, obj=-127.0614, eq=0.0071, soc=0.0017, bound=0.0001, true_loss=-83.9738
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4800] loss=-121.7270, obj=-128.5927, eq=0.0067, soc=0.0017, bound=0.0001, true_loss=-84.8901
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5000] loss=-122.5890, obj=-129.7343, eq=0.0070, soc=0.0017, bound=0.0001, true_loss=-85.9216
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5200] loss=-122.5279, obj=-130.6690, eq=0.0080, soc=0.0017, bound=0.0001, true_loss=-86.8463
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026

## 4. Generate an equal-size global-random control dataset

For each follower instance, prices are drawn independently and uniformly from $[0,1.5]^{24}$. The requested sample count is the actual number of unique trust-region rows exported for that same instance. Existing `_new` arrays are never loaded or reused.

In [8]:
def generate_fresh_random_samples(
    scenario,
    n_samples,
    *,
    seed,
    checkpoint_interval=100,
    max_consecutive_failures=20,
):
    """Generate a fresh deterministic `_new` dataset for one instance."""
    if n_samples <= 0:
        raise ValueError("n_samples must be positive.")

    set_global_seed(seed)
    rng = make_rng(seed)
    solver_options = {
        **INSTANCE_SOLVER_KWARGS[scenario],
        "failure_mode": "none",
        "include_metadata": True,
        "time_limit": LOWER_TIME_LIMIT,
        "mip_gap": LOWER_MIP_GAP,
    }
    lower_solver = follower_solver.build_solver(
        INSTANCE_TYPES[scenario],
        T=T,
        net=INSTANCE_NETWORKS[scenario],
        **solver_options,
    )

    x_path = DATA_DIR / f"X_{scenario}_new.npy"
    y_path = DATA_DIR / f"Y_{scenario}_new.npy"
    x_data = np.empty((n_samples, T), dtype=float)
    y_data = np.empty((n_samples, T), dtype=float)
    completed = 0
    attempts = 0
    failures = 0
    consecutive_failures = 0
    checkpoint_start = time.time()

    print(f"{scenario}: generating {n_samples} fresh samples (seed={seed}).")
    while completed < n_samples:
        attempts += 1
        price = rng.uniform(0.0, 1.5, size=T)
        result = lower_solver.lower_solve(price)
        if result is None:
            failures += 1
            consecutive_failures += 1
            print(
                f"{scenario}: skipped failed attempt {attempts}; "
                f"collected {completed}/{n_samples}."
            )
            if consecutive_failures >= max_consecutive_failures:
                raise RuntimeError(
                    f"{scenario}: stopped after {consecutive_failures} "
                    "consecutive lower-level failures."
                )
            continue

        consecutive_failures = 0
        response = np.asarray(result["p_mg"], dtype=float).reshape(T)
        if not np.isfinite(response).all():
            raise ValueError(f"{scenario}: follower returned a non-finite response.")
        x_data[completed] = price
        y_data[completed] = response
        completed += 1

        if completed % checkpoint_interval == 0 or completed == n_samples:
            atomic_save_npy(x_path, x_data[:completed])
            atomic_save_npy(y_path, y_data[:completed])
            elapsed = time.time() - checkpoint_start
            print(
                f"{scenario}: saved {completed}/{n_samples} fresh samples "
                f"({failures} failed attempts, {elapsed:.1f} s)."
            )
            checkpoint_start = time.time()

    return x_data, y_data

In [9]:
new_data = {}
for scenario in SCENARIOS:
    new_data[scenario] = generate_fresh_random_samples(
        scenario,
        tr_sample_counts[scenario],
        seed=NEW_DATA_SEEDS[scenario],
        checkpoint_interval=NEW_DATA_CHECKPOINT_INTERVAL,
    )

sample_rows = []
for scenario in SCENARIOS:
    original_x, _ = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy",
        DATA_DIR / f"Y_{scenario}.npy",
    )
    tr_x, _ = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_tr.npy",
        DATA_DIR / f"Y_{scenario}_tr.npy",
    )
    new_x, _ = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_new.npy",
        DATA_DIR / f"Y_{scenario}_new.npy",
        expected_rows=len(tr_x),
    )
    if len(new_x) != len(tr_x):
        raise AssertionError(
            f"{scenario}: new sample count {len(new_x)} != TR count {len(tr_x)}."
        )
    sample_rows.append(
        {
            "scenario": scenario,
            "original_samples": len(original_x),
            "trust_region_samples": len(tr_x),
            "new_random_samples": len(new_x),
            "tr_combined_samples": len(original_x) + len(tr_x),
            "new_combined_samples": len(original_x) + len(new_x),
        }
    )

sample_count_table = pd.DataFrame(sample_rows).set_index("scenario")
if not (
    sample_count_table["trust_region_samples"]
    == sample_count_table["new_random_samples"]
).all():
    raise AssertionError("Random and trust-region sample counts must match.")
display(sample_count_table)

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

SB1: generating 1392 fresh samples (seed=4201).
SB1: saved 100/1392 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 200/1392 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 300/1392 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 400/1392 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 500/1392 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 600/1392 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 700/1392 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 800/1392 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 900/1392 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 1000/1392 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 1100/1392 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 1200/1392 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 1300/1392 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 1392/1392 fresh samples (0 failed attempts, 1.5 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

SB2: generating 1342 fresh samples (seed=4202).
SB2: saved 100/1342 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 200/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 300/1342 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 400/1342 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 500/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 600/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 700/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 800/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 900/1342 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 1000/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 1100/1342 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 1200/1342 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 1300/1342 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 1342/1342 fresh samples (0 failed attempts, 0.8 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

BG1: generating 1097 fresh samples (seed=4203).
BG1: saved 100/1097 fresh samples (0 failed attempts, 8.9 s).
BG1: saved 200/1097 fresh samples (0 failed attempts, 9.6 s).
BG1: saved 300/1097 fresh samples (0 failed attempts, 10.2 s).
BG1: saved 400/1097 fresh samples (0 failed attempts, 10.8 s).
BG1: saved 500/1097 fresh samples (0 failed attempts, 11.3 s).
BG1: saved 600/1097 fresh samples (0 failed attempts, 11.8 s).
BG1: saved 700/1097 fresh samples (0 failed attempts, 12.2 s).
BG1: saved 800/1097 fresh samples (0 failed attempts, 12.7 s).
BG1: saved 900/1097 fresh samples (0 failed attempts, 13.5 s).
BG1: saved 1000/1097 fresh samples (0 failed attempts, 14.4 s).
BG1: saved 1097/1097 fresh samples (0 failed attempts, 14.4 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

BG2: generating 1064 fresh samples (seed=4204).
BG2: saved 100/1064 fresh samples (0 failed attempts, 9.2 s).
BG2: saved 200/1064 fresh samples (0 failed attempts, 10.7 s).
BG2: saved 300/1064 fresh samples (0 failed attempts, 10.7 s).
BG2: saved 400/1064 fresh samples (0 failed attempts, 11.2 s).
BG2: saved 500/1064 fresh samples (0 failed attempts, 12.0 s).
BG2: saved 600/1064 fresh samples (0 failed attempts, 12.3 s).
BG2: saved 700/1064 fresh samples (0 failed attempts, 12.7 s).
BG2: saved 800/1064 fresh samples (0 failed attempts, 13.1 s).
BG2: saved 900/1064 fresh samples (0 failed attempts, 13.7 s).
BG2: saved 1000/1064 fresh samples (0 failed attempts, 14.5 s).
BG2: saved 1064/1064 fresh samples (0 failed attempts, 9.7 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

IP1: generating 1309 fresh samples (seed=4205).
IP1: saved 100/1309 fresh samples (0 failed attempts, 71.9 s).
IP1: saved 200/1309 fresh samples (0 failed attempts, 73.6 s).
IP1: saved 300/1309 fresh samples (0 failed attempts, 79.8 s).
IP1: saved 400/1309 fresh samples (0 failed attempts, 78.7 s).
IP1: saved 500/1309 fresh samples (0 failed attempts, 74.8 s).
IP1: saved 600/1309 fresh samples (0 failed attempts, 82.3 s).
IP1: saved 700/1309 fresh samples (0 failed attempts, 88.6 s).
IP1: saved 800/1309 fresh samples (0 failed attempts, 77.5 s).
IP1: saved 900/1309 fresh samples (0 failed attempts, 91.0 s).
IP1: saved 1000/1309 fresh samples (0 failed attempts, 81.5 s).
IP1: saved 1100/1309 fresh samples (0 failed attempts, 77.2 s).
IP1: saved 1200/1309 fresh samples (0 failed attempts, 71.9 s).
IP1: saved 1300/1309 fresh samples (0 failed attempts, 81.0 s).
IP1: saved 1309/1309 fresh samples (0 failed attempts, 7.8 s).

,original_samples,trust_region_samples,new_random_samples,tr_combined_samples,new_combined_samples
scenario,,,,,
SB1,10000,1392,1392,11392,11392
SB2,10000,1342,1342,11342,11342
BG1,10000,1097,1097,11097,11097
BG2,10000,1064,1064,11064,11064
IP1,10000,1309,1309,11309,11309

## 5. Retrain global models on original + equal-size random samples

Training writes `L2O_XX_new.pth/.json`, then the NN solver uses the same initial point and optimization budget as the other NN runs.

In [10]:
new_training_results = {}
for scenario in SCENARIOS:
    print(f"\nTraining {scenario} on original + equal-size global random samples")
    new_training_results[scenario] = train(
        scenario,
        config=training_config(scenario),
        data_tag="new",
        model_tag="new",
        include_original=True,
    )
    for suffix in (".pth", ".json"):
        expected_model = MODEL_DIR / f"L2O_{scenario}_new{suffix}"
        if not expected_model.is_file():
            raise FileNotFoundError(expected_model)

display(pd.DataFrame(new_training_results).T.rename_axis("scenario"))

Training SB1 on original + equal-size global random samples
SB1: concatenated original 10000 + new 1392 samples -> 11392
SB1 epoch   10/500: train=0.054344, validation=0.056812
SB1 epoch   20/500: train=0.037359, validation=0.039618
SB1 epoch   30/500: train=0.031813, validation=0.033871
SB1 epoch   40/500: train=0.024504, validation=0.026595
SB1 epoch   50/500: train=0.015438, validation=0.016905
SB1 epoch   60/500: train=0.012559, validation=0.013723
SB1 epoch   70/500: train=0.010040, validation=0.011200
SB1 epoch   80/500: train=0.009581, validation=0.010699
SB1 epoch   90/500: train=0.005985, validation=0.006853
SB1 epoch  100/500: train=0.004866, validation=0.005639
SB1 epoch  110/500: train=0.003688, validation=0.004289
SB1 epoch  120/500: train=0.003270, validation=0.003825
SB1 epoch  130/500: train=0.002841, validation=0.003403
SB1 epoch  140/500: train=0.002269, validation=0.002771
SB1 epoch  150/500: train=0.002699, validation=0.003192
SB1 epoch  160/500: train=0.001717, validation=0.002185
SB1 epoch  170/500: train=0.001585, validation=0.001921
SB1 epoch  180/500: train=0.001833, validation=0.002161
SB1 epoch  190/500: train=0.001532, validation=0.001864
SB1 epoch  200/500: train=0.001491, validation=0.001851
SB1 epoch  210/500: train=0.001586, validation=0.001921
SB1 epoch  220/500: train=0.001333, validation=0.001620
SB1 epoch  230/500: train=0.001354, validation=0.001720
SB1 epoch  240/500: train=0.001287, validation=0.001616
SB1 epoch  250/500: train=0.001002, validation=0.001194
SB1 epoch  260/500: train=0.001076, validation=0.001290
SB1 epoch  270/500: train=0.001147, validation=0.001399
SB1 epoch  280/500: train=0.001202, validation=0.001426
SB1 epoch  290/500: train=0.001249, validation=0.001482
SB1 epoch  300/500: train=0.000921, validation=0.001104
SB1 epoch  310/500: train=0.001169, validation=0.001357
SB1 epoch  320/500: train=0.001730, validation=0.002060
SB1 epoch  330/500: train=0.001121, validation=0.001364
SB1 epoch  340/500: train=0.000934, validation=0.001149
SB1 epoch  350/500: train=0.000801, validation=0.000994
SB1 epoch  360/500: train=0.001111, validation=0.001294
SB1 epoch  370/500: train=0.000953, validation=0.001133
SB1 epoch  380/500: train=0.001682, validation=0.001975
SB1 epoch  390/500: train=0.001212, validation=0.001355
SB1 epoch  400/500: train=0.000970, validation=0.001007
SB1 epoch  410/500: train=0.001105, validation=0.001062
SB1 epoch  420/500: train=0.000774, validation=0.000803
SB1 epoch  430/500: train=0.000816, validation=0.000858
SB1 epoch  440/500: train=0.000762, validation=0.000810
SB1 epoch  450/500: train=0.000616, validation=0.000718
SB1 epoch  460/500: train=0.000836, validation=0.000864
SB1 epoch  470/500: train=0.000899, validation=0.000942
SB1 epoch  480/500: train=0.000913, validation=0.000942
SB1 epoch  490/500: train=0.001150, validation=0.001095
SB1 epoch  500/500: train=0.000735, validation=0.000748

Training SB2 on original + equal-size global random samples
SB2: concatenated original 10000 + new 1342 samples -> 11342
SB2 epoch   10/500: train=0.061361, validation=0.064887
SB2 epoch   20/500: train=0.041725, validation=0.044285
SB2 epoch   30/500: train=0.035942, validation=0.038126
SB2 epoch   40/500: train=0.027987, validation=0.030173
SB2 epoch   50/500: train=0.019534, validation=0.020913
SB2 epoch   60/500: train=0.014564, validation=0.015558
SB2 epoch   70/500: train=0.011729, validation=0.012797
SB2 epoch   80/500: train=0.009464, validation=0.010537
SB2 epoch   90/500: train=0.007938, validation=0.008963
SB2 epoch  100/500: train=0.006038, validation=0.006905
SB2 epoch  110/500: train=0.004369, validation=0.005100
SB2 epoch  120/500: train=0.003723, validation=0.004355
SB2 epoch  130/500: train=0.003212, validation=0.003784
SB2 epoch  140/500: train=0.002351, validation=0.002860
SB2 epoch  150/500: train=0.002260, validation=0.002708
SB2 epoch  160/500: train=0.001919, validation=0.002388
SB2 epoch  170/500: train=0.001883, validation=0.002349
SB2 epoch  180/500: train=0.001688, validation=0.002091
SB2 epoch  190/500: train=0.001463, validation=0.001839
SB2 epoch  200/500: train=0.001518, validation=0.001909
SB2 epoch  210/500: train=0.001461, validation=0.001820
SB2 epoch  220/500: train=0.001211, validation=0.001581
SB2 epoch  230/500: train=0.001260, validation=0.001611
SB2 epoch  240/500: train=0.001266, validation=0.001570
SB2 epoch  250/500: train=0.001202, validation=0.001473
SB2 epoch  260/500: train=0.001112, validation=0.001439
SB2 epoch  270/500: train=0.001068, validation=0.001345
SB2 epoch  280/500: train=0.001059, validation=0.001318
SB2 epoch  290/500: train=0.000893, validation=0.001132
SB2 epoch  300/500: train=0.000924, validation=0.001179
SB2 epoch  310/500: train=0.001119, validation=0.001377
SB2 epoch  320/500: train=0.000923, validation=0.001227
SB2 epoch  330/500: train=0.000870, validation=0.001111
SB2 epoch  340/500: train=0.000784, validation=0.001007
SB2 epoch  350/500: train=0.000775, validation=0.001001
SB2 epoch  360/500: train=0.000914, validation=0.001114
SB2 epoch  370/500: train=0.000733, validation=0.000963
SB2 epoch  380/500: train=0.000765, validation=0.000986
SB2 epoch  390/500: train=0.000807, validation=0.000988
SB2 epoch  400/500: train=0.000810, validation=0.001035
SB2 epoch  410/500: train=0.000793, validation=0.000975
SB2 epoch  420/500: train=0.000671, validation=0.000877
SB2 epoch  430/500: train=0.000803, validation=0.001012
SB2 epoch  440/500: train=0.000721, validation=0.000930
SB2 epoch  450/500: train=0.000760, validation=0.000943
SB2 epoch  460/500: train=0.000676, validation=0.000911
SB2 epoch  470/500: train=0.000663, validation=0.000836
SB2 epoch  480/500: train=0.000629, validation=0.000813
SB2 epoch  490/500: train=0.000576, validation=0.000771
SB2 epoch  500/500: train=0.000595, validation=0.000802

Training BG1 on original + equal-size global random samples
BG1: concatenated original 10000 + new 1097 samples -> 11097
BG1 epoch   10/500: train=0.024829, validation=0.025917
BG1 epoch   20/500: train=0.011833, validation=0.012292
BG1 epoch   30/500: train=0.008742, validation=0.009065
BG1 epoch   40/500: train=0.005801, validation=0.006041
BG1 epoch   50/500: train=0.004728, validation=0.004868
BG1 epoch   60/500: train=0.003792, validation=0.003953
BG1 epoch   70/500: train=0.003257, validation=0.003414
BG1 epoch   80/500: train=0.002481, validation=0.002603
BG1 epoch   90/500: train=0.002332, validation=0.002479
BG1 epoch  100/500: train=0.002090, validation=0.002255
BG1 epoch  110/500: train=0.001689, validation=0.001842
BG1 epoch  120/500: train=0.001550, validation=0.001715
BG1 epoch  130/500: train=0.001417, validation=0.001555
BG1 epoch  140/500: train=0.001085, validation=0.001198
BG1 epoch  150/500: train=0.000908, validation=0.000993
BG1 epoch  160/500: train=0.000809, validation=0.000880
BG1 epoch  170/500: train=0.000776, validation=0.000841
BG1 epoch  180/500: train=0.000693, validation=0.000754
BG1 epoch  190/500: train=0.000694, validation=0.000760
BG1 epoch  200/500: train=0.000648, validation=0.000711
BG1 epoch  210/500: train=0.000633, validation=0.000702
BG1 epoch  220/500: train=0.000666, validation=0.000732
BG1 epoch  230/500: train=0.000607, validation=0.000677
BG1 epoch  240/500: train=0.000633, validation=0.000706
BG1 epoch  250/500: train=0.000588, validation=0.000659
BG1 epoch  260/500: train=0.000589, validation=0.000661
BG1 epoch  270/500: train=0.000596, validation=0.000670
BG1 epoch  280/500: train=0.000543, validation=0.000611
BG1 epoch  290/500: train=0.000534, validation=0.000614
BG1 epoch  300/500: train=0.000532, validation=0.000607
BG1 epoch  310/500: train=0.000517, validation=0.000592
BG1 epoch  320/500: train=0.000507, validation=0.000587
BG1 epoch  330/500: train=0.000519, validation=0.000604
BG1 epoch  340/500: train=0.000496, validation=0.000577
BG1 epoch  350/500: train=0.000493, validation=0.000580
BG1 epoch  360/500: train=0.000465, validation=0.000550
BG1 epoch  370/500: train=0.000487, validation=0.000570
BG1 epoch  380/500: train=0.000499, validation=0.000595
BG1 epoch  390/500: train=0.000477, validation=0.000566
BG1 epoch  400/500: train=0.000470, validation=0.000562
BG1 epoch  410/500: train=0.000457, validation=0.000542
BG1 epoch  420/500: train=0.000422, validation=0.000514
BG1 epoch  430/500: train=0.000448, validation=0.000535
BG1 epoch  440/500: train=0.000436, validation=0.000531
BG1 epoch  450/500: train=0.000402, validation=0.000495
BG1 epoch  460/500: train=0.000410, validation=0.000504
BG1 epoch  470/500: train=0.000430, validation=0.000526
BG1 epoch  480/500: train=0.000410, validation=0.000506
BG1 epoch  490/500: train=0.000425, validation=0.000517
BG1 epoch  500/500: train=0.000441, validation=0.000535

Training BG2 on original + equal-size global random samples
BG2: concatenated original 10000 + new 1064 samples -> 11064
BG2 epoch   10/500: train=0.022420, validation=0.023812
BG2 epoch   20/500: train=0.012495, validation=0.012948
BG2 epoch   30/500: train=0.007922, validation=0.008172
BG2 epoch   40/500: train=0.007398, validation=0.007697
BG2 epoch   50/500: train=0.004960, validation=0.005182
BG2 epoch   60/500: train=0.004159, validation=0.004355
BG2 epoch   70/500: train=0.003485, validation=0.003683
BG2 epoch   80/500: train=0.002741, validation=0.002896
BG2 epoch   90/500: train=0.002499, validation=0.002661
BG2 epoch  100/500: train=0.002333, validation=0.002490
BG2 epoch  110/500: train=0.001894, validation=0.002043
BG2 epoch  120/500: train=0.001859, validation=0.001991
BG2 epoch  130/500: train=0.001752, validation=0.001878
BG2 epoch  140/500: train=0.001381, validation=0.001492
BG2 epoch  150/500: train=0.001242, validation=0.001333
BG2 epoch  160/500: train=0.000948, validation=0.001033
BG2 epoch  170/500: train=0.000922, validation=0.000991
BG2 epoch  180/500: train=0.000801, validation=0.000880
BG2 epoch  190/500: train=0.000712, validation=0.000789
BG2 epoch  200/500: train=0.000720, validation=0.000795
BG2 epoch  210/500: train=0.000690, validation=0.000773
BG2 epoch  220/500: train=0.000649, validation=0.000717
BG2 epoch  230/500: train=0.000683, validation=0.000759
BG2 epoch  240/500: train=0.000600, validation=0.000678
BG2 epoch  250/500: train=0.000628, validation=0.000705
BG2 epoch  260/500: train=0.000598, validation=0.000682
BG2 epoch  270/500: train=0.000614, validation=0.000698
BG2 epoch  280/500: train=0.000575, validation=0.000661
BG2 epoch  290/500: train=0.000602, validation=0.000689
BG2 epoch  300/500: train=0.000546, validation=0.000629
BG2 epoch  310/500: train=0.000528, validation=0.000613
BG2 epoch  320/500: train=0.000573, validation=0.000664
BG2 epoch  330/500: train=0.000520, validation=0.000610
BG2 epoch  340/500: train=0.000531, validation=0.000627
BG2 epoch  350/500: train=0.000519, validation=0.000609
BG2 epoch  360/500: train=0.000520, validation=0.000618
BG2 epoch  370/500: train=0.000485, validation=0.000582
BG2 epoch  380/500: train=0.000504, validation=0.000597
BG2 epoch  390/500: train=0.000470, validation=0.000571
BG2 epoch  400/500: train=0.000499, validation=0.000597
BG2 epoch  410/500: train=0.000477, validation=0.000582
BG2 epoch  420/500: train=0.000499, validation=0.000605
BG2 epoch  430/500: train=0.000460, validation=0.000567
BG2 epoch  440/500: train=0.000481, validation=0.000596
BG2 epoch  450/500: train=0.000465, validation=0.000570
BG2 epoch  460/500: train=0.000488, validation=0.000593
BG2 epoch  470/500: train=0.000479, validation=0.000577
BG2 epoch  480/500: train=0.000480, validation=0.000591
BG2 epoch  490/500: train=0.000450, validation=0.000558
BG2 epoch  500/500: train=0.000468, validation=0.000568

Training IP1 on original + equal-size global random samples
IP1: concatenated original 10000 + new 1309 samples -> 11309
IP1 epoch   10/500: train=1.477956, validation=1.764430
IP1 epoch   20/500: train=1.092424, validation=1.421035
IP1 epoch   30/500: train=0.933006, validation=1.255044
IP1 epoch   40/500: train=0.830534, validation=1.160701
IP1 epoch   50/500: train=0.692532, validation=1.032303
IP1 epoch   60/500: train=0.629588, validation=0.991229
IP1 epoch   70/500: train=0.579369, validation=0.942318
IP1 epoch   80/500: train=0.547089, validation=0.916845
IP1 epoch   90/500: train=0.516816, validation=0.910559
IP1 epoch  100/500: train=0.496282, validation=0.893577
IP1 epoch  110/500: train=0.475213, validation=0.882353
IP1 epoch  120/500: train=0.442100, validation=0.862158
IP1 epoch  130/500: train=0.422674, validation=0.850295
IP1 epoch  140/500: train=0.414797, validation=0.840633
IP1 epoch  150/500: train=0.393665, validation=0.834678
IP1 epoch  160/500: train=0.382103, validation=0.825793
IP1 epoch  170/500: train=0.360212, validation=0.814062
IP1 epoch  180/500: train=0.370405, validation=0.834517
IP1 epoch  190/500: train=0.356096, validation=0.818915
IP1 epoch  200/500: train=0.341507, validation=0.811661
IP1 epoch  210/500: train=0.336965, validation=0.814160
IP1 epoch  220/500: train=0.333587, validation=0.820371
IP1 epoch  230/500: train=0.317337, validation=0.798120
IP1 epoch  240/500: train=0.314446, validation=0.800733
IP1 epoch  250/500: train=0.297879, validation=0.789687
IP1 epoch  260/500: train=0.299923, validation=0.800113
IP1 epoch  270/500: train=0.296157, validation=0.788500
IP1 epoch  280/500: train=0.287814, validation=0.785523
IP1 epoch  290/500: train=0.286766, validation=0.781367
IP1 epoch  300/500: train=0.280896, validation=0.777127
IP1 epoch  310/500: train=0.279542, validation=0.784983
IP1 epoch  320/500: train=0.274619, validation=0.777262
IP1 epoch  330/500: train=0.267210, validation=0.773387
IP1 epoch  340/500: train=0.265364, validation=0.771508
IP1 epoch  350/500: train=0.263622, validation=0.773870
IP1 epoch  360/500: train=0.264847, validation=0.769822
IP1 epoch  370/500: train=0.260163, validation=0.773032
IP1 epoch  380/500: train=0.261787, validation=0.776060
IP1 epoch  390/500: train=0.253263, validation=0.772703
IP1 epoch  400/500: train=0.255067, validation=0.775332
IP1 epoch  410/500: train=0.250008, validation=0.768789
IP1 epoch  420/500: train=0.245845, validation=0.768297
IP1 epoch  430/500: train=0.242451, validation=0.762469
IP1 epoch  440/500: train=0.241364, validation=0.765548
IP1 epoch  450/500: train=0.237414, validation=0.760734
IP1 epoch  460/500: train=0.241355, validation=0.761315
IP1 epoch  470/500: train=0.237192, validation=0.760946
IP1 epoch  480/500: train=0.246292, validation=0.779864
IP1 epoch  490/500: train=0.235301, validation=0.766779
IP1 epoch  500/500: train=0.234742, validation=0.757823

          train_mse  validation_mse
scenario
SB1        0.000735        0.000748
SB2        0.000595        0.000802
BG1        0.000441        0.000535
BG2        0.000468        0.000568
IP1        0.234742        0.757823

In [15]:
new_nn_config = NNSolverExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=X0,
    steps=20000,
    lr=NN_LEARNING_RATE,
    save_every=NN_SAVE_EVERY,
    history_path=str(RESULTS_DIR / "NN_solver_new_ablation_history.csv"),
    evaluate_true=True,
    save_results=True,
    model_tag="new",
)
new_nn_result = run_nn_solver_experiment(new_nn_config)
new_nn_prices = np.asarray(new_nn_result["optimal pi"], dtype=float).reshape(
    len(SCENARIOS), T
)

print("Random-retrained NN history:", new_nn_result["history_path"])
print("Random-retrained NN true objective:", new_nn_result["true_obj"])
print("Random-retrained NN runtime (s):", new_nn_result["runtime_seconds"])

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[0] loss=6079.8252, obj=-123.3201, eq=6.1960, soc=0.0647, bound=0.0646, true_loss=1.2892
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[200] loss=132.8055, obj=-65.6807, eq=0.1947, soc=0.0350, bound=0.0241, true_loss=-3.0122
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[400] loss=32.4037, obj=-51.4451, eq=0.0822, soc=0.0157, bound=0.0106, true_loss=-9.9868
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[600] loss=-7.6863, obj=-41.4533, eq=0.0330, soc=0.0070, bound=0.0027, true_loss=-13.9449
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[800] loss=-22.1596, obj=-38.6537, eq=0.0161, soc=0.0036, bound=0.0009, true_loss=-18.9925
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1000] loss=-29.8806, obj=-40.3972, eq=0.0103, soc=0.0023, bound=0.0005, true_loss=-24.0399
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1200] loss=-36.4401, obj=-45.1338, eq=0.0085, soc=0.0019, bound=0.0004, true_loss=-31.2284
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1400] loss=-42.1794, obj=-50.4910, eq=0.0081, soc=0.0018, bound=0.0003, true_loss=-37.2370
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1600] loss=-48.7495, obj=-56.0741, eq=0.0072, soc=0.0016, bound=0.0003, true_loss=-42.9512
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1800] loss=-55.0378, obj=-62.3409, eq=0.0071, soc=0.0016, bound=0.0003, true_loss=-49.1297
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2000] loss=-60.3285, obj=-68.7337, eq=0.0082, soc=0.0017, bound=0.0002, true_loss=-54.9290
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2200] loss=-66.6580, obj=-74.6029, eq=0.0078, soc=0.0017, bound=0.0002, true_loss=-60.1101
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2400] loss=-72.1720, obj=-79.6492, eq=0.0073, soc=0.0016, bound=0.0002, true_loss=-64.9947
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2600] loss=-76.9226, obj=-84.1398, eq=0.0071, soc=0.0016, bound=0.0002, true_loss=-68.7626
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2800] loss=-80.7701, obj=-88.1047, eq=0.0072, soc=0.0016, bound=0.0002, true_loss=-72.6127
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3000] loss=-84.9351, obj=-91.6203, eq=0.0065, soc=0.0016, bound=0.0002, true_loss=-75.4955
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3200] loss=-86.7123, obj=-94.5617, eq=0.0077, soc=0.0016, bound=0.0002, true_loss=-78.2936
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3400] loss=-89.2166, obj=-97.0494, eq=0.0077, soc=0.0016, bound=0.0002, true_loss=-81.0051
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3600] loss=-92.5209, obj=-99.1425, eq=0.0065, soc=0.0015, bound=0.0002, true_loss=-83.1749
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3800] loss=-94.1482, obj=-101.0031, eq=0.0067, soc=0.0016, bound=0.0002, true_loss=-84.8742
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4000] loss=-95.3348, obj=-102.5191, eq=0.0070, soc=0.0016, bound=0.0002, true_loss=-86.3659
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4200] loss=-96.7461, obj=-103.8081, eq=0.0069, soc=0.0016, bound=0.0002, true_loss=-87.6531
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4400] loss=-98.0993, obj=-104.9767, eq=0.0067, soc=0.0016, bound=0.0002, true_loss=-88.3029
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4600] loss=-99.2772, obj=-105.8616, eq=0.0064, soc=0.0016, bound=0.0002, true_loss=-89.1715
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4800] loss=-97.9117, obj=-106.6328, eq=0.0086, soc=0.0017, bound=0.0002, true_loss=-89.7494
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5000] loss=-100.7782, obj=-107.2857, eq=0.0063, soc=0.0016, bound=0.0002, true_loss=-90.5507
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5200] loss=-101.3548, obj=-107.8666, eq=0.0064, soc=0.0016, bound=0.0002, true_loss=-91.1836
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026

## 6. Four-way solution and high-fidelity objective comparison

Lower true objective values are better. The key ablation comparison is between the two equally sized augmented training sets.

In [13]:
tr_saved_paths = tr_result.get("saved_paths", {})
comparison = pd.DataFrame(
    [
        {
            "method": "Original NN",
            "true_objective": float(original_nn_result["true_obj"]),
            "runtime_seconds": float(original_nn_result["runtime_seconds"]),
            "iterations": NN_STEPS,
            "composite_queries": np.nan,
            "history_or_result_path": original_nn_result["history_path"],
        },
        {
            "method": "Trust region",
            "true_objective": tr_objective,
            "runtime_seconds": float(tr_result["elapsed_seconds"]),
            "iterations": int(tr_result["n_iter"]),
            "composite_queries": tr_composite_queries,
            "history_or_result_path": tr_saved_paths.get("json"),
        },
        {
            "method": "NN: original + TR samples",
            "true_objective": float(tr_nn_result["true_obj"]),
            "runtime_seconds": float(tr_nn_result["runtime_seconds"]),
            "iterations": NN_STEPS,
            "composite_queries": np.nan,
            "history_or_result_path": tr_nn_result["history_path"],
        },
        {
            "method": "NN: original + equal global random samples",
            "true_objective": float(new_nn_result["true_obj"]),
            "runtime_seconds": float(new_nn_result["runtime_seconds"]),
            "iterations": NN_STEPS,
            "composite_queries": np.nan,
            "history_or_result_path": new_nn_result["history_path"],
        },
    ]
).set_index("method")

if len(comparison) != 4:
    raise AssertionError(f"Expected four comparison rows, got {len(comparison)}.")
if not np.isfinite(comparison["true_objective"].to_numpy(dtype=float)).all():
    raise ValueError("All four high-fidelity objectives must be finite.")

hour_columns = [f"hour_{hour:02d}" for hour in range(T)]
solution_frames = {
    "Original NN": pd.DataFrame(
        original_nn_prices, index=SCENARIOS, columns=hour_columns
    ),
    "Trust region": pd.DataFrame(
        tr_prices, index=SCENARIOS, columns=hour_columns
    ),
    "NN: original + TR samples": pd.DataFrame(
        tr_nn_prices, index=SCENARIOS, columns=hour_columns
    ),
    "NN: original + equal global random samples": pd.DataFrame(
        new_nn_prices, index=SCENARIOS, columns=hour_columns
    ),
}
solutions = pd.concat(solution_frames, names=["method", "scenario"])
if solutions.shape != (4 * len(SCENARIOS), T):
    raise AssertionError(f"Unexpected solution table shape: {solutions.shape}.")

output_timestamp = time.strftime("%Y%m%d-%H%M%S")
summary_path = RESULTS_DIR / f"retraining_ablation_summary_{output_timestamp}.csv"
solutions_path = RESULTS_DIR / f"retraining_ablation_solutions_{output_timestamp}.csv"
comparison.reset_index().to_csv(summary_path, index=False)
solutions.to_csv(solutions_path)

display(comparison)
display(sample_count_table)
display(solutions)
print("Saved objective summary to:", summary_path)
print("Saved four solution matrices to:", solutions_path)

,true_objective,runtime_seconds,iterations,composite_queries,history_or_result_path
method,,,,,
Original NN,-98.480666,2223.791465,10000,NaN,/Users/liqi/Desktop/Codes/Surrogated-assisted ...
Trust region,-99.595549,11703.492167,24,1464.0,/Users/liqi/Desktop/Codes/Surrogated-assisted ...
NN: original + TR samples,-91.212067,2179.042543,10000,NaN,/Users/liqi/Desktop/Codes/Surrogated-assisted ...
NN: original + equal global random samples,-96.196163,2187.003335,10000,NaN,/Users/liqi/Desktop/Codes/Surrogated-assisted ...

,original_samples,trust_region_samples,new_random_samples,tr_combined_samples,new_combined_samples
scenario,,,,,
SB1,10000,1392,1392,11392,11392
SB2,10000,1342,1342,11342,11342
BG1,10000,1097,1097,11097,11097
BG2,10000,1064,1064,11064,11064
IP1,10000,1309,1309,11309,11309

                                                      hour_00   hour_01  \
method                                     scenario
Original NN                                SB1       0.970181  0.972706
                                           SB2       0.984327  1.489236
                                           BG1       1.499816  1.499887
                                           BG2       1.499647  1.499705
                                           IP1       1.496455  1.492518
Trust region                               SB1       1.000002  0.991217
                                           SB2       0.998743  1.457483
                                           BG1       1.499985  1.499985
                                           BG2       1.499987  1.499985
                                           IP1       1.488347  1.478651
NN: original + TR samples                  SB1       1.499712  1.215124
                                           SB2       1.087324  1.011228
                                           BG1       1.499889  1.499525
                                           BG2       1.499655  1.499598
                                           IP1       1.477153  1.348952
NN: original + equal global random samples SB1       1.499040  0.974682
                                           SB2       0.978410  1.168926
                                           BG1       1.499913  1.499880
                                           BG2       1.499779  1.499739
                                           IP1       1.492821  1.495248

                                                      hour_02   hour_03  \
method                                     scenario
Original NN                                SB1       0.975164  1.000694
                                           SB2       0.971531  0.980285
                                           BG1       1.499895  1.499872
                                           BG2       1.499627  1.499876
                                           IP1       1.494619  1.495886
Trust region                               SB1       1.000069  0.999314
                                           SB2       0.999609  1.000127
                                           BG1       1.499986  1.499985
                                           BG2       1.499987  1.499985
                                           IP1       1.495236  1.488084
NN: original + TR samples                  SB1       1.316121  1.388250
                                           SB2       0.993166  0.986937
                                           BG1       1.499817  1.499912
                                           BG2       1.499785  1.499897
                                           IP1       1.494497  1.492429
NN: original + equal global random samples SB1       1.420878  1.024053
                                           SB2       1.184377  0.975395
                                           BG1       1.499895  1.499868
                                           BG2       1.499837  1.499943
                                           IP1       1.493362  1.493652

                                                      hour_04   hour_05  \
method                                     scenario
Original NN                                SB1       0.959616  0.969702
                                           SB2       0.946286  0.950465
                                           BG1       1.499943  1.499931
                                           BG2       1.499915  1.499792
                                           IP1       1.491641  1.457786
Trust region                               SB1       0.998336  0.997233
                                           SB2       0.999625  0.999985
                                           BG1       1.499984  1.499985
                                           BG2       1.499987  1.499987
                                           IP1       1.489248  1.480766
NN: original + TR samples                  SB1       1.278881  1.499802
                                           SB2       1.028826  1.254102
                                           BG1       1.499944  1.499950
                                           BG2       1.499867  1.499874
                                           IP1       1.338661  1.457190
NN: original + equal global random samples SB1       0.980017  0.945989
                                           SB2       0.939934  1.498518
                                           BG1       1.499931  1.499922
                                           BG2       1.499916  1.499869
                                           IP1       1.495118  1.441085

                                                      hour_06   hour_07  \
method                                     scenario
Original NN                                SB1       1.160907  1.497205
                                           SB2       0.998462  0.976595
                                           BG1       1.499945  1.499928
                                           BG2       1.499918  1.499930
                                           IP1       1.486227  1.497947
Trust region                               SB1       1.157387  1.485886
                                           SB2       0.998369  0.998287
                                           BG1       1.499984  1.499988
                                           BG2       1.499983  1.499987
                                           IP1       1.492406  1.486847
NN: original + TR samples                  SB1       1.093277  1.119854
                                           SB2       1.354707  1.043538
                                           BG1       1.499933  1.499934
                                           BG2       1.499931  1.499922
                                           IP1       1.459731  1.495704
NN: original + equal global random samples SB1       0.970615  1.499583
                                           SB2       0.993058  1.019875
                                           BG1       1.499927  1.499445
                                           BG2       1.499954  1.499945
                                           IP1       1.495559  1.492922

                                                      hour_08   hour_09  ...  \
method                                     scenario                      ...
Original NN                                SB1       1.497323  0.998421  ...
                                           SB2       1.498717  1.498230  ...
                                           BG1       1.499881  1.499913  ...
                                           BG2       1.499858  1.499912  ...
                                           IP1       1.498367  1.497680  ...
Trust region                               SB1       1.491757  0.999704  ...
                                           SB2       1.498959  1.498097  ...
                                           BG1       1.499987  1.499985  ...
                                           BG2       1.499985  1.499984  ...
                                           IP1       1.485163  1.494086  ...
NN: original + TR samples                  SB1       1.147705  1.201166  ...
                                           SB2       1.498873  1.063052  ...
                                           BG1       1.499903  1.499915  ...
                                           BG2       1.499887  1.499917  ...
                                           IP1       1.188569  1.458742  ...
NN: original + equal global random samples SB1       1.499140  0.993667  ...
                                           SB2       1.498683  0.996357  ...
                                           BG1       1.499901  1.499925  ...
                                           BG2       1.499905  1.499929  ...
                                           IP1       1.490366  1.499402  ...

                                                      hour_14   hour_15  \
method                                     scenario
Original NN                                SB1       1.047077  1.499775
                                           SB2       1.016355  1.498472
                                           BG1       1.499950  1.499931
                                           BG2       1.499942  1.499920
                                           IP1       1.498705  1.498223
Trust region                               SB1       1.014625  1.478245
                                           SB2       1.001994  1.493639
                                           BG1       1.499989  1.499984
                                           BG2       1.499983  1.499986
                                           IP1       1.499677  1.491651
NN: original + TR samples                  SB1       1.067100  1.498885
                                           SB2       1.499727  1.020694
                                           BG1       1.499925  1.499930
                                           BG2       1.499926  1.499919
                                           IP1       1.499210  1.499355
NN: original + equal global random samples SB1       1.498769  1.499639
                                           SB2       1.042400  1.498998
                                           BG1       1.499936  1.499938
                                           BG2       1.499903  1.499924
                                           IP1       1.498695  1.499676

                                                      hour_16   hour_17  \
method                                     scenario
Original NN                                SB1       1.496677  1.499511
                                           SB2       1.497773  1.498430
                                           BG1       1.499941  1.499935
                                           BG2       1.499952  1.499877
                                           IP1       1.498699  1.496387
Trust region                               SB1       1.495911  1.494805
                                           SB2       1.499862  1.499607
                                           BG1       1.499989  1.499983
                                           BG2       1.499986  1.499987
                                           IP1       1.497985  1.485793
NN: original + TR samples                  SB1       1.185577  1.132676
                                           SB2       1.162010  1.013519
                                           BG1       1.499939  1.499939
                                           BG2       1.499931  1.499908
                                           IP1       1.499719  1.464896
NN: original + equal global random samples SB1       0.978189  1.499426
                                           SB2       1.146923  1.498288
                                           BG1       1.499945  1.499938
                                           BG2       1.499943  1.499902
                                           IP1       1.499328  1.497983

                                                      hour_18   hour_19  \
method                                     scenario
Original NN                                SB1       1.337253  1.495676
                                           SB2       1.498577  1.499142
                                           BG1       1.499918  1.499891
                                           BG2       1.499927  1.499919
                                           IP1       1.490192  1.497343
Trust region                               SB1       1.409586  1.499851
                                           SB2       1.499984  1.499971
                                           BG1       1.499985  1.499987
                                           BG2       1.499987  1.499987
                                           IP1       1.484978  1.498614
NN: original + TR samples                  SB1       0.865979  1.194052
                                           SB2       1.054438  1.499545
                                           BG1       1.499883  1.499902
                                           BG2       1.499928  1.499950
                                           IP1       1.372045  1.381463
NN: original + equal global random samples SB1       1.499055  1.028125
                                           SB2       1.499127  1.499316
                                           BG1       1.499807  1.499873
                                           BG2       1.499901  1.499928
                                           IP1       1.496094  1.496430

                                                      hour_20   hour_21  \
method                                     scenario
Original NN                                SB1       1.489284  1.496565
                                           SB2       1.497796  1.451597
                                           BG1       1.499909  1.499468
                                           BG2       1.499869  1.499671
                                           IP1       1.496753  1.495072
Trust region                               SB1       1.499407  1.483297
                                           SB2       1.497886  1.495479
                                           BG1       1.499987  1.499985
                                           BG2       1.499986  1.499987
                                           IP1       1.497015  1.486102
NN: original + TR samples                  SB1       1.074966  1.129296
                                           SB2       1.103153  1.046156
                                           BG1       1.499906  1.499806
                                           BG2       1.499828  1.499848
                                           IP1       1.420791  1.493411
NN: original + equal global random samples SB1       1.499548  1.499745
                                           SB2       1.497206  1.259356
                                           BG1       1.499933  1.371639
                                           BG2       1.499717  1.434022
                                           IP1       1.496643  1.496894

                                                      hour_22   hour_23
method                                     scenario
Original NN                                SB1       1.093230  0.966810
                                           SB2       1.440844  1.184781
                                           BG1       1.499928  1.499742
                                           BG2       1.499878  1.499435
                                           IP1       1.498292  1.497317
Trust region                               SB1       1.073991  1.000001
                                           SB2       1.448008  1.184515
                                           BG1       1.499967  1.499122
                                           BG2       1.499987  1.499982
                                           IP1       1.499975  1.488153
NN: original + TR samples                  SB1       1.498811  1.499678
                                           SB2       1.498815  1.080921
                                           BG1       1.499857  1.499839
                                           BG2       1.499756  1.491221
                                           IP1       1.497947  1.390379
NN: original + equal global random samples SB1       1.499683  1.284353
                                           SB2       1.499319  1.197870
                                           BG1       1.499891  1.499844
                                           BG2       1.499828  1.499622
                                           IP1       1.496552  1.496213

[20 rows x 24 columns]

Saved objective summary to: /Users/liqi/Desktop/Codes/Surrogated-assisted Stackelnerg Game/results/retraining_ablation_summary_20260919-183137.csv
Saved four solution matrices to: /Users/liqi/Desktop/Codes/Surrogated-assisted Stackelnerg Game/results/retraining_ablation_solutions_20260919-183137.csv