# Ablation study: trust-region samples vs. random samples

This notebook tests whether the improvement from retraining the neural surrogate comes from trust-region-localized samples or simply from adding the same number of high-fidelity samples.

The three experiment groups are:

1. the saved trust-region result;
2. original training data + trust-region samples;
3. original training data + the same number of newly generated global random samples.

In [1]:
import json
import time
from pathlib import Path

import numpy as np
import pandas as pd
import pandapower.networks as pn

import follower_solver
from L2Otraining import TrainingConfig, train
from stackelberg.followers.bg import create_cigre_residential_network
from stackelberg.network import create_case33bw_20kv
from stackelberg.nn_solver import NNSolverExperimentConfig, run_nn_solver_experiment
from stackelberg.randomness import make_rng, set_global_seed

PROJECT_ROOT = Path.cwd().resolve()
DATA_DIR = PROJECT_ROOT / "data"
MODEL_DIR = PROJECT_ROOT / "NNmodel"
RESULTS_DIR = PROJECT_ROOT / "results"

if not (PROJECT_ROOT / "L2Otraining.py").is_file():
    raise RuntimeError("Run this notebook with the project root as the working directory.")

DATA_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

T = 24
SEED = 42
upper_net = create_case33bw_20kv()
scenarios = ["SB", "SB", "BG", "BG", "IP"]
lower_nets = [
    pn.create_cigre_network_lv(),
    pn.create_cigre_network_lv(),
    create_cigre_residential_network(),
    create_cigre_residential_network(),
    pn.create_cigre_network_lv(),
]
mg_buses = [17, 32, 15, 21, 1]
unique_scenarios = list(dict.fromkeys(scenarios))
scenario_networks = {}
for scenario, network in zip(scenarios, lower_nets):
    scenario_networks.setdefault(scenario, network)

# Keep these enabled for the complete automated ablation run. Completed random
# datasets are detected and reused, so rerunning the notebook is safe.
RETRAIN_TR_MODELS = True
RUN_TR_NN_SOLVER = True
GENERATE_NEW_SAMPLES = True
RETRAIN_NEW_MODELS = True
RUN_NEW_NN_SOLVER = True

TRAINING_EPOCHS = 500
NN_STEPS = 5000
NN_LEARNING_RATE = 1e-2
NN_SAVE_EVERY = 200
NEW_DATA_SEEDS = {"SB": 4201, "BG": 4202, "IP": 4203}
NEW_DATA_CHECKPOINT_INTERVAL = 100

## 1. Load the saved trust-region result

The filename supplied for this experiment contains `trust_region` (not `turst_region`). The history CSV gives the iteration-level objective trajectory, while the JSON contains the final price vector and full saved history.

In [2]:
TR_RUN_ID = "20260828-045534"
TR_HISTORY_PATH = RESULTS_DIR / f"trust_region_history_{TR_RUN_ID}.csv"
TR_RESULT_PATH = RESULTS_DIR / f"trust_region_result_{TR_RUN_ID}.json"

for required_path in (TR_HISTORY_PATH, TR_RESULT_PATH):
    if not required_path.is_file():
        raise FileNotFoundError(required_path)

tr_history = pd.read_csv(TR_HISTORY_PATH).sort_values("k").reset_index(drop=True)
with TR_RESULT_PATH.open("r", encoding="utf-8") as file:
    tr_saved_result = json.load(file)

if tr_history.empty:
    raise ValueError(f"Trust-region history is empty: {TR_HISTORY_PATH}")

tr_last = tr_history.iloc[-1]
tr_x_opt = np.asarray(tr_saved_result["x_opt"], dtype=float).reshape(len(scenarios), T)
tr_summary = pd.Series(
    {
        "run_id": TR_RUN_ID,
        "converged": bool(tr_saved_result["converged"]),
        "iterations": int(tr_saved_result["n_iter"]),
        "final_true_objective": float(tr_last["F_current"]),
        "final_candidate_objective": float(tr_last["F_candidate"]),
        "final_radius": float(tr_last["R"]),
        "accepted_steps": int(tr_history["decision"].astype(str).str.startswith("accept").sum()),
        "rejected_steps": int((tr_history["decision"] == "reject").sum()),
    },
    name="trust_region",
)

display(tr_summary.to_frame("value"))
display(tr_history.tail())
display(pd.DataFrame(tr_x_opt, index=scenarios))

                                     value
run_id                     20260828-045534
converged                             True
iterations                              43
final_true_objective            -101.29897
final_candidate_objective      -101.265342
final_radius                      0.000073
accepted_steps                          14
rejected_steps                          29

,k,F_current,F_candidate,F_tilde_current,F_tilde_candidate,rho,decision,R,n_residuals,rbf_condition_numbers,max_rbf_condition,geometry_resample_attempts
38,38,-101.29897,-101.212983,-101.298964,-101.291247,-inf,reject,0.000306,14,"[136080.759267719, 152033.0393250161, 25413.04...",178589.546750,0
39,39,-101.29897,-101.236453,-101.298964,-101.298955,-inf,reject,0.000214,14,"[147414.59706066543, 137801.71842968994, 26432...",171133.230086,0
40,40,-101.29897,-101.230113,-101.298964,-101.276129,-inf,reject,0.000150,14,"[146082.44069825005, 139299.0839068988, 25273....",172392.403402,0
41,41,-101.29897,-101.262336,-101.298964,-101.272474,-inf,reject,0.000105,14,"[139193.14750776193, 169739.40240783326, 25830...",180162.583261,0
42,42,-101.29897,-101.265342,-101.298964,-101.250425,-inf,reject,0.000073,14,"[133812.0555472771, 146218.9510779727, 28141.9...",182475.276487,0

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
SB,1.045048,1.091423,1.110336,1.051721,1.108366,1.024407,1.321957,1.034646,1.000332,1.000921,...,1.063006,1.034797,1.499817,1.499958,1.499987,1.499773,1.499988,0.985109,1.125533,1.031857
SB,1.062976,1.127831,1.466499,1.056383,1.039007,1.344635,1.052466,1.057504,0.994752,1.003916,...,1.087294,1.064135,1.494790,1.486213,1.499984,1.499986,1.487902,1.499974,1.398838,1.045117
BG,1.499983,1.499985,1.499985,1.499985,1.499984,1.499985,1.499986,1.499985,1.499982,1.499987,...,1.499986,1.499983,1.499984,1.499983,1.499984,1.499983,1.499985,1.499986,1.499985,1.499985
BG,1.499983,1.499987,1.499985,1.499986,1.499987,1.499987,1.499986,1.499987,1.499985,1.499985,...,1.499985,1.499985,1.499985,1.499987,1.499987,1.499985,1.499986,1.499986,1.499986,1.499987
IP,1.481462,1.481608,1.487102,1.486122,1.482103,1.455926,1.499032,1.484030,1.473870,1.496045,...,1.496380,1.499111,1.499243,1.488322,1.480456,1.493546,1.498827,1.497995,1.499939,1.482495

In [3]:
def load_aligned_arrays(x_path, y_path, *, expected_width=T):
    """Load and validate one aligned X/Y sample pair."""
    x_data = np.load(x_path)
    y_data = np.load(y_path)
    if x_data.ndim != 2 or y_data.ndim != 2:
        raise ValueError(f"Expected 2-D arrays, got X{x_data.shape} and Y{y_data.shape}.")
    if x_data.shape != y_data.shape:
        raise ValueError(f"X/Y shape mismatch: X{x_data.shape} and Y{y_data.shape}.")
    if x_data.shape[1] != expected_width:
        raise ValueError(f"Expected width {expected_width}, got {x_data.shape[1]}.")
    if not np.isfinite(x_data).all() or not np.isfinite(y_data).all():
        raise ValueError(f"Non-finite values found in {x_path.name} or {y_path.name}.")
    return x_data, y_data


tr_sample_counts = {}
sample_rows = []
for scenario in unique_scenarios:
    original_x, original_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy", DATA_DIR / f"Y_{scenario}.npy"
    )
    tr_x, tr_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_tr.npy", DATA_DIR / f"Y_{scenario}_tr.npy"
    )
    tr_sample_counts[scenario] = len(tr_x)
    sample_rows.append(
        {
            "scenario": scenario,
            "original_samples": len(original_x),
            "trust_region_samples": len(tr_x),
            "combined_samples": len(original_x) + len(tr_x),
        }
    )

sample_count_table = pd.DataFrame(sample_rows).set_index("scenario")
display(sample_count_table)

          original_samples  trust_region_samples  combined_samples
scenario
SB                   10000                  5190             15190
BG                   10000                  5176             15176
IP                   10000                  2595             12595

## 2. Retrain on original + trust-region samples

For each unique scenario, concatenate the original and `_tr` arrays and train a fresh model. `TrainingConfig` retains the original architecture and optimizer settings. Tagged checkpoints ensure that the original models are not overwritten.

In [4]:
tr_training_results = {}
if RETRAIN_TR_MODELS:
    for scenario in unique_scenarios:
        print(f"\nTraining {scenario} on original + trust-region samples")
        tr_training_results[scenario] = train(
            scenario,
            config=TrainingConfig(
                scenario=scenario,
                hidden_dim=128,
                residual_blocks=3,
                batch_size=64,
                learning_rate=1e-3,
                epochs=TRAINING_EPOCHS,
                validation_fraction=0.2,
                seed=SEED,
            ),
            data_tag="tr",
            model_tag="tr",
            include_original=True,
        )
else:
    print("Skipped trust-region model retraining.")

if tr_training_results:
    display(pd.DataFrame(tr_training_results).T.rename_axis("scenario"))

Training SB on original + trust-region samples

SB: concatenated original 10000 + tr 5190 samples -> 15190

SB epoch   10/500: train=0.036368, validation=0.037152

SB epoch   20/500: train=0.026342, validation=0.027092

SB epoch   30/500: train=0.021046, validation=0.021565

SB epoch   40/500: train=0.018553, validation=0.018995

SB epoch   50/500: train=0.020172, validation=0.020293

SB epoch   60/500: train=0.021868, validation=0.022162

SB epoch   70/500: train=0.014691, validation=0.014966

SB epoch   80/500: train=0.018978, validation=0.019346

SB epoch   90/500: train=0.018140, validation=0.018347

SB epoch  100/500: train=0.013485, validation=0.013855

SB epoch  110/500: train=0.008956, validation=0.009312

SB epoch  120/500: train=0.011561, validation=0.011919

SB epoch  130/500: train=0.011723, validation=0.012019

SB epoch  140/500: train=0.017700, validation=0.017934

SB epoch  150/500: train=0.007281, validation=0.007606

SB epoch  160/500: train=0.008359, validation=0.008625

SB epoch  170/500: train=0.006128, validation=0.006490

SB epoch  180/500: train=0.009954, validation=0.010236

SB epoch  190/500: train=0.003325, validation=0.003658

SB epoch  200/500: train=0.006856, validation=0.007129

SB epoch  210/500: train=0.003346, validation=0.003652

SB epoch  220/500: train=0.004101, validation=0.004390

SB epoch  230/500: train=0.003114, validation=0.003415

SB epoch  240/500: train=0.002708, validation=0.002992

SB epoch  250/500: train=0.002660, validation=0.002984

SB epoch  260/500: train=0.002362, validation=0.002626

SB epoch  270/500: train=0.002337, validation=0.002651

SB epoch  280/500: train=0.002647, validation=0.002933

SB epoch  290/500: train=0.002087, validation=0.002357

SB epoch  300/500: train=0.002545, validation=0.002843

SB epoch  310/500: train=0.002596, validation=0.002846

SB epoch  320/500: train=0.001729, validation=0.001981

SB epoch  330/500: train=0.001930, validation=0.002195

SB epoch  340/500: train=0.001798, validation=0.002074

SB epoch  350/500: train=0.001724, validation=0.001997

SB epoch  360/500: train=0.001714, validation=0.001983

SB epoch  370/500: train=0.001543, validation=0.001794

SB epoch  380/500: train=0.001768, validation=0.002036

SB epoch  390/500: train=0.001593, validation=0.001863

SB epoch  400/500: train=0.001565, validation=0.001775

SB epoch  410/500: train=0.001186, validation=0.001431

SB epoch  420/500: train=0.001419, validation=0.001649

SB epoch  430/500: train=0.001105, validation=0.001340

SB epoch  440/500: train=0.001183, validation=0.001401

SB epoch  450/500: train=0.001852, validation=0.002082

SB epoch  460/500: train=0.001019, validation=0.001242

SB epoch  470/500: train=0.000967, validation=0.001176

SB epoch  480/500: train=0.001075, validation=0.001281

SB epoch  490/500: train=0.001263, validation=0.001469

SB epoch  500/500: train=0.000917, validation=0.001143

Training BG on original + trust-region samples
BG: concatenated original 10000 + tr 5176 samples -> 15176

BG epoch   10/500: train=0.013068, validation=0.013200

BG epoch   20/500: train=0.007073, validation=0.007122

BG epoch   30/500: train=0.007200, validation=0.007318

BG epoch   40/500: train=0.009085, validation=0.009194

BG epoch   50/500: train=0.006515, validation=0.006565

BG epoch   60/500: train=0.025505, validation=0.025865

BG epoch   70/500: train=0.019222, validation=0.019438

BG epoch   80/500: train=0.009287, validation=0.009427

BG epoch   90/500: train=0.008866, validation=0.008956

BG epoch  100/500: train=0.012939, validation=0.013059

BG epoch  110/500: train=0.009304, validation=0.009422

BG epoch  120/500: train=0.002099, validation=0.002103

BG epoch  130/500: train=0.001914, validation=0.001940

BG epoch  140/500: train=0.001360, validation=0.001337

BG epoch  150/500: train=0.001587, validation=0.001552

BG epoch  160/500: train=0.001043, validation=0.001016

BG epoch  170/500: train=0.000944, validation=0.000931

BG epoch  180/500: train=0.000887, validation=0.000850

BG epoch  190/500: train=0.000591, validation=0.000598

BG epoch  200/500: train=0.000750, validation=0.000739

BG epoch  210/500: train=0.000594, validation=0.000624

BG epoch  220/500: train=0.000694, validation=0.000724

BG epoch  230/500: train=0.002062, validation=0.002075

BG epoch  240/500: train=0.000657, validation=0.000698

BG epoch  250/500: train=0.000520, validation=0.000542

BG epoch  260/500: train=0.000527, validation=0.000565

BG epoch  270/500: train=0.000610, validation=0.000653

BG epoch  280/500: train=0.000502, validation=0.000553

BG epoch  290/500: train=0.000461, validation=0.000522

BG epoch  300/500: train=0.000453, validation=0.000504

BG epoch  310/500: train=0.000498, validation=0.000557

BG epoch  320/500: train=0.000429, validation=0.000478

BG epoch  330/500: train=0.000586, validation=0.000652

BG epoch  340/500: train=0.000397, validation=0.000456

BG epoch  350/500: train=0.000364, validation=0.000411

BG epoch  360/500: train=0.000372, validation=0.000420

BG epoch  370/500: train=0.000348, validation=0.000395

BG epoch  380/500: train=0.000442, validation=0.000483

BG epoch  390/500: train=0.000345, validation=0.000394

BG epoch  400/500: train=0.000379, validation=0.000430

BG epoch  410/500: train=0.000365, validation=0.000423

BG epoch  420/500: train=0.000409, validation=0.000458

BG epoch  430/500: train=0.000364, validation=0.000417

BG epoch  440/500: train=0.000328, validation=0.000385

BG epoch  450/500: train=0.000330, validation=0.000385

BG epoch  460/500: train=0.000304, validation=0.000359

BG epoch  470/500: train=0.000417, validation=0.000477

BG epoch  480/500: train=0.000327, validation=0.000400

BG epoch  490/500: train=0.000301, validation=0.000377

BG epoch  500/500: train=0.000961, validation=0.001077

Training IP on original + trust-region samples
IP: concatenated original 10000 + tr 2595 samples -> 12595

IP epoch   10/500: train=1.772277, validation=1.961366

IP epoch   20/500: train=1.779758, validation=1.978484

IP epoch   30/500: train=1.329223, validation=1.583669

IP epoch   40/500: train=1.618093, validation=1.886653

IP epoch   50/500: train=1.300354, validation=1.604421

IP epoch   60/500: train=1.483350, validation=1.827450

IP epoch   70/500: train=1.310221, validation=1.662116

IP epoch   80/500: train=1.342337, validation=1.743484

IP epoch   90/500: train=0.970876, validation=1.397310

IP epoch  100/500: train=0.942923, validation=1.402605

IP epoch  110/500: train=0.846308, validation=1.305629

IP epoch  120/500: train=0.730820, validation=1.224986

IP epoch  130/500: train=0.963953, validation=1.436653

IP epoch  140/500: train=0.794265, validation=1.309598

IP epoch  150/500: train=0.632958, validation=1.156048

IP epoch  160/500: train=0.639929, validation=1.178558

IP epoch  170/500: train=0.680345, validation=1.230668

IP epoch  180/500: train=0.569384, validation=1.132713

IP epoch  190/500: train=0.714008, validation=1.270685

IP epoch  200/500: train=0.613928, validation=1.179894

IP epoch  210/500: train=0.654224, validation=1.241448

IP epoch  220/500: train=0.516109, validation=1.111105

IP epoch  230/500: train=0.522217, validation=1.132300

IP epoch  240/500: train=1.052533, validation=1.660491

IP epoch  250/500: train=0.705221, validation=1.324065

IP epoch  260/500: train=0.601260, validation=1.225195

IP epoch  270/500: train=0.649649, validation=1.272324

IP epoch  280/500: train=0.605786, validation=1.238641

IP epoch  290/500: train=0.562824, validation=1.204665

IP epoch  300/500: train=0.656990, validation=1.284983

IP epoch  310/500: train=0.775362, validation=1.411141

IP epoch  320/500: train=0.535345, validation=1.169891

IP epoch  330/500: train=0.463032, validation=1.105907

IP epoch  340/500: train=0.453434, validation=1.104272

IP epoch  350/500: train=0.635116, validation=1.282323

IP epoch  360/500: train=0.475741, validation=1.135733

IP epoch  370/500: train=0.509268, validation=1.167218

IP epoch  380/500: train=0.483704, validation=1.153301

IP epoch  390/500: train=0.483918, validation=1.142433

IP epoch  400/500: train=0.474994, validation=1.146690

IP epoch  410/500: train=0.453408, validation=1.133953

IP epoch  420/500: train=0.486013, validation=1.160902

IP epoch  430/500: train=0.411170, validation=1.079942

IP epoch  440/500: train=0.502034, validation=1.189959

IP epoch  450/500: train=0.519815, validation=1.207891

IP epoch  460/500: train=0.537809, validation=1.222371

IP epoch  470/500: train=0.442306, validation=1.133513

IP epoch  480/500: train=0.557917, validation=1.243872

IP epoch  490/500: train=0.430959, validation=1.135264

IP epoch  500/500: train=0.546139, validation=1.240004

          train_mse  validation_mse
scenario
SB         0.000917        0.001143
BG         0.000961        0.001077
IP         0.546139        1.240004

In [5]:
tr_nn_result = None
if RUN_TR_NN_SOLVER:
    tr_nn_config = NNSolverExperimentConfig(
        upper_net=upper_net,
        lower_nets=lower_nets,
        mg_buses=mg_buses,
        scenarios=scenarios,
        T=T,
        seed=SEED,
        device="cpu",
        steps=NN_STEPS,
        lr=NN_LEARNING_RATE,
        save_every=NN_SAVE_EVERY,
        history_path=str(RESULTS_DIR / "NN_solver_tr_ablation_history.csv"),
        evaluate_true=True,
        save_results=True,
        model_tag="tr",
    )
    tr_nn_result = run_nn_solver_experiment(tr_nn_config)
    print("TR-retrained NN history:", tr_nn_result["history_path"])
    print("TR-retrained NN true objective:", tr_nn_result["true_obj"])
    print("TR-retrained NN runtime (s):", tr_nn_result["runtime_seconds"])
else:
    print("Skipped the NN solver with trust-region-retrained models.")

Set parameter Username

Set parameter LicenseID to value 2711611

Academic license - for non-commercial use only - expires 2026-09-22

[0] loss=5740.4990, obj=-123.2677, eq=5.8566, soc=0.0647, bound=0.0646, true_loss=1.5415

[200] loss=139.3161, obj=-67.8390, eq=0.2032, soc=0.0367, bound=0.0250, true_loss=-2.2243

[400] loss=31.9049, obj=-52.5675, eq=0.0828, soc=0.0157, bound=0.0110, true_loss=-9.4498

[600] loss=-8.8772, obj=-43.5354, eq=0.0339, soc=0.0073, bound=0.0029, true_loss=-14.1328

[800] loss=-24.9417, obj=-41.5820, eq=0.0163, soc=0.0037, bound=0.0009, true_loss=-20.9268

[1000] loss=-34.2338, obj=-45.8819, eq=0.0114, soc=0.0026, bound=0.0004, true_loss=-27.5142

[1200] loss=-43.0392, obj=-52.9776, eq=0.0097, soc=0.0023, bound=0.0003, true_loss=-33.9883

[1400] loss=-51.4918, obj=-59.7242, eq=0.0080, soc=0.0020, bound=0.0003, true_loss=-41.3679

[1600] loss=-57.9886, obj=-65.7176, eq=0.0076, soc=0.0018, bound=0.0002, true_loss=-47.5415

[1800] loss=-64.8330, obj=-71.9793, eq=0.0070, soc=0.0016, bound=0.0002, true_loss=-52.7082

[2000] loss=-71.5075, obj=-78.2124, eq=0.0065, soc=0.0016, bound=0.0002, true_loss=-58.3564

[2200] loss=-77.2029, obj=-83.6138, eq=0.0063, soc=0.0015, bound=0.0002, true_loss=-63.4841

[2400] loss=-80.4778, obj=-88.1367, eq=0.0075, soc=0.0016, bound=0.0002, true_loss=-67.6027

[2600] loss=-84.6581, obj=-91.7681, eq=0.0070, soc=0.0015, bound=0.0002, true_loss=-72.2553

[2800] loss=-88.8274, obj=-95.1763, eq=0.0062, soc=0.0015, bound=0.0002, true_loss=-75.5009

[3000] loss=-90.8546, obj=-97.6193, eq=0.0066, soc=0.0015, bound=0.0002, true_loss=-77.9597

[3200] loss=-93.2170, obj=-99.8369, eq=0.0065, soc=0.0015, bound=0.0002, true_loss=-80.3119

[3400] loss=-94.9668, obj=-101.8952, eq=0.0068, soc=0.0015, bound=0.0002, true_loss=-82.1883

[3600] loss=-95.8793, obj=-103.6054, eq=0.0076, soc=0.0016, bound=0.0002, true_loss=-84.1399

[3800] loss=-98.7919, obj=-105.2158, eq=0.0063, soc=0.0015, bound=0.0002, true_loss=-85.7870

[4000] loss=-99.4062, obj=-106.6862, eq=0.0071, soc=0.0016, bound=0.0002, true_loss=-87.4318

[4200] loss=-101.4153, obj=-107.9330, eq=0.0064, soc=0.0015, bound=0.0002, true_loss=-88.7156

[4400] loss=-102.2712, obj=-109.3865, eq=0.0070, soc=0.0016, bound=0.0002, true_loss=-90.1581

[4600] loss=-103.5920, obj=-110.0894, eq=0.0063, soc=0.0015, bound=0.0002, true_loss=-91.0252

[4800] loss=-103.9908, obj=-110.7416, eq=0.0066, soc=0.0016, bound=0.0002, true_loss=-91.6942

TR-retrained NN history: /Users/liqi/Library/CloudStorage/OneDrive-TheUniversityofHongKong-Connect/Stackelberg Game/Surrogated-assisted Stackelnerg Game/results/NN_solver_tr_ablation_history_20260829-114932.csv
TR-retrained NN true objective: -92.30679830578671
TR-retrained NN runtime (s): 1279.3124418258667

## 3. Retrain on original + equally many global random samples

This control group uses exactly as many new samples as the trust-region group for each scenario, but draws prices globally from $[0, 1.5]^{24}$. The generated files use the `_new` tag and never overwrite the original data.

Generation is checkpointed and resumable. For IP, the date and MIP settings match the production call in `data_generation.py`.

In [6]:
def atomic_save_npy(path, array):
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    with temporary_path.open("wb") as file:
        np.save(file, array)
    temporary_path.replace(path)


def atomic_save_json(path, payload):
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    temporary_path.write_text(json.dumps(payload), encoding="utf-8")
    temporary_path.replace(path)


def generate_tagged_random_samples(
    scenario,
    n_samples,
    network,
    *,
    seed,
    checkpoint_interval=100,
    max_consecutive_failures=20,
):
    """Generate or resume a deterministic `_new` high-fidelity dataset."""
    x_path = DATA_DIR / f"X_{scenario}_new.npy"
    y_path = DATA_DIR / f"Y_{scenario}_new.npy"
    state_path = DATA_DIR / f"generation_{scenario}_new_state.json"

    if x_path.exists() != y_path.exists():
        raise RuntimeError(f"Only one of {x_path.name} and {y_path.name} exists.")

    if x_path.exists():
        saved_x, saved_y = load_aligned_arrays(x_path, y_path)
        completed = len(saved_x)
        if completed > n_samples:
            raise ValueError(
                f"{scenario} already has {completed} new samples; expected at most {n_samples}."
            )
        if completed == n_samples:
            print(f"{scenario}: reusing complete random dataset ({completed} samples).")
            return saved_x, saved_y
        if not state_path.is_file():
            raise RuntimeError(
                f"Cannot safely resume partial {scenario} data without {state_path.name}."
            )
    else:
        saved_x = np.empty((0, T), dtype=float)
        saved_y = np.empty((0, T), dtype=float)
        completed = 0

    set_global_seed(seed)
    rng = make_rng(seed)
    if completed:
        state = json.loads(state_path.read_text(encoding="utf-8"))
        if int(state["completed"]) != completed:
            raise RuntimeError(
                f"{scenario} checkpoint state ({state['completed']}) does not match arrays ({completed})."
            )
        rng.bit_generator.state = state["rng_state"]

    solver_kwargs = {"failure_mode": "none", "include_metadata": True}
    if scenario == "IP":
        solver_kwargs.update(date="2023-07-15", time_limit=30.0, mip_gap=1e-3)
    lower_solver = follower_solver.build_solver(
        scenario,
        T=T,
        net=network,
        **solver_kwargs,
    )

    x_data = np.empty((n_samples, T), dtype=float)
    y_data = np.empty((n_samples, T), dtype=float)
    x_data[:completed] = saved_x
    y_data[:completed] = saved_y
    attempts = completed
    failures = 0
    consecutive_failures = 0
    checkpoint_start = time.time()

    print(f"{scenario}: generating samples {completed + 1}..{n_samples} (seed={seed}).")
    while completed < n_samples:
        attempts += 1
        price = rng.uniform(0.0, 1.5, size=T)
        result = lower_solver.lower_solve(price)
        if result is None:
            failures += 1
            consecutive_failures += 1
            print(
                f"{scenario}: skipped failed attempt {attempts}; "
                f"collected {completed}/{n_samples}."
            )
            if consecutive_failures >= max_consecutive_failures:
                raise RuntimeError(
                    f"{scenario}: stopped after {consecutive_failures} consecutive failures."
                )
            continue

        consecutive_failures = 0
        response = np.asarray(result["p_mg"], dtype=float).reshape(T)
        if not np.isfinite(response).all():
            raise ValueError(f"{scenario}: follower returned a non-finite response.")
        x_data[completed] = price
        y_data[completed] = response
        completed += 1

        if completed % checkpoint_interval == 0 or completed == n_samples:
            atomic_save_npy(x_path, x_data[:completed])
            atomic_save_npy(y_path, y_data[:completed])
            atomic_save_json(
                state_path,
                {
                    "scenario": scenario,
                    "seed": seed,
                    "target_samples": n_samples,
                    "completed": completed,
                    "attempts": attempts,
                    "failures": failures,
                    "rng_state": rng.bit_generator.state,
                },
            )
            elapsed = time.time() - checkpoint_start
            print(
                f"{scenario}: saved {completed}/{n_samples} samples "
                f"({failures} failed attempts, {elapsed:.1f} s since last checkpoint)."
            )
            checkpoint_start = time.time()

    return x_data, y_data

In [7]:
new_data = {}
if GENERATE_NEW_SAMPLES:
    for scenario in unique_scenarios:
        new_data[scenario] = generate_tagged_random_samples(
            scenario,
            tr_sample_counts[scenario],
            scenario_networks[scenario],
            seed=NEW_DATA_SEEDS[scenario],
            checkpoint_interval=NEW_DATA_CHECKPOINT_INTERVAL,
        )
else:
    print("Skipped random sample generation; validating existing `_new` arrays.")

new_sample_rows = []
for scenario in unique_scenarios:
    new_x, new_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_new.npy", DATA_DIR / f"Y_{scenario}_new.npy"
    )
    if len(new_x) != tr_sample_counts[scenario]:
        raise ValueError(
            f"{scenario}: expected {tr_sample_counts[scenario]} random samples, got {len(new_x)}."
        )
    original_x = np.load(DATA_DIR / f"X_{scenario}.npy", mmap_mode="r")
    new_sample_rows.append(
        {
            "scenario": scenario,
            "original_samples": len(original_x),
            "new_random_samples": len(new_x),
            "trust_region_samples": tr_sample_counts[scenario],
            "combined_samples": len(original_x) + len(new_x),
        }
    )

new_sample_count_table = pd.DataFrame(new_sample_rows).set_index("scenario")
display(new_sample_count_table)

SB: generating samples 1..5190 (seed=4201).

SB: saved 100/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 200/5190 samples (0 failed attempts, 0.3 s since last checkpoint).

SB: saved 300/5190 samples (0 failed attempts, 0.3 s since last checkpoint).
SB: saved 400/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 500/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 600/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 700/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 800/5190 samples (0 failed attempts, 0.3 s since last checkpoint).
SB: saved 900/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 1000/5190 samples (0 failed attempts, 0.3 s since last checkpoint).
SB: saved 1100/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 1200/5190 samples (0 failed attempts, 0.3 s since last checkpoint).

SB: saved 1300/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 1400/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 1500/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 1600/5190 samples (0 failed attempts, 0.3 s since last checkpoint).
SB: saved 1700/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 1800/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 1900/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 2000/5190 samples (0 failed attempts, 0.1 s since last checkpoint).

SB: saved 2100/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 2200/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 2300/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 2400/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 2500/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 2600/5190 samples (0 failed attempts, 0.1 s since last checkpoint).
SB: saved 2700/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 2800/5190 samples (0 failed attempts, 0.1 s since last checkpoint).
SB: saved 2900/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 3000/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 3100/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 3200/5190 samples (0 failed attempts, 0.1 s since last checkpoint).
SB: saved 3300/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 3400/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 3500/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 3600/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 3700/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 3800/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 3900/5190 samples (0 failed attempts, 0.1 s since last checkpoint).

SB: saved 4000/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 4100/5190 samples (0 failed attempts, 0.1 s since last checkpoint).

SB: saved 4200/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 4300/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 4400/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 4500/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 4600/5190 samples (0 failed attempts, 0.1 s since last checkpoint).
SB: saved 4700/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 4800/5190 samples (0 failed attempts, 0.2 s since last checkpoint).
SB: saved 4900/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 5000/5190 samples (0 failed attempts, 0.1 s since last checkpoint).
SB: saved 5100/5190 samples (0 failed attempts, 0.2 s since last checkpoint).

SB: saved 5190/5190 samples (0 failed attempts, 0.1 s since last checkpoint).

BG: generating samples 1..5176 (seed=4202).

BG: saved 100/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 200/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 300/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 400/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 500/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 600/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 700/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 800/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 900/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 1000/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 1100/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 1200/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 1300/5176 samples (0 failed attempts, 3.0 s since last checkpoint).

BG: saved 1400/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 1500/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 1600/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 1700/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 1800/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 1900/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 2000/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 2100/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 2200/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 2300/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 2400/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 2500/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 2600/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 2700/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 2800/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 2900/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 3000/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 3100/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 3200/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 3300/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 3400/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 3500/5176 samples (0 failed attempts, 2.9 s since last checkpoint).

BG: saved 3600/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 3700/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 3800/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 3900/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 4000/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 4100/5176 samples (0 failed attempts, 2.9 s since last checkpoint).

BG: saved 4200/5176 samples (0 failed attempts, 2.9 s since last checkpoint).

BG: saved 4300/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 4400/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 4500/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 4600/5176 samples (0 failed attempts, 2.9 s since last checkpoint).

BG: saved 4700/5176 samples (0 failed attempts, 2.6 s since last checkpoint).

BG: saved 4800/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 4900/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 5000/5176 samples (0 failed attempts, 2.7 s since last checkpoint).

BG: saved 5100/5176 samples (0 failed attempts, 2.8 s since last checkpoint).

BG: saved 5176/5176 samples (0 failed attempts, 2.1 s since last checkpoint).
IP: generating samples 1..2595 (seed=4203).

IP: saved 100/2595 samples (0 failed attempts, 54.8 s since last checkpoint).

IP: saved 200/2595 samples (0 failed attempts, 54.1 s since last checkpoint).

IP: saved 300/2595 samples (0 failed attempts, 59.2 s since last checkpoint).

IP: saved 400/2595 samples (0 failed attempts, 58.7 s since last checkpoint).

IP: saved 500/2595 samples (0 failed attempts, 58.3 s since last checkpoint).

IP: saved 600/2595 samples (0 failed attempts, 61.1 s since last checkpoint).

IP: saved 700/2595 samples (0 failed attempts, 53.4 s since last checkpoint).

IP: saved 800/2595 samples (0 failed attempts, 54.8 s since last checkpoint).

IP: saved 900/2595 samples (0 failed attempts, 58.0 s since last checkpoint).

IP: saved 1000/2595 samples (0 failed attempts, 60.6 s since last checkpoint).

IP: saved 1100/2595 samples (0 failed attempts, 60.6 s since last checkpoint).

IP: saved 1200/2595 samples (0 failed attempts, 56.4 s since last checkpoint).

IP: saved 1300/2595 samples (0 failed attempts, 60.4 s since last checkpoint).

IP: saved 1400/2595 samples (0 failed attempts, 59.6 s since last checkpoint).

IP: saved 1500/2595 samples (0 failed attempts, 58.5 s since last checkpoint).

IP: saved 1600/2595 samples (0 failed attempts, 55.2 s since last checkpoint).

IP: saved 1700/2595 samples (0 failed attempts, 60.7 s since last checkpoint).

IP: saved 1800/2595 samples (0 failed attempts, 63.1 s since last checkpoint).

IP: saved 1900/2595 samples (0 failed attempts, 55.2 s since last checkpoint).

IP: saved 2000/2595 samples (0 failed attempts, 61.0 s since last checkpoint).

IP: saved 2100/2595 samples (0 failed attempts, 61.4 s since last checkpoint).

IP: saved 2200/2595 samples (0 failed attempts, 53.4 s since last checkpoint).

IP: saved 2300/2595 samples (0 failed attempts, 62.8 s since last checkpoint).

IP: saved 2400/2595 samples (0 failed attempts, 53.7 s since last checkpoint).

IP: saved 2500/2595 samples (0 failed attempts, 60.6 s since last checkpoint).

IP: saved 2595/2595 samples (0 failed attempts, 54.4 s since last checkpoint).

,original_samples,new_random_samples,trust_region_samples,combined_samples
scenario,,,,
SB,10000,5190,5190,15190
BG,10000,5176,5176,15176
IP,10000,2595,2595,12595

In [8]:
new_training_results = {}
if RETRAIN_NEW_MODELS:
    for scenario in unique_scenarios:
        print(f"\nTraining {scenario} on original + equally many global random samples")
        new_training_results[scenario] = train(
            scenario,
            config=TrainingConfig(
                scenario=scenario,
                hidden_dim=128,
                residual_blocks=3,
                batch_size=64,
                learning_rate=1e-3,
                epochs=TRAINING_EPOCHS,
                validation_fraction=0.2,
                seed=SEED,
            ),
            data_tag="new",
            model_tag="new",
            include_original=True,
        )
else:
    print("Skipped random-baseline model retraining.")

if new_training_results:
    display(pd.DataFrame(new_training_results).T.rename_axis("scenario"))

Training SB on original + equally many global random samples
SB: concatenated original 10000 + new 5190 samples -> 15190

SB epoch   10/500: train=0.047711, validation=0.049930

SB epoch   20/500: train=0.034699, validation=0.036942

SB epoch   30/500: train=0.022313, validation=0.023949

SB epoch   40/500: train=0.013448, validation=0.014432

SB epoch   50/500: train=0.009273, validation=0.010062

SB epoch   60/500: train=0.007960, validation=0.008800

SB epoch   70/500: train=0.005781, validation=0.006378

SB epoch   80/500: train=0.004433, validation=0.005005

SB epoch   90/500: train=0.003333, validation=0.003745

SB epoch  100/500: train=0.002791, validation=0.003166

SB epoch  110/500: train=0.002438, validation=0.002828

SB epoch  120/500: train=0.001964, validation=0.002269

SB epoch  130/500: train=0.001757, validation=0.002054

SB epoch  140/500: train=0.001538, validation=0.001785

SB epoch  150/500: train=0.001400, validation=0.001638

SB epoch  160/500: train=0.001544, validation=0.001761

SB epoch  170/500: train=0.001280, validation=0.001466

SB epoch  180/500: train=0.001288, validation=0.001479

SB epoch  190/500: train=0.001091, validation=0.001291

SB epoch  200/500: train=0.001147, validation=0.001282

SB epoch  210/500: train=0.000993, validation=0.001127

SB epoch  220/500: train=0.001022, validation=0.001115

SB epoch  230/500: train=0.001057, validation=0.001132

SB epoch  240/500: train=0.000812, validation=0.000878

SB epoch  250/500: train=0.000698, validation=0.000730

SB epoch  260/500: train=0.000825, validation=0.000815

SB epoch  270/500: train=0.000661, validation=0.000680

SB epoch  280/500: train=0.000860, validation=0.000781

SB epoch  290/500: train=0.000928, validation=0.000846

SB epoch  300/500: train=0.000576, validation=0.000527

SB epoch  310/500: train=0.000620, validation=0.000656

SB epoch  320/500: train=0.000956, validation=0.001023

SB epoch  330/500: train=0.000564, validation=0.000521

SB epoch  340/500: train=0.001023, validation=0.000983

SB epoch  350/500: train=0.000853, validation=0.000939

SB epoch  360/500: train=0.000504, validation=0.000549

SB epoch  370/500: train=0.000658, validation=0.000681

SB epoch  380/500: train=0.001036, validation=0.000999

SB epoch  390/500: train=0.000491, validation=0.000495

SB epoch  400/500: train=0.000525, validation=0.000528

SB epoch  410/500: train=0.000593, validation=0.000589

SB epoch  420/500: train=0.000443, validation=0.000414

SB epoch  430/500: train=0.000877, validation=0.000730

SB epoch  440/500: train=0.000466, validation=0.000509

SB epoch  450/500: train=0.000471, validation=0.000490

SB epoch  460/500: train=0.000367, validation=0.000382

SB epoch  470/500: train=0.000443, validation=0.000412

SB epoch  480/500: train=0.000834, validation=0.000753

SB epoch  490/500: train=0.000502, validation=0.000426

SB epoch  500/500: train=0.000417, validation=0.000409

Training BG on original + equally many global random samples
BG: concatenated original 10000 + new 5176 samples -> 15176

BG epoch   10/500: train=0.016214, validation=0.016681

BG epoch   20/500: train=0.009101, validation=0.009218

BG epoch   30/500: train=0.005874, validation=0.006031

BG epoch   40/500: train=0.003903, validation=0.003994

BG epoch   50/500: train=0.003244, validation=0.003329

BG epoch   60/500: train=0.003189, validation=0.003297

BG epoch   70/500: train=0.002048, validation=0.002119

BG epoch   80/500: train=0.001718, validation=0.001792

BG epoch   90/500: train=0.001438, validation=0.001497

BG epoch  100/500: train=0.001102, validation=0.001151

BG epoch  110/500: train=0.000886, validation=0.000938

BG epoch  120/500: train=0.000792, validation=0.000828

BG epoch  130/500: train=0.000753, validation=0.000794

BG epoch  140/500: train=0.000691, validation=0.000739

BG epoch  150/500: train=0.000647, validation=0.000691

BG epoch  160/500: train=0.000618, validation=0.000659

BG epoch  170/500: train=0.000606, validation=0.000651

BG epoch  180/500: train=0.000576, validation=0.000622

BG epoch  190/500: train=0.000553, validation=0.000601

BG epoch  200/500: train=0.000601, validation=0.000653

BG epoch  210/500: train=0.000551, validation=0.000600

BG epoch  220/500: train=0.000514, validation=0.000563

BG epoch  230/500: train=0.000538, validation=0.000588

BG epoch  240/500: train=0.000506, validation=0.000558

BG epoch  250/500: train=0.000485, validation=0.000535

BG epoch  260/500: train=0.000469, validation=0.000524

BG epoch  270/500: train=0.000473, validation=0.000529

BG epoch  280/500: train=0.000518, validation=0.000577

BG epoch  290/500: train=0.000482, validation=0.000544

BG epoch  300/500: train=0.000452, validation=0.000505

BG epoch  310/500: train=0.000480, validation=0.000536

BG epoch  320/500: train=0.000435, validation=0.000487

BG epoch  330/500: train=0.000433, validation=0.000493

BG epoch  340/500: train=0.000433, validation=0.000502

BG epoch  350/500: train=0.000453, validation=0.000514

BG epoch  360/500: train=0.000392, validation=0.000454

BG epoch  370/500: train=0.000401, validation=0.000463

BG epoch  380/500: train=0.000422, validation=0.000478

BG epoch  390/500: train=0.000379, validation=0.000444

BG epoch  400/500: train=0.000387, validation=0.000444

BG epoch  410/500: train=0.000405, validation=0.000459

BG epoch  420/500: train=0.000389, validation=0.000444

BG epoch  430/500: train=0.000409, validation=0.000464

BG epoch  440/500: train=0.000368, validation=0.000429

BG epoch  450/500: train=0.000355, validation=0.000408

BG epoch  460/500: train=0.000537, validation=0.000589

BG epoch  470/500: train=0.000357, validation=0.000419

BG epoch  480/500: train=0.000416, validation=0.000465

BG epoch  490/500: train=0.000367, validation=0.000428

BG epoch  500/500: train=0.000351, validation=0.000406

Training IP on original + equally many global random samples
IP: concatenated original 10000 + new 2595 samples -> 12595

IP epoch   10/500: train=1.668623, validation=1.955725

IP epoch   20/500: train=1.283053, validation=1.641466

IP epoch   30/500: train=1.096905, validation=1.491111

IP epoch   40/500: train=0.956037, validation=1.386829

IP epoch   50/500: train=0.905563, validation=1.352944

IP epoch   60/500: train=0.832184, validation=1.319345

IP epoch   70/500: train=0.761666, validation=1.273895

IP epoch   80/500: train=0.735237, validation=1.258379

IP epoch   90/500: train=0.698527, validation=1.249205

IP epoch  100/500: train=0.651432, validation=1.236242

IP epoch  110/500: train=0.635780, validation=1.229454

IP epoch  120/500: train=0.617576, validation=1.231732

IP epoch  130/500: train=0.591723, validation=1.216484

IP epoch  140/500: train=0.560829, validation=1.200997

IP epoch  150/500: train=0.560939, validation=1.214008

IP epoch  160/500: train=0.529908, validation=1.186749

IP epoch  170/500: train=0.525835, validation=1.202047

IP epoch  180/500: train=0.514607, validation=1.196325

IP epoch  190/500: train=0.487331, validation=1.173558

IP epoch  200/500: train=0.489621, validation=1.181578

IP epoch  210/500: train=0.468880, validation=1.174823

IP epoch  220/500: train=0.468528, validation=1.185381

IP epoch  230/500: train=0.454368, validation=1.182326

IP epoch  240/500: train=0.463459, validation=1.183063

IP epoch  250/500: train=0.436190, validation=1.171790

IP epoch  260/500: train=0.423430, validation=1.146776

IP epoch  270/500: train=0.419136, validation=1.154335

IP epoch  280/500: train=0.425416, validation=1.167694

IP epoch  290/500: train=0.417607, validation=1.156454

IP epoch  300/500: train=0.422496, validation=1.166880

IP epoch  310/500: train=0.407796, validation=1.166926

IP epoch  320/500: train=0.400465, validation=1.157589

IP epoch  330/500: train=0.399214, validation=1.160670

IP epoch  340/500: train=0.391837, validation=1.149887

IP epoch  350/500: train=0.388722, validation=1.144621

IP epoch  360/500: train=0.387772, validation=1.162693

IP epoch  370/500: train=0.385694, validation=1.152816

IP epoch  380/500: train=0.379338, validation=1.156137

IP epoch  390/500: train=0.368024, validation=1.151615

IP epoch  400/500: train=0.377222, validation=1.158602

IP epoch  410/500: train=0.365247, validation=1.150886

IP epoch  420/500: train=0.363856, validation=1.146292

IP epoch  430/500: train=0.374125, validation=1.164954

IP epoch  440/500: train=0.364716, validation=1.142626

IP epoch  450/500: train=0.357374, validation=1.146322

IP epoch  460/500: train=0.356258, validation=1.148896

IP epoch  470/500: train=0.359227, validation=1.152680

IP epoch  480/500: train=0.354144, validation=1.151201

IP epoch  490/500: train=0.345218, validation=1.144249

IP epoch  500/500: train=0.344501, validation=1.143724

          train_mse  validation_mse
scenario
SB         0.000417        0.000409
BG         0.000351        0.000406
IP         0.344501        1.143724

In [9]:
new_nn_result = None
if RUN_NEW_NN_SOLVER:
    new_nn_config = NNSolverExperimentConfig(
        upper_net=upper_net,
        lower_nets=lower_nets,
        mg_buses=mg_buses,
        scenarios=scenarios,
        T=T,
        seed=SEED,
        device="cpu",
        steps=NN_STEPS,
        lr=NN_LEARNING_RATE,
        save_every=NN_SAVE_EVERY,
        history_path=str(RESULTS_DIR / "NN_solver_new_ablation_history.csv"),
        evaluate_true=True,
        save_results=True,
        model_tag="new",
    )
    new_nn_result = run_nn_solver_experiment(new_nn_config)
    print("Random-retrained NN history:", new_nn_result["history_path"])
    print("Random-retrained NN true objective:", new_nn_result["true_obj"])
    print("Random-retrained NN runtime (s):", new_nn_result["runtime_seconds"])
else:
    print("Skipped the NN solver with random-retrained models.")

[0] loss=5687.8311, obj=-122.9917, eq=5.8037, soc=0.0647, bound=0.0646, true_loss=2.8869

[200] loss=129.4694, obj=-65.3999, eq=0.1912, soc=0.0345, bound=0.0236, true_loss=-4.8800

[400] loss=29.1090, obj=-52.7444, eq=0.0802, soc=0.0153, bound=0.0104, true_loss=-11.8808

[600] loss=-11.1847, obj=-44.4314, eq=0.0325, soc=0.0070, bound=0.0028, true_loss=-18.0566

[800] loss=-26.4344, obj=-42.1118, eq=0.0153, soc=0.0035, bound=0.0009, true_loss=-23.3599

[1000] loss=-34.3800, obj=-43.9915, eq=0.0094, soc=0.0022, bound=0.0005, true_loss=-29.0757

[1200] loss=-40.3547, obj=-48.8648, eq=0.0083, soc=0.0018, bound=0.0003, true_loss=-35.3499

[1400] loss=-48.4177, obj=-55.6162, eq=0.0070, soc=0.0016, bound=0.0003, true_loss=-41.8594

[1600] loss=-54.1425, obj=-61.7042, eq=0.0074, soc=0.0016, bound=0.0002, true_loss=-48.6052

[1800] loss=-60.6161, obj=-68.1536, eq=0.0074, soc=0.0016, bound=0.0002, true_loss=-54.9836

[2000] loss=-65.7274, obj=-74.9057, eq=0.0090, soc=0.0017, bound=0.0003, true_loss=-61.2480

[2200] loss=-72.7794, obj=-79.8015, eq=0.0069, soc=0.0016, bound=0.0002, true_loss=-66.3996

[2400] loss=-76.8668, obj=-84.1728, eq=0.0071, soc=0.0016, bound=0.0002, true_loss=-71.3777

[2600] loss=-81.5687, obj=-88.3496, eq=0.0066, soc=0.0016, bound=0.0002, true_loss=-75.5888

[2800] loss=-85.6091, obj=-92.7621, eq=0.0070, soc=0.0017, bound=0.0002, true_loss=-79.3425

[3000] loss=-88.9810, obj=-95.6825, eq=0.0065, soc=0.0017, bound=0.0002, true_loss=-82.5625

[3200] loss=-91.0440, obj=-98.1156, eq=0.0069, soc=0.0017, bound=0.0002, true_loss=-84.1612

[3400] loss=-92.6307, obj=-100.1590, eq=0.0074, soc=0.0017, bound=0.0002, true_loss=-86.1672

[3600] loss=-94.0630, obj=-101.8420, eq=0.0076, soc=0.0017, bound=0.0002, true_loss=-87.7921

[3800] loss=-96.4079, obj=-103.3366, eq=0.0068, soc=0.0017, bound=0.0002, true_loss=-88.9924

[4000] loss=-97.5214, obj=-104.4929, eq=0.0068, soc=0.0017, bound=0.0001, true_loss=-90.1190

[4200] loss=-98.5043, obj=-105.6713, eq=0.0070, soc=0.0017, bound=0.0001, true_loss=-91.1760

[4400] loss=-99.2709, obj=-106.4981, eq=0.0071, soc=0.0017, bound=0.0001, true_loss=-91.9859

[4600] loss=-100.5687, obj=-107.1851, eq=0.0065, soc=0.0016, bound=0.0001, true_loss=-92.8701

[4800] loss=-100.4491, obj=-107.7764, eq=0.0072, soc=0.0017, bound=0.0001, true_loss=-93.3178

Random-retrained NN history: /Users/liqi/Library/CloudStorage/OneDrive-TheUniversityofHongKong-Connect/Stackelberg Game/Surrogated-assisted Stackelnerg Game/results/NN_solver_new_ablation_history_20260829-125323.csv
Random-retrained NN true objective: -93.9988956781133
Random-retrained NN runtime (s): 1274.1698248386383

## 4. Ablation summary

Lower true objective values are better. The key comparison is between the two equally sized augmented datasets: localized trust-region samples versus globally random samples.

In [10]:
def saved_nn_true_objective(history_path):
    history = pd.read_csv(history_path)
    if "true_loss" not in history.columns:
        return np.nan
    evaluated = history.dropna(subset=["true_loss"])
    if evaluated.empty:
        return np.nan
    return float(evaluated.sort_values("iteration").iloc[-1]["true_loss"])


summary_rows = []
original_nn_path = RESULTS_DIR / "NN_solver_history_20260826-145443.csv"
if original_nn_path.is_file():
    summary_rows.append(
        {
            "method": "Original NN surrogate",
            "true_objective": saved_nn_true_objective(original_nn_path),
            "runtime_seconds": np.nan,
            "history_path": str(original_nn_path),
        }
    )

if tr_nn_result is not None:
    summary_rows.append(
        {
            "method": "NN: original + trust-region samples",
            "true_objective": float(tr_nn_result["true_obj"]),
            "runtime_seconds": float(tr_nn_result["runtime_seconds"]),
            "history_path": tr_nn_result["history_path"],
        }
    )

if new_nn_result is not None:
    summary_rows.append(
        {
            "method": "NN: original + equal random samples",
            "true_objective": float(new_nn_result["true_obj"]),
            "runtime_seconds": float(new_nn_result["runtime_seconds"]),
            "history_path": new_nn_result["history_path"],
        }
    )

summary_rows.append(
    {
        "method": "Trust-region residual correction",
        "true_objective": float(tr_summary["final_true_objective"]),
        "runtime_seconds": np.nan,
        "history_path": str(TR_HISTORY_PATH),
    }
)

ablation_summary = pd.DataFrame(summary_rows)
ablation_summary["objective_gap_vs_tr"] = (
    ablation_summary["true_objective"] - float(tr_summary["final_true_objective"])
)
summary_path = RESULTS_DIR / f"retraining_ablation_summary_{time.strftime('%Y%m%d-%H%M%S')}.csv"
ablation_summary.to_csv(summary_path, index=False)

display(ablation_summary)
print("Saved ablation summary to:", summary_path)

,method,true_objective,runtime_seconds,history_path,objective_gap_vs_tr
0,Original NN surrogate,-93.319467,NaN,/Users/liqi/Library/CloudStorage/OneDrive-TheU...,7.979503
1,NN: original + trust-region samples,-92.306798,1279.312442,/Users/liqi/Library/CloudStorage/OneDrive-TheU...,8.992172
2,NN: original + equal random samples,-93.998896,1274.169825,/Users/liqi/Library/CloudStorage/OneDrive-TheU...,7.300075
3,Trust-region residual correction,-101.298970,NaN,/Users/liqi/Library/CloudStorage/OneDrive-TheU...,0.000000

Saved ablation summary to: /Users/liqi/Library/CloudStorage/OneDrive-TheUniversityofHongKong-Connect/Stackelberg Game/Surrogated-assisted Stackelnerg Game/results/retraining_ablation_summary_20260829-131437.csv

In [1]:
import gurobipy as gp
from gurobipy import GRB

# max  3x + 4y
# s.t. x + 2y <= 14
#      3x - y >= 0
#      x - y  <= 2
#      x, y   >= 0

model = gp.Model("simple_lp")
x = model.addVar(lb=0.0, name="x")
y = model.addVar(lb=0.0, name="y")

model.setObjective(3 * x + 4 * y, GRB.MAXIMIZE)
model.addConstr(x + 2 * y <= 14, name="c1")
model.addConstr(3 * x - y >= 0, name="c2")
model.addConstr(x - y <= 2, name="c3")

model.optimize()

print(f"Status: {model.Status}")
print(f"x = {x.X:.4f}, y = {y.X:.4f}")
print(f"obj = {model.ObjVal:.4f}")

Set parameter Username
Set parameter LicenseID to value 2711611
Academic license - for non-commercial use only - expires 2026-09-22
Gurobi Optimizer version 12.0.3 build v12.0.3rc0 (mac64[arm] - Darwin 25.6.0 25G83)

CPU model: Apple M4
Thread count: 10 physical cores, 10 logical processors, using up to 10 threads

Optimize a model with 3 rows, 2 columns and 6 nonzeros
Model fingerprint: 0x6228bac5
Coefficient statistics:
  Matrix range     [1e+00, 3e+00]
  Objective range  [3e+00, 4e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+00, 1e+01]
Presolve removed 1 rows and 0 columns
Presolve time: 0.00s
Presolved: 2 rows, 2 columns, 4 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    4.2000000e+01   9.996500e+00   0.000000e+00      0s
       1    3.4000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.00 seconds (0.00 work units)
Optimal objective  3.400000000e+01
Status: 2
x = 6.0000, y = 4.0000
obj = 34.0000