# Five-microgrid ablation study: trust-region samples vs. global random samples

This notebook runs one complete experiment from top to bottom. It does not load an old trust-region run. The four methods compared at the end are:

1. the original global L2O models solved with the NN solver;
2. trust-region residual correction initialized from the original NN solution;
3. global L2O models retrained on original + trust-region samples;
4. global L2O models retrained on original + equally many global random samples.

The original zero-initialized NN solution is loaded from `results/000`; the remaining run includes five lower-level models, a trust-region run, two rounds of training, and two new 10,000-step NN solves.

In [ ]:
import time
from pathlib import Path

import numpy as np
import pandas as pd
import pandapower.networks as pn

import follower_solver  
from L2Otraining import TrainingConfig, train
from stackelberg.followers.bg import create_cigre_residential_network
from stackelberg.followers.ip import create_industrial_park_network
from stackelberg.instances import resolve_follower_configuration
from stackelberg.network import create_case33bw_20kv
from stackelberg.nn_solver import (
    NNSolverExperimentConfig,
    run_nn_solver_experiment,
)
from stackelberg.randomness import make_rng, set_global_seed
from stackelberg.trust_region import (
    TrustRegionExperimentConfig,
    run_trust_region_experiment,
)

PROJECT_ROOT = Path.cwd().resolve()
DATA_DIR = PROJECT_ROOT / "data"
MODEL_DIR = PROJECT_ROOT / "NNmodel"
RESULTS_DIR = PROJECT_ROOT / "results"
ORIGINAL_NN_HISTORY_PATH = (
    RESULTS_DIR / "000" / "NN_solver_history_20260912-234954.csv"
)

if not (PROJECT_ROOT / "L2Otraining.py").is_file():
    raise RuntimeError("Run this notebook with the project root as the working directory.")

DATA_DIR.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

T = 24
SEED = 42
NN_STEPS = 10_000
NN_LEARNING_RATE = 1e-2
NN_SAVE_EVERY = 200
TRAINING_EPOCHS = 500
LOWER_TIME_LIMIT = 30.0
LOWER_MIP_GAP = 1e-3
NEW_DATA_CHECKPOINT_INTERVAL = 100
NEW_DATA_SEEDS = {
    "SB1": 4201,
    "SB2": 4202,
    "BG1": 4203,
    "BG2": 4204,
    "IP1": 4205,
}

SCENARIOS = ["SB1", "SB2", "BG1", "BG2", "IP1"]
MG_BUSES = [17, 32, 15, 21, 1]
UPPER_NET = create_case33bw_20kv()
LOWER_NETS = [
    pn.create_cigre_network_lv(),
    pn.create_cigre_network_lv(),
    create_cigre_residential_network(),
    create_cigre_residential_network(),
    create_industrial_park_network(),
]
X0 = np.full((len(SCENARIOS), T), 0.0, dtype=float)

follower_ids, scenario_types, follower_kwargs = resolve_follower_configuration(
    SCENARIOS
)
if follower_ids != SCENARIOS:
    raise RuntimeError(f"Resolved follower order {follower_ids} does not match {SCENARIOS}.")

INSTANCE_NETWORKS = dict(zip(SCENARIOS, LOWER_NETS))
INSTANCE_TYPES = dict(zip(SCENARIOS, scenario_types))
INSTANCE_SOLVER_KWARGS = dict(zip(SCENARIOS, follower_kwargs))

instance_table = pd.DataFrame(
    {
        "follower_id": SCENARIOS,
        "scenario_type": scenario_types,
        "mg_bus": MG_BUSES,
        "solver_kwargs": follower_kwargs,
    }
).set_index("follower_id")
display(instance_table)

            scenario_type  mg_bus           solver_kwargs
follower_id
SB1                    SB      17                      {}
SB2                    SB      32     {'load_scale': 1.1}
BG1                    BG      15  {'date': '2023-01-01'}
BG2                    BG      21  {'date': '2023-07-01'}
IP1                    IP       1  {'date': '2023-01-01'}

In [2]:
def load_aligned_arrays(x_path, y_path, *, expected_rows=None, expected_width=T):
    """Load and validate one aligned price/response dataset."""
    x_path = Path(x_path)
    y_path = Path(y_path)
    if not x_path.is_file() or not y_path.is_file():
        raise FileNotFoundError(f"Expected both {x_path} and {y_path}.")

    x_data = np.load(x_path)
    y_data = np.load(y_path)
    if x_data.ndim != 2 or y_data.ndim != 2:
        raise ValueError(f"Expected 2-D arrays, got X{x_data.shape} and Y{y_data.shape}.")
    if x_data.shape != y_data.shape:
        raise ValueError(f"X/Y shape mismatch: X{x_data.shape} and Y{y_data.shape}.")
    if x_data.shape[1] != expected_width:
        raise ValueError(f"Expected width {expected_width}, got {x_data.shape[1]}.")
    if len(x_data) == 0:
        raise ValueError(f"Dataset is empty: {x_path.name}.")
    if expected_rows is not None and len(x_data) != expected_rows:
        raise ValueError(
            f"Expected {expected_rows} rows in {x_path.name}, got {len(x_data)}."
        )
    if not np.isfinite(x_data).all() or not np.isfinite(y_data).all():
        raise ValueError(f"Non-finite values found in {x_path.name} or {y_path.name}.")
    if np.any(x_data < -1e-12) or np.any(x_data > 1.5 + 1e-12):
        raise ValueError(f"Prices in {x_path.name} must lie in [0, 1.5].")
    return x_data, y_data


def atomic_save_npy(path, array):
    """Replace a NumPy file only after the complete array is serialized."""
    path = Path(path)
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    with temporary_path.open("wb") as file:
        np.save(file, np.asarray(array))
    temporary_path.replace(path)


for scenario in SCENARIOS:
    load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy",
        DATA_DIR / f"Y_{scenario}.npy",
    )
    for suffix in (".pth", ".json"):
        model_path = MODEL_DIR / f"L2O_{scenario}{suffix}"
        if not model_path.is_file():
            raise FileNotFoundError(model_path)

print("Validated original datasets and L2O checkpoints for all five instances.")

Validated original datasets and L2O checkpoints for all five instances.

## 1. Load the existing zero-initialized original NN solution

The original NN solver is not rerun. Its last saved iterate is loaded from `results/000`; the two retrained NN-solver runs use the same all-zero initial price matrix and 10,000-step budget.

In [3]:
if not ORIGINAL_NN_HISTORY_PATH.is_file():
    raise FileNotFoundError(ORIGINAL_NN_HISTORY_PATH)

original_nn_history = pd.read_csv(ORIGINAL_NN_HISTORY_PATH)
if original_nn_history.empty:
    raise ValueError(f"Warm-start history is empty: {ORIGINAL_NN_HISTORY_PATH}")

price_columns = [f"pi_{index}" for index in range(len(SCENARIOS) * T)]
missing_columns = [
    column for column in ["iteration", "true_loss", *price_columns]
    if column not in original_nn_history.columns
]
if missing_columns:
    raise ValueError(f"Warm-start history is missing columns: {missing_columns}")

original_nn_last = original_nn_history.sort_values("iteration").iloc[-1]
original_nn_prices = original_nn_last[price_columns].to_numpy(dtype=float).reshape(
    len(SCENARIOS), T
)
if not np.isfinite(original_nn_prices).all():
    raise ValueError("Warm-start prices contain non-finite values.")
if np.any(original_nn_prices < 0.0) or np.any(original_nn_prices > 1.5):
    raise ValueError("Warm-start prices must lie in [0, 1.5].")
original_true_objective = float(original_nn_last["true_loss"])
if not np.isfinite(original_true_objective):
    raise ValueError("Warm-start true objective is not finite.")

original_nn_result = {
    "optimal pi": original_nn_prices,
    "true_obj": original_true_objective,
    "runtime_seconds": np.nan,
    "history_path": str(ORIGINAL_NN_HISTORY_PATH),
}

print("Loaded original NN warm start:", original_nn_result["history_path"])
print("Saved iteration:", int(original_nn_last["iteration"]))
print("Original NN true objective:", original_nn_result["true_obj"])
display(pd.DataFrame(original_nn_prices, index=SCENARIOS))

Loaded original NN warm start: /Users/liqi/Desktop/Codes/Surrogated-assisted Stackelnerg Game/results/000/NN_solver_history_20260912-234954.csv
Saved iteration: 9800
Original NN true objective: -103.73745796679384

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
SB1,0.905496,0.972395,0.992483,0.998625,0.982330,0.981594,1.006895,1.002889,0.991757,1.000325,...,1.037887,1.018056,1.024587,0.997190,0.993872,1.024512,1.423613,1.006008,1.086199,0.996892
SB2,0.984292,0.985921,0.971553,0.977133,0.962063,0.958349,1.004334,0.994941,1.498616,0.988460,...,1.011563,0.999690,0.996986,0.981880,1.001129,1.013935,0.991371,0.986417,1.089251,0.993309
BG1,1.499927,1.499906,1.499724,1.499684,1.499929,1.499869,1.499946,1.499939,1.499915,1.499948,...,1.499942,1.499932,1.499939,1.499932,1.499938,1.499940,1.499914,0.261827,1.499944,1.499898
BG2,1.499915,1.499862,1.499867,1.499870,1.499940,1.499835,1.499953,1.499933,1.499934,1.499927,...,1.499954,1.499947,1.499947,1.499948,1.499952,1.499953,1.499886,1.499871,1.499922,1.499468
IP1,1.493962,1.488898,1.495653,1.494458,1.490675,1.476853,1.496844,1.499135,1.499072,1.499319,...,1.499453,1.499741,1.499321,1.497359,1.494321,1.498004,1.496904,1.494693,1.498408,1.498219

## 2. Trust region and fresh trust-region training samples

The trust region starts at the original NN solution. `save_true_responses=True` retains the high-fidelity residual-fit designs, including each local center, and the controller removes duplicate rows across iterations before export. The resulting files replace the known-invalid `_tr` datasets.

In [4]:
tr_config = TrustRegionExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=original_nn_prices,
    lower_time_limit=LOWER_TIME_LIMIT,
    lower_mip_gap=LOWER_MIP_GAP,
    copt_initialize_network_state=True,
    tr_params={
        "R_0": 0.05,
        "R_max": 1.0,
        "gamma_dec": 0.7,
        "gamma_inc": 1.5,
        "eta_1": 0.1,
        "eta_2": 0.75,
    },
    algo_params={
        "n_samples": 60,
        "K_max": 60,
        "sampling_method": "lhs",
        "residual_update_mode": "accumulate",
        "rbf_geometry_condition_max": 1e12,
        "solve_params": {
            "steps_init": 0,
            "steps_warm": 2000,
            "lr": 1e-2,
            "penalty_weights": {
                "eq": 1000.0,
                "ineq": 100.0,
                "soc": 100.0,
                "bound": 10.0,
            },
            "tr_weight": 1e6,
            "verbose": True,
        },
    },
    residual_model_params={
        "model_type": "rbf",
        "rbf_kernel": "cubic",
        "rbf_smoothing": 1e-3,
        "rbf_degree": 1,
        "rbf_scale": "trust_radius",
        "rbf_epsilon": None,
    },
    save_results=True,
    output_dir=str(RESULTS_DIR),
    save_true_responses=True,
    true_response_dir=str(DATA_DIR),
    true_response_tag="tr",
)
tr_result = run_trust_region_experiment(tr_config)
tr_prices = np.asarray(tr_result["x_opt"], dtype=float).reshape(
    len(SCENARIOS), T
)
tr_history = pd.DataFrame(tr_result["history"])
if tr_history.empty:
    raise RuntimeError("Trust-region history is empty.")
tr_last = tr_history.iloc[-1]
tr_objective = float(
    tr_last["F_candidate"]
    if str(tr_last["decision"]).startswith("accept")
    else tr_last["F_current"]
)
tr_composite_queries = int(
    tr_result["n_iter"] * (tr_config.algo_params["n_samples"] + 1)
)

print("Trust region converged:", tr_result["converged"])
print("Trust region iterations:", tr_result["n_iter"])
print("Trust region true objective:", tr_objective)
print("Trust region composite high-fidelity queries:", tr_composite_queries)
print("Saved paths:", tr_result.get("saved_paths"))

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Using global surrogate to solve initial point...
Initial surrogate solve used steps_init=0. Time taken to solve initial point 0.0613 seconds.
Iteration 0 | R=0.0500
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0500...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.1549e+04
Follower 1 RBF interpolation condition number: 4.9430e+05
Follower 2 RBF interpolation condition number: 6.4673e+05
Follower 3 RBF interpolation condition number: 6.5962e+05
Follower 4 RBF interpolation condition number: 5.6811e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   0] F_current=-103.8277 | F_candidate=-104.1335 | F_tilde_current=-103.6793 | F_tilde_candidate=-110.7795 | Ared=0.3058 | Pred=7.1002 | rho=0.0431 | decision=accept_shrink | R=0.0500 | residual_update=accumulate | n_residuals=1
Accepting step 0 and shrinking...
Time taken to solve iteration 0 495.3016 seconds.
Iteration 1 | R=0.0350
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0350...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.9141e+04
Follower 1 RBF interpolation condition number: 5.0604e+04
Follower 2 RBF interpolation condition number: 6.7972e+05
Follower 3 RBF interpolation condition number: 6.2049e+05
Follower 4 RBF interpolation condition number: 5.9867e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   1] F_current=-104.1335 | F_candidate=-103.8778 | F_tilde_current=-104.1489 | F_tilde_candidate=-105.7027 | Ared=-0.2557 | Pred=1.5538 | rho=-0.1646 | decision=reject | R=0.0350 | residual_update=accumulate | n_residuals=1
Rejecting step 1...
Time taken to solve iteration 1 491.6081 seconds.
Iteration 2 | R=0.0245
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0245...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.0607e+04
Follower 1 RBF interpolation condition number: 4.9663e+04
Follower 2 RBF interpolation condition number: 6.8881e+05
Follower 3 RBF interpolation condition number: 6.1975e+05
Follower 4 RBF interpolation condition number: 6.6263e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   2] F_current=-104.1335 | F_candidate=-104.4656 | F_tilde_current=-104.1562 | F_tilde_candidate=-105.5746 | Ared=0.3321 | Pred=1.4184 | rho=0.2341 | decision=accept_keep | R=0.0245 | residual_update=accumulate | n_residuals=2
Accepting step 2 and keeping...
Time taken to solve iteration 2 478.7207 seconds.
Iteration 3 | R=0.0245
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0245...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0507e+05
Follower 1 RBF interpolation condition number: 5.3258e+04
Follower 2 RBF interpolation condition number: 7.4126e+05
Follower 3 RBF interpolation condition number: 6.1673e+05
Follower 4 RBF interpolation condition number: 6.5848e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   3] F_current=-104.4659 | F_candidate=-104.5488 | F_tilde_current=-104.4336 | F_tilde_candidate=-105.2937 | Ared=0.0829 | Pred=0.8601 | rho=0.0964 | decision=accept_shrink | R=0.0245 | residual_update=accumulate | n_residuals=3
Accepting step 3 and shrinking...
Time taken to solve iteration 3 473.1899 seconds.
Iteration 4 | R=0.0171
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0171...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 9.9312e+05
Follower 1 RBF interpolation condition number: 5.3174e+04
Follower 2 RBF interpolation condition number: 7.7679e+05
Follower 3 RBF interpolation condition number: 6.2337e+05
Follower 4 RBF interpolation condition number: 7.8774e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   4] F_current=-104.5488 | F_candidate=-104.8555 | F_tilde_current=-104.5268 | F_tilde_candidate=-105.2833 | Ared=0.3067 | Pred=0.7565 | rho=0.4054 | decision=accept_keep | R=0.0171 | residual_update=accumulate | n_residuals=4
Accepting step 4 and keeping...
Time taken to solve iteration 4 475.0421 seconds.
Iteration 5 | R=0.0171
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0171...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0811e+06
Follower 1 RBF interpolation condition number: 5.7011e+04
Follower 2 RBF interpolation condition number: 7.2208e+05
Follower 3 RBF interpolation condition number: 6.2900e+05
Follower 4 RBF interpolation condition number: 7.5697e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   5] F_current=-104.8540 | F_candidate=-104.5713 | F_tilde_current=-104.8376 | F_tilde_candidate=-105.9225 | Ared=-0.2826 | Pred=1.0849 | rho=-0.2605 | decision=reject | R=0.0171 | residual_update=accumulate | n_residuals=4
Rejecting step 5...
Time taken to solve iteration 5 475.3621 seconds.
Iteration 6 | R=0.0120
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0120...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0226e+06
Follower 1 RBF interpolation condition number: 4.8931e+04
Follower 2 RBF interpolation condition number: 7.1789e+05
Follower 3 RBF interpolation condition number: 6.1232e+05
Follower 4 RBF interpolation condition number: 8.5925e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   6] F_current=-104.8540 | F_candidate=-104.7009 | F_tilde_current=-104.8403 | F_tilde_candidate=-105.8682 | Ared=-0.1530 | Pred=1.0279 | rho=-0.1489 | decision=reject | R=0.0120 | residual_update=accumulate | n_residuals=4
Rejecting step 6...
Time taken to solve iteration 6 475.9806 seconds.
Iteration 7 | R=0.0084
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0084...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 9.9537e+05
Follower 1 RBF interpolation condition number: 5.0363e+04
Follower 2 RBF interpolation condition number: 7.7567e+05
Follower 3 RBF interpolation condition number: 6.1948e+05
Follower 4 RBF interpolation condition number: 9.8679e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   7] F_current=-104.8540 | F_candidate=-105.2097 | F_tilde_current=-104.8413 | F_tilde_candidate=-106.0140 | Ared=0.3557 | Pred=1.1727 | rho=0.3033 | decision=accept_keep | R=0.0084 | residual_update=accumulate | n_residuals=5
Accepting step 7 and keeping...
Time taken to solve iteration 7 477.1225 seconds.
Iteration 8 | R=0.0084
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0084...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.1029e+06
Follower 1 RBF interpolation condition number: 5.2141e+04
Follower 2 RBF interpolation condition number: 7.7728e+05
Follower 3 RBF interpolation condition number: 6.3620e+05
Follower 4 RBF interpolation condition number: 8.4435e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   8] F_current=-105.2097 | F_candidate=-105.1049 | F_tilde_current=-105.2068 | F_tilde_candidate=-105.9841 | Ared=-0.1048 | Pred=0.7772 | rho=-0.1348 | decision=reject | R=0.0084 | residual_update=accumulate | n_residuals=5
Rejecting step 8...
Time taken to solve iteration 8 488.4498 seconds.
Iteration 9 | R=0.0059
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0059...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0293e+06
Follower 1 RBF interpolation condition number: 5.0925e+04
Follower 2 RBF interpolation condition number: 7.7982e+05
Follower 3 RBF interpolation condition number: 6.2390e+05
Follower 4 RBF interpolation condition number: 9.5843e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter   9] F_current=-105.2097 | F_candidate=-105.0486 | F_tilde_current=-105.2073 | F_tilde_candidate=-105.7351 | Ared=-0.1610 | Pred=0.5278 | rho=-0.3051 | decision=reject | R=0.0059 | residual_update=accumulate | n_residuals=5
Rejecting step 9...
Time taken to solve iteration 9 485.3852 seconds.
Iteration 10 | R=0.0041
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0041...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0101e+06
Follower 1 RBF interpolation condition number: 5.2771e+04
Follower 2 RBF interpolation condition number: 8.3335e+05
Follower 3 RBF interpolation condition number: 6.0153e+05
Follower 4 RBF interpolation condition number: 1.0187e+06
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  10] F_current=-105.2097 | F_candidate=-105.3470 | F_tilde_current=-105.2086 | F_tilde_candidate=-105.6144 | Ared=0.1374 | Pred=0.4059 | rho=0.3385 | decision=accept_keep | R=0.0041 | residual_update=accumulate | n_residuals=6
Accepting step 10 and keeping...
Time taken to solve iteration 10 485.3958 seconds.
Iteration 11 | R=0.0041
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0041...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0920e+06
Follower 1 RBF interpolation condition number: 5.4769e+04
Follower 2 RBF interpolation condition number: 8.6457e+05
Follower 3 RBF interpolation condition number: 6.4707e+05
Follower 4 RBF interpolation condition number: 9.3643e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  11] F_current=-105.3470 | F_candidate=-105.3947 | F_tilde_current=-105.3468 | F_tilde_candidate=-105.6314 | Ared=0.0477 | Pred=0.2846 | rho=0.1675 | decision=accept_keep | R=0.0041 | residual_update=accumulate | n_residuals=7
Accepting step 11 and keeping...
Time taken to solve iteration 11 484.0180 seconds.
Iteration 12 | R=0.0041
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0041...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0781e+06
Follower 1 RBF interpolation condition number: 5.6693e+04
Follower 2 RBF interpolation condition number: 9.0751e+05
Follower 3 RBF interpolation condition number: 6.2189e+05
Follower 4 RBF interpolation condition number: 9.2634e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  12] F_current=-105.3947 | F_candidate=-105.4364 | F_tilde_current=-105.3952 | F_tilde_candidate=-106.1990 | Ared=0.0417 | Pred=0.8038 | rho=0.0518 | decision=accept_shrink | R=0.0041 | residual_update=accumulate | n_residuals=8
Accepting step 12 and shrinking...
Time taken to solve iteration 12 484.4070 seconds.
Iteration 13 | R=0.0029
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0029...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 1.0083e+06
Follower 1 RBF interpolation condition number: 5.5626e+04
Follower 2 RBF interpolation condition number: 8.8793e+05
Follower 3 RBF interpolation condition number: 6.0165e+05
Follower 4 RBF interpolation condition number: 8.8770e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  13] F_current=-105.4364 | F_candidate=-105.5082 | F_tilde_current=-105.4376 | F_tilde_candidate=-105.9667 | Ared=0.0718 | Pred=0.5291 | rho=0.1358 | decision=accept_keep | R=0.0029 | residual_update=accumulate | n_residuals=9
Accepting step 13 and keeping...
Time taken to solve iteration 13 486.3974 seconds.
Iteration 14 | R=0.0029
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0029...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.0167e+04
Follower 1 RBF interpolation condition number: 5.4996e+04
Follower 2 RBF interpolation condition number: 8.5094e+05
Follower 3 RBF interpolation condition number: 6.0397e+05
Follower 4 RBF interpolation condition number: 8.8264e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  14] F_current=-105.5082 | F_candidate=-105.4340 | F_tilde_current=-105.5092 | F_tilde_candidate=-106.3885 | Ared=-0.0742 | Pred=0.8793 | rho=-0.0844 | decision=reject | R=0.0029 | residual_update=accumulate | n_residuals=9
Rejecting step 14...
Time taken to solve iteration 14 490.1208 seconds.
Iteration 15 | R=0.0020
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0020...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.6738e+04
Follower 1 RBF interpolation condition number: 5.2056e+04
Follower 2 RBF interpolation condition number: 8.5575e+05
Follower 3 RBF interpolation condition number: 5.8202e+05
Follower 4 RBF interpolation condition number: 7.8173e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  15] F_current=-105.5082 | F_candidate=-105.6045 | F_tilde_current=-105.5098 | F_tilde_candidate=-105.9585 | Ared=0.0963 | Pred=0.4487 | rho=0.2146 | decision=accept_keep | R=0.0020 | residual_update=accumulate | n_residuals=10
Accepting step 15 and keeping...
Time taken to solve iteration 15 497.2458 seconds.
Iteration 16 | R=0.0020
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0020...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.4056e+04
Follower 1 RBF interpolation condition number: 4.9443e+04
Follower 2 RBF interpolation condition number: 8.5813e+05
Follower 3 RBF interpolation condition number: 6.0856e+05
Follower 4 RBF interpolation condition number: 7.4521e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  16] F_current=-105.6045 | F_candidate=-105.6210 | F_tilde_current=-105.5897 | F_tilde_candidate=-105.9582 | Ared=0.0165 | Pred=0.3685 | rho=0.0447 | decision=accept_shrink | R=0.0020 | residual_update=accumulate | n_residuals=11
Accepting step 16 and shrinking...
Time taken to solve iteration 16 517.7787 seconds.
Iteration 17 | R=0.0014
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0014...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 5.1872e+04
Follower 1 RBF interpolation condition number: 5.1732e+04
Follower 2 RBF interpolation condition number: 8.8726e+05
Follower 3 RBF interpolation condition number: 5.7296e+05
Follower 4 RBF interpolation condition number: 6.0111e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  17] F_current=-105.6210 | F_candidate=-105.6547 | F_tilde_current=-105.6081 | F_tilde_candidate=-105.8862 | Ared=0.0337 | Pred=0.2781 | rho=0.1213 | decision=accept_keep | R=0.0014 | residual_update=accumulate | n_residuals=12
Accepting step 17 and keeping...
Time taken to solve iteration 17 526.5474 seconds.
Iteration 18 | R=0.0014
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0014...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 4.7719e+04
Follower 1 RBF interpolation condition number: 5.3505e+04
Follower 2 RBF interpolation condition number: 8.9442e+05
Follower 3 RBF interpolation condition number: 5.8402e+05
Follower 4 RBF interpolation condition number: 7.4743e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...
[Iter  18] F_current=-105.6547 | F_candidate=-105.6694 | F_tilde_current=-105.6432 | F_tilde_candidate=-105.9435 | Ared=0.0146 | Pred=0.3002 | rho=0.0487 | decision=accept_shrink | R=0.0014 | residual_update=accumulate | n_residuals=13
Accepting step 18 and shrinking...
Time taken to solve iteration 18 508.4866 seconds.
Iteration 19 | R=0.0010
Building 60-point local designs for each of 5 followers (center + coordinate star + LHS) within R_tr=0.0010...
Fitting follower-local residual models with sample counts [60, 60, 60, 60, 60]...
Follower 0 RBF interpolation condition number: 6.8947e+04
Follower 1 RBF interpolation condition number: 5.1389e+04
Follower 2 RBF interpolation condition number: 7.9226e+05
Follower 3 RBF interpolation condition number: 5.4808e+05
Follower 4 RBF interpolation condition number: 6.2787e+05
Constructing temporary surrogate and solving with steps_warm=2000...
Evaluating surrogate and actual objective...
Computing ratio and deciding step...

In [5]:
current_tr_responses = tr_result.get("true_responses", {})
if set(current_tr_responses) != set(SCENARIOS):
    raise RuntimeError(
        f"Expected current-run TR samples for {SCENARIOS}, got "
        f"{sorted(current_tr_responses)}."
    )

tr_sample_counts = {}
sample_rows = []
for scenario in SCENARIOS:
    original_x, original_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy",
        DATA_DIR / f"Y_{scenario}.npy",
    )
    tr_x, tr_y = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_tr.npy",
        DATA_DIR / f"Y_{scenario}_tr.npy",
    )
    in_memory_x = np.asarray(current_tr_responses[scenario]["X"], dtype=float)
    in_memory_y = np.asarray(current_tr_responses[scenario]["Y"], dtype=float)
    np.testing.assert_allclose(tr_x, in_memory_x)
    np.testing.assert_allclose(tr_y, in_memory_y)

    tr_sample_counts[scenario] = len(tr_x)
    sample_rows.append(
        {
            "scenario": scenario,
            "original_samples": len(original_x),
            "trust_region_samples": len(tr_x),
            "tr_combined_samples": len(original_x) + len(tr_x),
        }
    )

tr_sample_count_table = pd.DataFrame(sample_rows).set_index("scenario")
display(tr_sample_count_table)

          original_samples  trust_region_samples  tr_combined_samples
scenario
SB1                  10000                  2748                12748
SB2                  10000                  2752                12752
BG1                  10000                  2646                12646
BG2                  10000                  1304                11304
IP1                  10000                  2682                12682

## 3. Retrain global models on original + trust-region samples

Each follower instance remains separate. Training writes `L2O_XX_tr.pth/.json` and leaves the original checkpoints unchanged.

In [6]:
def training_config(scenario):
    return TrainingConfig(
        scenario=scenario,
        hidden_dim=128,
        residual_blocks=3,
        batch_size=64,
        learning_rate=1e-3,
        epochs=TRAINING_EPOCHS,
        validation_fraction=0.2,
        seed=SEED,
    )


tr_training_results = {}
for scenario in SCENARIOS:
    print(f"\nTraining {scenario} on original + trust-region samples")
    tr_training_results[scenario] = train(
        scenario,
        config=training_config(scenario),
        data_tag="tr",
        model_tag="tr",
        include_original=True,
    )
    for suffix in (".pth", ".json"):
        expected_model = MODEL_DIR / f"L2O_{scenario}_tr{suffix}"
        if not expected_model.is_file():
            raise FileNotFoundError(expected_model)

display(pd.DataFrame(tr_training_results).T.rename_axis("scenario"))

Training SB1 on original + trust-region samples
SB1: concatenated original 10000 + tr 2748 samples -> 12748
SB1 epoch   10/500: train=0.050791, validation=0.053268
SB1 epoch   20/500: train=0.037227, validation=0.039422
SB1 epoch   30/500: train=0.028161, validation=0.029948
SB1 epoch   40/500: train=0.020378, validation=0.022005
SB1 epoch   50/500: train=0.012537, validation=0.013637
SB1 epoch   60/500: train=0.008957, validation=0.009988
SB1 epoch   70/500: train=0.009582, validation=0.010461
SB1 epoch   80/500: train=0.007296, validation=0.008062
SB1 epoch   90/500: train=0.007172, validation=0.007896
SB1 epoch  100/500: train=0.008777, validation=0.009383
SB1 epoch  110/500: train=0.004280, validation=0.004888
SB1 epoch  120/500: train=0.003644, validation=0.004159
SB1 epoch  130/500: train=0.002837, validation=0.003374
SB1 epoch  140/500: train=0.003291, validation=0.003715
SB1 epoch  150/500: train=0.008371, validation=0.008717
SB1 epoch  160/500: train=0.002032, validation=0.002425
SB1 epoch  170/500: train=0.001775, validation=0.002126
SB1 epoch  180/500: train=0.001534, validation=0.001853
SB1 epoch  190/500: train=0.001312, validation=0.001577
SB1 epoch  200/500: train=0.001152, validation=0.001443
SB1 epoch  210/500: train=0.001217, validation=0.001519
SB1 epoch  220/500: train=0.001576, validation=0.001805
SB1 epoch  230/500: train=0.002128, validation=0.002405
SB1 epoch  240/500: train=0.000811, validation=0.001022
SB1 epoch  250/500: train=0.000952, validation=0.001215
SB1 epoch  260/500: train=0.000947, validation=0.001199
SB1 epoch  270/500: train=0.000663, validation=0.000905
SB1 epoch  280/500: train=0.000727, validation=0.000986
SB1 epoch  290/500: train=0.000888, validation=0.001077
SB1 epoch  300/500: train=0.000728, validation=0.000950
SB1 epoch  310/500: train=0.000763, validation=0.000978
SB1 epoch  320/500: train=0.000664, validation=0.000895
SB1 epoch  330/500: train=0.000657, validation=0.000876
SB1 epoch  340/500: train=0.000627, validation=0.000847
SB1 epoch  350/500: train=0.000702, validation=0.000892
SB1 epoch  360/500: train=0.000720, validation=0.000891
SB1 epoch  370/500: train=0.000500, validation=0.000680
SB1 epoch  380/500: train=0.000632, validation=0.000803
SB1 epoch  390/500: train=0.000554, validation=0.000739
SB1 epoch  400/500: train=0.000524, validation=0.000696
SB1 epoch  410/500: train=0.000540, validation=0.000706
SB1 epoch  420/500: train=0.000553, validation=0.000738
SB1 epoch  430/500: train=0.000538, validation=0.000685
SB1 epoch  440/500: train=0.000550, validation=0.000675
SB1 epoch  450/500: train=0.000467, validation=0.000608
SB1 epoch  460/500: train=0.000643, validation=0.000778
SB1 epoch  470/500: train=0.000476, validation=0.000628
SB1 epoch  480/500: train=0.000566, validation=0.000699
SB1 epoch  490/500: train=0.000487, validation=0.000605
SB1 epoch  500/500: train=0.000446, validation=0.000573

Training SB2 on original + trust-region samples
SB2: concatenated original 10000 + tr 2752 samples -> 12752
SB2 epoch   10/500: train=0.044097, validation=0.047186
SB2 epoch   20/500: train=0.031208, validation=0.033460
SB2 epoch   30/500: train=0.029794, validation=0.031584
SB2 epoch   40/500: train=0.020844, validation=0.022105
SB2 epoch   50/500: train=0.015324, validation=0.016339
SB2 epoch   60/500: train=0.009925, validation=0.010953
SB2 epoch   70/500: train=0.009322, validation=0.010374
SB2 epoch   80/500: train=0.006883, validation=0.007780
SB2 epoch   90/500: train=0.005063, validation=0.005826
SB2 epoch  100/500: train=0.004346, validation=0.004959
SB2 epoch  110/500: train=0.003315, validation=0.003890
SB2 epoch  120/500: train=0.002520, validation=0.003007
SB2 epoch  130/500: train=0.002080, validation=0.002477
SB2 epoch  140/500: train=0.002077, validation=0.002521
SB2 epoch  150/500: train=0.001722, validation=0.002083
SB2 epoch  160/500: train=0.001501, validation=0.001900
SB2 epoch  170/500: train=0.001485, validation=0.001754
SB2 epoch  180/500: train=0.001203, validation=0.001469
SB2 epoch  190/500: train=0.001538, validation=0.001771
SB2 epoch  200/500: train=0.001141, validation=0.001355
SB2 epoch  210/500: train=0.001707, validation=0.002030
SB2 epoch  220/500: train=0.001242, validation=0.001428
SB2 epoch  230/500: train=0.001143, validation=0.001342
SB2 epoch  240/500: train=0.001176, validation=0.001338
SB2 epoch  250/500: train=0.000821, validation=0.001009
SB2 epoch  260/500: train=0.000858, validation=0.001042
SB2 epoch  270/500: train=0.000809, validation=0.000997
SB2 epoch  280/500: train=0.000791, validation=0.000959
SB2 epoch  290/500: train=0.001008, validation=0.001171
SB2 epoch  300/500: train=0.000905, validation=0.001049
SB2 epoch  310/500: train=0.000894, validation=0.001032
SB2 epoch  320/500: train=0.000811, validation=0.000951
SB2 epoch  330/500: train=0.000808, validation=0.000918
SB2 epoch  340/500: train=0.000650, validation=0.000777
SB2 epoch  350/500: train=0.000833, validation=0.000961
SB2 epoch  360/500: train=0.000640, validation=0.000769
SB2 epoch  370/500: train=0.000661, validation=0.000807
SB2 epoch  380/500: train=0.000774, validation=0.000903
SB2 epoch  390/500: train=0.000721, validation=0.000859
SB2 epoch  400/500: train=0.000752, validation=0.000902
SB2 epoch  410/500: train=0.000676, validation=0.000775
SB2 epoch  420/500: train=0.000777, validation=0.000847
SB2 epoch  430/500: train=0.000568, validation=0.000692
SB2 epoch  440/500: train=0.000678, validation=0.000785
SB2 epoch  450/500: train=0.000569, validation=0.000686
SB2 epoch  460/500: train=0.000600, validation=0.000721
SB2 epoch  470/500: train=0.000652, validation=0.000781
SB2 epoch  480/500: train=0.000658, validation=0.000793
SB2 epoch  490/500: train=0.000717, validation=0.000838
SB2 epoch  500/500: train=0.000771, validation=0.000911

Training BG1 on original + trust-region samples
BG1: concatenated original 10000 + tr 2646 samples -> 12646
BG1 epoch   10/500: train=0.046510, validation=0.046341
BG1 epoch   20/500: train=0.536016, validation=0.536932
BG1 epoch   30/500: train=0.114583, validation=0.113848
BG1 epoch   40/500: train=0.148633, validation=0.147844
BG1 epoch   50/500: train=0.110161, validation=0.110280
BG1 epoch   60/500: train=0.120742, validation=0.120180
BG1 epoch   70/500: train=0.191990, validation=0.190774
BG1 epoch   80/500: train=0.329447, validation=0.329649
BG1 epoch   90/500: train=0.004012, validation=0.004027
BG1 epoch  100/500: train=0.005399, validation=0.005389
BG1 epoch  110/500: train=0.004571, validation=0.004592
BG1 epoch  120/500: train=0.038433, validation=0.038507
BG1 epoch  130/500: train=0.008759, validation=0.008737
BG1 epoch  140/500: train=0.003851, validation=0.003863
BG1 epoch  150/500: train=0.004551, validation=0.004561
BG1 epoch  160/500: train=0.004900, validation=0.004912
BG1 epoch  170/500: train=0.028849, validation=0.028731
BG1 epoch  180/500: train=0.012314, validation=0.012362
BG1 epoch  190/500: train=0.011842, validation=0.011723
BG1 epoch  200/500: train=0.014355, validation=0.014394
BG1 epoch  210/500: train=0.021041, validation=0.020976
BG1 epoch  220/500: train=0.003502, validation=0.003501
BG1 epoch  230/500: train=0.002003, validation=0.002005
BG1 epoch  240/500: train=0.001696, validation=0.001700
BG1 epoch  250/500: train=0.001810, validation=0.001823
BG1 epoch  260/500: train=0.001693, validation=0.001703
BG1 epoch  270/500: train=0.005674, validation=0.005687
BG1 epoch  280/500: train=0.001368, validation=0.001391
BG1 epoch  290/500: train=0.001841, validation=0.001860
BG1 epoch  300/500: train=0.001854, validation=0.001865
BG1 epoch  310/500: train=0.001443, validation=0.001459
BG1 epoch  320/500: train=0.001032, validation=0.001046
BG1 epoch  330/500: train=0.001574, validation=0.001590
BG1 epoch  340/500: train=0.001072, validation=0.001094
BG1 epoch  350/500: train=0.001137, validation=0.001161
BG1 epoch  360/500: train=0.001094, validation=0.001130
BG1 epoch  370/500: train=0.000984, validation=0.001009
BG1 epoch  380/500: train=0.001284, validation=0.001301
BG1 epoch  390/500: train=0.001164, validation=0.001188
BG1 epoch  400/500: train=0.000877, validation=0.000907
BG1 epoch  410/500: train=0.001063, validation=0.001086
BG1 epoch  420/500: train=0.001573, validation=0.001588
BG1 epoch  430/500: train=0.001118, validation=0.001147
BG1 epoch  440/500: train=0.000891, validation=0.000919
BG1 epoch  450/500: train=0.002373, validation=0.002394
BG1 epoch  460/500: train=0.000898, validation=0.000925
BG1 epoch  470/500: train=0.001446, validation=0.001458
BG1 epoch  480/500: train=0.001080, validation=0.001103
BG1 epoch  490/500: train=0.001062, validation=0.001081
BG1 epoch  500/500: train=0.000983, validation=0.001006

Training BG2 on original + trust-region samples
BG2: concatenated original 10000 + tr 1304 samples -> 11304
BG2 epoch   10/500: train=0.017179, validation=0.017434
BG2 epoch   20/500: train=0.030545, validation=0.030735
BG2 epoch   30/500: train=0.013838, validation=0.013920
BG2 epoch   40/500: train=0.016116, validation=0.016201
BG2 epoch   50/500: train=0.005815, validation=0.005881
BG2 epoch   60/500: train=0.004236, validation=0.004281
BG2 epoch   70/500: train=0.004739, validation=0.004807
BG2 epoch   80/500: train=0.004506, validation=0.004547
BG2 epoch   90/500: train=0.003281, validation=0.003319
BG2 epoch  100/500: train=0.004089, validation=0.004131
BG2 epoch  110/500: train=0.005007, validation=0.005057
BG2 epoch  120/500: train=0.008663, validation=0.008699
BG2 epoch  130/500: train=0.042807, validation=0.043042
BG2 epoch  140/500: train=0.017099, validation=0.017145
BG2 epoch  150/500: train=0.008960, validation=0.009030
BG2 epoch  160/500: train=0.002741, validation=0.002795
BG2 epoch  170/500: train=0.017281, validation=0.017309
BG2 epoch  180/500: train=0.003837, validation=0.003906
BG2 epoch  190/500: train=0.001896, validation=0.001944
BG2 epoch  200/500: train=0.002105, validation=0.002166
BG2 epoch  210/500: train=0.002908, validation=0.002967
BG2 epoch  220/500: train=0.015705, validation=0.015628
BG2 epoch  230/500: train=0.001975, validation=0.002024
BG2 epoch  240/500: train=0.013862, validation=0.013915
BG2 epoch  250/500: train=0.002617, validation=0.002663
BG2 epoch  260/500: train=0.008355, validation=0.008396
BG2 epoch  270/500: train=0.002053, validation=0.002112
BG2 epoch  280/500: train=0.001314, validation=0.001370
BG2 epoch  290/500: train=0.002110, validation=0.002159
BG2 epoch  300/500: train=0.001704, validation=0.001752
BG2 epoch  310/500: train=0.001121, validation=0.001166
BG2 epoch  320/500: train=0.001577, validation=0.001629
BG2 epoch  330/500: train=0.002019, validation=0.002066
BG2 epoch  340/500: train=0.001233, validation=0.001281
BG2 epoch  350/500: train=0.001583, validation=0.001633
BG2 epoch  360/500: train=0.000630, validation=0.000682
BG2 epoch  370/500: train=0.000636, validation=0.000693
BG2 epoch  380/500: train=0.001780, validation=0.001834
BG2 epoch  390/500: train=0.002319, validation=0.002358
BG2 epoch  400/500: train=0.000711, validation=0.000770
BG2 epoch  410/500: train=0.000737, validation=0.000795
BG2 epoch  420/500: train=0.000741, validation=0.000802
BG2 epoch  430/500: train=0.000615, validation=0.000679
BG2 epoch  440/500: train=0.000607, validation=0.000669
BG2 epoch  450/500: train=0.000568, validation=0.000630
BG2 epoch  460/500: train=0.001746, validation=0.001785
BG2 epoch  470/500: train=0.000562, validation=0.000619
BG2 epoch  480/500: train=0.000531, validation=0.000592
BG2 epoch  490/500: train=0.000495, validation=0.000560
BG2 epoch  500/500: train=0.000535, validation=0.000606

Training IP1 on original + trust-region samples
IP1: concatenated original 10000 + tr 2682 samples -> 12682
IP1 epoch   10/500: train=1.300769, validation=1.468624
IP1 epoch   20/500: train=1.000285, validation=1.163541
IP1 epoch   30/500: train=0.851686, validation=1.025078
IP1 epoch   40/500: train=0.764630, validation=0.944080
IP1 epoch   50/500: train=0.983034, validation=1.179088
IP1 epoch   60/500: train=0.987613, validation=1.167680
IP1 epoch   70/500: train=0.522088, validation=0.740110
IP1 epoch   80/500: train=1.111243, validation=1.309758
IP1 epoch   90/500: train=1.034420, validation=1.259248
IP1 epoch  100/500: train=0.836782, validation=1.070292
IP1 epoch  110/500: train=0.930937, validation=1.180693
IP1 epoch  120/500: train=0.715230, validation=0.981656
IP1 epoch  130/500: train=1.255471, validation=1.504059
IP1 epoch  140/500: train=0.954952, validation=1.251529
IP1 epoch  150/500: train=1.179187, validation=1.454227
IP1 epoch  160/500: train=0.673517, validation=0.983739
IP1 epoch  170/500: train=1.180516, validation=1.458702
IP1 epoch  180/500: train=0.597930, validation=0.916780
IP1 epoch  190/500: train=1.307583, validation=1.596695
IP1 epoch  200/500: train=0.485293, validation=0.813728
IP1 epoch  210/500: train=0.469375, validation=0.803132
IP1 epoch  220/500: train=1.266643, validation=1.585412
IP1 epoch  230/500: train=0.702718, validation=1.041485
IP1 epoch  240/500: train=1.104956, validation=1.425692
IP1 epoch  250/500: train=1.016771, validation=1.344995
IP1 epoch  260/500: train=0.423432, validation=0.780451
IP1 epoch  270/500: train=0.671553, validation=1.030348
IP1 epoch  280/500: train=0.819252, validation=1.173296
IP1 epoch  290/500: train=0.814518, validation=1.158317
IP1 epoch  300/500: train=1.091978, validation=1.452903
IP1 epoch  310/500: train=1.217644, validation=1.545179
IP1 epoch  320/500: train=0.448584, validation=0.812735
IP1 epoch  330/500: train=1.165411, validation=1.507479
IP1 epoch  340/500: train=0.516660, validation=0.886082
IP1 epoch  350/500: train=0.639043, validation=1.000704
IP1 epoch  360/500: train=0.606844, validation=0.987103
IP1 epoch  370/500: train=0.715501, validation=1.083306
IP1 epoch  380/500: train=0.748842, validation=1.124887
IP1 epoch  390/500: train=0.328956, validation=0.718264
IP1 epoch  400/500: train=0.608203, validation=0.978739
IP1 epoch  410/500: train=0.779502, validation=1.151932
IP1 epoch  420/500: train=0.817526, validation=1.205538
IP1 epoch  430/500: train=0.317366, validation=0.706029
IP1 epoch  440/500: train=0.333042, validation=0.728572
IP1 epoch  450/500: train=0.500752, validation=0.891096
IP1 epoch  460/500: train=0.676607, validation=1.071623
IP1 epoch  470/500: train=0.565880, validation=0.946353
IP1 epoch  480/500: train=0.686755, validation=1.067230
IP1 epoch  490/500: train=0.349669, validation=0.738834
IP1 epoch  500/500: train=0.308006, validation=0.706454

          train_mse  validation_mse
scenario
SB1        0.000446        0.000573
SB2        0.000771        0.000911
BG1        0.000983        0.001006
BG2        0.000535        0.000606
IP1        0.308006        0.706454

In [7]:
tr_nn_config = NNSolverExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=X0,
    steps=NN_STEPS,
    lr=NN_LEARNING_RATE,
    save_every=NN_SAVE_EVERY,
    history_path=str(RESULTS_DIR / "NN_solver_tr_ablation_history.csv"),
    evaluate_true=True,
    save_results=True,
    model_tag="tr",
)
tr_nn_result = run_nn_solver_experiment(tr_nn_config)
tr_nn_prices = np.asarray(tr_nn_result["optimal pi"], dtype=float).reshape(
    len(SCENARIOS), T
)

print("TR-retrained NN history:", tr_nn_result["history_path"])
print("TR-retrained NN true objective:", tr_nn_result["true_obj"])
print("TR-retrained NN runtime (s):", tr_nn_result["runtime_seconds"])

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[0] loss=6010.2324, obj=-1.1225, eq=6.0042, soc=0.0647, bound=0.0646, true_loss=124.0954
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[200] loss=341.0348, obj=45.9639, eq=0.2893, soc=0.0547, bound=0.0314, true_loss=124.3325
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[400] loss=200.7602, obj=70.1113, eq=0.1278, soc=0.0273, bound=0.0104, true_loss=123.8919
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[600] loss=120.1092, obj=67.7509, eq=0.0511, soc=0.0119, bound=0.0027, true_loss=106.2284
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[800] loss=74.9716, obj=57.7603, eq=0.0168, soc=0.0040, bound=0.0009, true_loss=83.1272
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1000] loss=64.6736, obj=52.5278, eq=0.0118, soc=0.0030, bound=0.0003, true_loss=77.2309
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1200] loss=56.3723, obj=46.2537, eq=0.0099, soc=0.0025, bound=0.0001, true_loss=71.1080
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1400] loss=47.6190, obj=39.9241, eq=0.0075, soc=0.0020, bound=0.0001, true_loss=64.6778
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1600] loss=35.5123, obj=26.7723, eq=0.0085, soc=0.0023, bound=0.0001, true_loss=51.4777
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1800] loss=0.6608, obj=-8.3686, eq=0.0088, soc=0.0022, bound=0.0001, true_loss=15.8542
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2000] loss=-37.2675, obj=-45.5276, eq=0.0080, soc=0.0021, bound=0.0001, true_loss=-20.9500
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2200] loss=-69.4451, obj=-78.2050, eq=0.0085, soc=0.0022, bound=0.0001, true_loss=-53.6610
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2400] loss=-78.5868, obj=-87.2919, eq=0.0085, soc=0.0022, bound=0.0001, true_loss=-64.0117
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2600] loss=-80.6970, obj=-90.5208, eq=0.0096, soc=0.0021, bound=0.0001, true_loss=-67.6198
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2800] loss=-85.9440, obj=-93.2573, eq=0.0071, soc=0.0020, bound=0.0001, true_loss=-70.3225
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3000] loss=-88.1145, obj=-95.8695, eq=0.0076, soc=0.0020, bound=0.0001, true_loss=-72.3638
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3200] loss=-89.2809, obj=-98.1844, eq=0.0087, soc=0.0020, bound=0.0001, true_loss=-74.0304
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3400] loss=-91.7928, obj=-100.3080, eq=0.0083, soc=0.0020, bound=0.0001, true_loss=-76.0122
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3600] loss=-95.0615, obj=-102.6091, eq=0.0073, soc=0.0020, bound=0.0001, true_loss=-78.1026
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3800] loss=-97.7829, obj=-105.0487, eq=0.0071, soc=0.0020, bound=0.0001, true_loss=-79.7493
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4000] loss=-99.7611, obj=-107.2207, eq=0.0073, soc=0.0020, bound=0.0001, true_loss=-81.4600
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4200] loss=-100.9157, obj=-108.8301, eq=0.0077, soc=0.0020, bound=0.0001, true_loss=-82.7393
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4400] loss=-102.6605, obj=-110.3794, eq=0.0075, soc=0.0020, bound=0.0001, true_loss=-83.3877
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4600] loss=-104.2287, obj=-111.6452, eq=0.0072, soc=0.0020, bound=0.0001, true_loss=-84.3380
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4800] loss=-104.9060, obj=-112.6867, eq=0.0076, soc=0.0020, bound=0.0001, true_loss=-85.1698
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5000] loss=-106.0132, obj=-113.5392, eq=0.0073, soc=0.0020, bound=0.0001, true_loss=-85.4016
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5200] loss=-106.6639, obj=-114.2012, eq=0.0073, soc=0.0020, bound=0.0001, true_loss=-86.0401
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026

## 4. Generate an equal-size global-random control dataset

For each follower instance, prices are drawn independently and uniformly from $[0,1.5]^{24}$. The requested sample count is the actual number of unique trust-region rows exported for that same instance. Existing `_new` arrays are never loaded or reused.

In [8]:
def generate_fresh_random_samples(
    scenario,
    n_samples,
    *,
    seed,
    checkpoint_interval=100,
    max_consecutive_failures=20,
):
    """Generate a fresh deterministic `_new` dataset for one instance."""
    if n_samples <= 0:
        raise ValueError("n_samples must be positive.")

    set_global_seed(seed)
    rng = make_rng(seed)
    solver_options = {
        **INSTANCE_SOLVER_KWARGS[scenario],
        "failure_mode": "none",
        "include_metadata": True,
        "time_limit": LOWER_TIME_LIMIT,
        "mip_gap": LOWER_MIP_GAP,
    }
    lower_solver = follower_solver.build_solver(
        INSTANCE_TYPES[scenario],
        T=T,
        net=INSTANCE_NETWORKS[scenario],
        **solver_options,
    )

    x_path = DATA_DIR / f"X_{scenario}_new.npy"
    y_path = DATA_DIR / f"Y_{scenario}_new.npy"
    x_data = np.empty((n_samples, T), dtype=float)
    y_data = np.empty((n_samples, T), dtype=float)
    completed = 0
    attempts = 0
    failures = 0
    consecutive_failures = 0
    checkpoint_start = time.time()

    print(f"{scenario}: generating {n_samples} fresh samples (seed={seed}).")
    while completed < n_samples:
        attempts += 1
        price = rng.uniform(0.0, 1.5, size=T)
        result = lower_solver.lower_solve(price)
        if result is None:
            failures += 1
            consecutive_failures += 1
            print(
                f"{scenario}: skipped failed attempt {attempts}; "
                f"collected {completed}/{n_samples}."
            )
            if consecutive_failures >= max_consecutive_failures:
                raise RuntimeError(
                    f"{scenario}: stopped after {consecutive_failures} "
                    "consecutive lower-level failures."
                )
            continue

        consecutive_failures = 0
        response = np.asarray(result["p_mg"], dtype=float).reshape(T)
        if not np.isfinite(response).all():
            raise ValueError(f"{scenario}: follower returned a non-finite response.")
        x_data[completed] = price
        y_data[completed] = response
        completed += 1

        if completed % checkpoint_interval == 0 or completed == n_samples:
            atomic_save_npy(x_path, x_data[:completed])
            atomic_save_npy(y_path, y_data[:completed])
            elapsed = time.time() - checkpoint_start
            print(
                f"{scenario}: saved {completed}/{n_samples} fresh samples "
                f"({failures} failed attempts, {elapsed:.1f} s)."
            )
            checkpoint_start = time.time()

    return x_data, y_data

In [9]:
new_data = {}
for scenario in SCENARIOS:
    new_data[scenario] = generate_fresh_random_samples(
        scenario,
        tr_sample_counts[scenario],
        seed=NEW_DATA_SEEDS[scenario],
        checkpoint_interval=NEW_DATA_CHECKPOINT_INTERVAL,
    )

sample_rows = []
for scenario in SCENARIOS:
    original_x, _ = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}.npy",
        DATA_DIR / f"Y_{scenario}.npy",
    )
    tr_x, _ = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_tr.npy",
        DATA_DIR / f"Y_{scenario}_tr.npy",
    )
    new_x, _ = load_aligned_arrays(
        DATA_DIR / f"X_{scenario}_new.npy",
        DATA_DIR / f"Y_{scenario}_new.npy",
        expected_rows=len(tr_x),
    )
    if len(new_x) != len(tr_x):
        raise AssertionError(
            f"{scenario}: new sample count {len(new_x)} != TR count {len(tr_x)}."
        )
    sample_rows.append(
        {
            "scenario": scenario,
            "original_samples": len(original_x),
            "trust_region_samples": len(tr_x),
            "new_random_samples": len(new_x),
            "tr_combined_samples": len(original_x) + len(tr_x),
            "new_combined_samples": len(original_x) + len(new_x),
        }
    )

sample_count_table = pd.DataFrame(sample_rows).set_index("scenario")
if not (
    sample_count_table["trust_region_samples"]
    == sample_count_table["new_random_samples"]
).all():
    raise AssertionError("Random and trust-region sample counts must match.")
display(sample_count_table)

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

SB1: generating 2748 fresh samples (seed=4201).
SB1: saved 100/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 200/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 300/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 400/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 500/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 600/2748 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 700/2748 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 800/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 900/2748 fresh samples (0 failed attempts, 1.5 s).
SB1: saved 1000/2748 fresh samples (0 failed attempts, 1.6 s).
SB1: saved 1100/2748 fresh samples (0 failed attempts, 2.1 s).
SB1: saved 1200/2748 fresh samples (0 failed attempts, 1.9 s).
SB1: saved 1300/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 1400/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 1500/2748 fresh samples (0 failed attempts, 2.1 s).
SB1: saved 1600/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 1700/2748 fresh samples (0 failed attempts, 2.0 s).
SB1: saved 1800/2748 fresh samples (0 failed attempts, 2.0 s).
SB1: saved 1900/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 2000/2748 fresh samples (0 failed attempts, 1.9 s).
SB1: saved 2100/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 2200/2748 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 2300/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 2400/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 2500/2748 fresh samples (0 failed attempts, 2.0 s).
SB1: saved 2600/2748 fresh samples (0 failed attempts, 1.8 s).
SB1: saved 2700/2748 fresh samples (0 failed attempts, 1.7 s).
SB1: saved 2748/2748 fresh samples (0 failed attempts, 0.8 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

SB2: generating 2752 fresh samples (seed=4202).
SB2: saved 100/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 200/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 300/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 400/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 500/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 600/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 700/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 800/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 900/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 1000/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 1100/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 1200/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 1300/2752 fresh samples (0 failed attempts, 1.8 s).
SB2: saved 1400/2752 fresh samples (0 failed attempts, 2.0 s).
SB2: saved 1500/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 1600/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 1700/2752 fresh samples (0 failed attempts, 2.0 s).
SB2: saved 1800/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 1900/2752 fresh samples (0 failed attempts, 2.1 s).
SB2: saved 2000/2752 fresh samples (0 failed attempts, 2.3 s).
SB2: saved 2100/2752 fresh samples (0 failed attempts, 1.9 s).
SB2: saved 2200/2752 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 2300/2752 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 2400/2752 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 2500/2752 fresh samples (0 failed attempts, 1.6 s).
SB2: saved 2600/2752 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 2700/2752 fresh samples (0 failed attempts, 1.7 s).
SB2: saved 2752/2752 fresh samples (0 failed attempts, 0.9 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

BG1: generating 2646 fresh samples (seed=4203).
BG1: saved 100/2646 fresh samples (0 failed attempts, 9.2 s).
BG1: saved 200/2646 fresh samples (0 failed attempts, 9.9 s).
BG1: saved 300/2646 fresh samples (0 failed attempts, 10.3 s).
BG1: saved 400/2646 fresh samples (0 failed attempts, 11.2 s).
BG1: saved 500/2646 fresh samples (0 failed attempts, 11.5 s).
BG1: saved 600/2646 fresh samples (0 failed attempts, 12.0 s).
BG1: saved 700/2646 fresh samples (0 failed attempts, 12.6 s).
BG1: saved 800/2646 fresh samples (0 failed attempts, 13.2 s).
BG1: saved 900/2646 fresh samples (0 failed attempts, 13.9 s).
BG1: saved 1000/2646 fresh samples (0 failed attempts, 14.4 s).
BG1: saved 1100/2646 fresh samples (0 failed attempts, 15.4 s).
BG1: saved 1200/2646 fresh samples (0 failed attempts, 15.2 s).
BG1: saved 1300/2646 fresh samples (0 failed attempts, 15.7 s).
BG1: saved 1400/2646 fresh samples (0 failed attempts, 16.6 s).
BG1: saved 1500/2646 fresh samples (0 failed attempts, 16.8 s).
BG1: saved 1600/2646 fresh samples (0 failed attempts, 17.3 s).
BG1: saved 1700/2646 fresh samples (0 failed attempts, 18.7 s).
BG1: saved 1800/2646 fresh samples (0 failed attempts, 19.3 s).
BG1: saved 1900/2646 fresh samples (0 failed attempts, 19.9 s).
BG1: saved 2000/2646 fresh samples (0 failed attempts, 20.1 s).
BG1: saved 2100/2646 fresh samples (0 failed attempts, 21.1 s).
BG1: saved 2200/2646 fresh samples (0 failed attempts, 21.0 s).
BG1: saved 2300/2646 fresh samples (0 failed attempts, 21.7 s).
BG1: saved 2400/2646 fresh samples (0 failed attempts, 22.5 s).
BG1: saved 2500/2646 fresh samples (0 failed attempts, 22.5 s).
BG1: saved 2600/2646 fresh samples (0 failed attempts, 23.1 s).
BG1: saved 2646/2646 fresh samples (0 failed attempts, 10.8 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

BG2: generating 1304 fresh samples (seed=4204).
BG2: saved 100/1304 fresh samples (0 failed attempts, 9.7 s).
BG2: saved 200/1304 fresh samples (0 failed attempts, 10.6 s).
BG2: saved 300/1304 fresh samples (0 failed attempts, 11.2 s).
BG2: saved 400/1304 fresh samples (0 failed attempts, 11.6 s).
BG2: saved 500/1304 fresh samples (0 failed attempts, 12.2 s).
BG2: saved 600/1304 fresh samples (0 failed attempts, 12.6 s).
BG2: saved 700/1304 fresh samples (0 failed attempts, 13.1 s).
BG2: saved 800/1304 fresh samples (0 failed attempts, 13.6 s).
BG2: saved 900/1304 fresh samples (0 failed attempts, 14.0 s).
BG2: saved 1000/1304 fresh samples (0 failed attempts, 14.9 s).
BG2: saved 1100/1304 fresh samples (0 failed attempts, 15.5 s).
BG2: saved 1200/1304 fresh samples (0 failed attempts, 16.3 s).
BG2: saved 1300/1304 fresh samples (0 failed attempts, 16.8 s).
BG2: saved 1304/1304 fresh samples (0 failed attempts, 0.7 s).
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

IP1: generating 2682 fresh samples (seed=4205).
IP1: saved 100/2682 fresh samples (0 failed attempts, 74.2 s).
IP1: saved 200/2682 fresh samples (0 failed attempts, 76.4 s).
IP1: saved 300/2682 fresh samples (0 failed attempts, 81.8 s).
IP1: saved 400/2682 fresh samples (0 failed attempts, 82.1 s).
IP1: saved 500/2682 fresh samples (0 failed attempts, 76.8 s).
IP1: saved 600/2682 fresh samples (0 failed attempts, 77.0 s).
IP1: saved 700/2682 fresh samples (0 failed attempts, 83.2 s).
IP1: saved 800/2682 fresh samples (0 failed attempts, 76.3 s).
IP1: saved 900/2682 fresh samples (0 failed attempts, 78.7 s).
IP1: saved 1000/2682 fresh samples (0 failed attempts, 78.6 s).
IP1: saved 1100/2682 fresh samples (0 failed attempts, 77.1 s).
IP1: saved 1200/2682 fresh samples (0 failed attempts, 71.4 s).
IP1: saved 1300/2682 fresh samples (0 failed attempts, 80.6 s).
IP1: saved 1400/2682 fresh samples (0 failed attempts, 79.0 s).
IP1: saved 1500/2682 fresh samples (0 failed attempts, 77.3 s).
IP1: saved 1600/2682 fresh samples (0 failed attempts, 84.2 s).
IP1: saved 1700/2682 fresh samples (0 failed attempts, 80.3 s).
IP1: saved 1800/2682 fresh samples (0 failed attempts, 77.0 s).
IP1: saved 1900/2682 fresh samples (0 failed attempts, 82.4 s).
IP1: saved 2000/2682 fresh samples (0 failed attempts, 82.2 s).
IP1: saved 2100/2682 fresh samples (0 failed attempts, 79.3 s).
IP1: saved 2200/2682 fresh samples (0 failed attempts, 79.9 s).
IP1: saved 2300/2682 fresh samples (0 failed attempts, 79.2 s).
IP1: saved 2400/2682 fresh samples (0 failed attempts, 78.4 s).
IP1: saved 2500/2682 fresh samples (0 failed attempts, 87.5 s).
IP1: saved 2600/2682 fresh samples (0 failed attempts, 78.5 s).
IP1: saved 2682/2682 fresh samples (0 failed attempts, 65.0 s).

,original_samples,trust_region_samples,new_random_samples,tr_combined_samples,new_combined_samples
scenario,,,,,
SB1,10000,2748,2748,12748,12748
SB2,10000,2752,2752,12752,12752
BG1,10000,2646,2646,12646,12646
BG2,10000,1304,1304,11304,11304
IP1,10000,2682,2682,12682,12682

## 5. Retrain global models on original + equal-size random samples

Training writes `L2O_XX_new.pth/.json`, then the NN solver uses the same initial point and optimization budget as the other NN runs.

In [10]:
new_training_results = {}
for scenario in SCENARIOS:
    print(f"\nTraining {scenario} on original + equal-size global random samples")
    new_training_results[scenario] = train(
        scenario,
        config=training_config(scenario),
        data_tag="new",
        model_tag="new",
        include_original=True,
    )
    for suffix in (".pth", ".json"):
        expected_model = MODEL_DIR / f"L2O_{scenario}_new{suffix}"
        if not expected_model.is_file():
            raise FileNotFoundError(expected_model)

display(pd.DataFrame(new_training_results).T.rename_axis("scenario"))

Training SB1 on original + equal-size global random samples
SB1: concatenated original 10000 + new 2748 samples -> 12748
SB1 epoch   10/500: train=0.051246, validation=0.054013
SB1 epoch   20/500: train=0.033283, validation=0.035212
SB1 epoch   30/500: train=0.029868, validation=0.031879
SB1 epoch   40/500: train=0.020561, validation=0.022394
SB1 epoch   50/500: train=0.014672, validation=0.016130
SB1 epoch   60/500: train=0.011569, validation=0.012882
SB1 epoch   70/500: train=0.009107, validation=0.010411
SB1 epoch   80/500: train=0.007440, validation=0.008509
SB1 epoch   90/500: train=0.005540, validation=0.006441
SB1 epoch  100/500: train=0.004721, validation=0.005567
SB1 epoch  110/500: train=0.003828, validation=0.004506
SB1 epoch  120/500: train=0.002984, validation=0.003628
SB1 epoch  130/500: train=0.002445, validation=0.002980
SB1 epoch  140/500: train=0.002200, validation=0.002663
SB1 epoch  150/500: train=0.002326, validation=0.002755
SB1 epoch  160/500: train=0.001827, validation=0.002275
SB1 epoch  170/500: train=0.001644, validation=0.002023
SB1 epoch  180/500: train=0.001612, validation=0.001978
SB1 epoch  190/500: train=0.001533, validation=0.001898
SB1 epoch  200/500: train=0.001443, validation=0.001706
SB1 epoch  210/500: train=0.001246, validation=0.001526
SB1 epoch  220/500: train=0.001159, validation=0.001419
SB1 epoch  230/500: train=0.001173, validation=0.001411
SB1 epoch  240/500: train=0.001118, validation=0.001337
SB1 epoch  250/500: train=0.000881, validation=0.001104
SB1 epoch  260/500: train=0.000873, validation=0.001067
SB1 epoch  270/500: train=0.000824, validation=0.000980
SB1 epoch  280/500: train=0.000885, validation=0.001055
SB1 epoch  290/500: train=0.000730, validation=0.000875
SB1 epoch  300/500: train=0.000712, validation=0.000822
SB1 epoch  310/500: train=0.000807, validation=0.000923
SB1 epoch  320/500: train=0.000681, validation=0.000779
SB1 epoch  330/500: train=0.000688, validation=0.000816
SB1 epoch  340/500: train=0.000635, validation=0.000726
SB1 epoch  350/500: train=0.000645, validation=0.000731
SB1 epoch  360/500: train=0.000567, validation=0.000654
SB1 epoch  370/500: train=0.000557, validation=0.000637
SB1 epoch  380/500: train=0.000685, validation=0.000752
SB1 epoch  390/500: train=0.000565, validation=0.000623
SB1 epoch  400/500: train=0.000508, validation=0.000565
SB1 epoch  410/500: train=0.000493, validation=0.000546
SB1 epoch  420/500: train=0.000521, validation=0.000597
SB1 epoch  430/500: train=0.000489, validation=0.000562
SB1 epoch  440/500: train=0.000463, validation=0.000524
SB1 epoch  450/500: train=0.000403, validation=0.000465
SB1 epoch  460/500: train=0.000510, validation=0.000599
SB1 epoch  470/500: train=0.000485, validation=0.000543
SB1 epoch  480/500: train=0.000428, validation=0.000519
SB1 epoch  490/500: train=0.000460, validation=0.000517
SB1 epoch  500/500: train=0.000387, validation=0.000444

Training SB2 on original + equal-size global random samples
SB2: concatenated original 10000 + new 2752 samples -> 12752
SB2 epoch   10/500: train=0.053939, validation=0.055244
SB2 epoch   20/500: train=0.042309, validation=0.043403
SB2 epoch   30/500: train=0.032420, validation=0.034151
SB2 epoch   40/500: train=0.022852, validation=0.023933
SB2 epoch   50/500: train=0.016868, validation=0.017852
SB2 epoch   60/500: train=0.012992, validation=0.013934
SB2 epoch   70/500: train=0.009850, validation=0.010860
SB2 epoch   80/500: train=0.007982, validation=0.008821
SB2 epoch   90/500: train=0.006271, validation=0.006999
SB2 epoch  100/500: train=0.005032, validation=0.005799
SB2 epoch  110/500: train=0.004104, validation=0.004725
SB2 epoch  120/500: train=0.003629, validation=0.004138
SB2 epoch  130/500: train=0.002963, validation=0.003455
SB2 epoch  140/500: train=0.002413, validation=0.002882
SB2 epoch  150/500: train=0.002268, validation=0.002740
SB2 epoch  160/500: train=0.002089, validation=0.002544
SB2 epoch  170/500: train=0.001983, validation=0.002441
SB2 epoch  180/500: train=0.001698, validation=0.002140
SB2 epoch  190/500: train=0.001708, validation=0.002186
SB2 epoch  200/500: train=0.001750, validation=0.002185
SB2 epoch  210/500: train=0.001528, validation=0.001931
SB2 epoch  220/500: train=0.001327, validation=0.001680
SB2 epoch  230/500: train=0.001505, validation=0.001811
SB2 epoch  240/500: train=0.001322, validation=0.001651
SB2 epoch  250/500: train=0.001348, validation=0.001687
SB2 epoch  260/500: train=0.001184, validation=0.001507
SB2 epoch  270/500: train=0.001107, validation=0.001397
SB2 epoch  280/500: train=0.000880, validation=0.001105
SB2 epoch  290/500: train=0.000933, validation=0.001155
SB2 epoch  300/500: train=0.001039, validation=0.001244
SB2 epoch  310/500: train=0.000749, validation=0.000959
SB2 epoch  320/500: train=0.000811, validation=0.000988
SB2 epoch  330/500: train=0.000789, validation=0.000967
SB2 epoch  340/500: train=0.000847, validation=0.001004
SB2 epoch  350/500: train=0.000851, validation=0.001021
SB2 epoch  360/500: train=0.000727, validation=0.000891
SB2 epoch  370/500: train=0.000600, validation=0.000764
SB2 epoch  380/500: train=0.000708, validation=0.000827
SB2 epoch  390/500: train=0.001224, validation=0.001354
SB2 epoch  400/500: train=0.000607, validation=0.000730
SB2 epoch  410/500: train=0.000705, validation=0.000814
SB2 epoch  420/500: train=0.000716, validation=0.000842
SB2 epoch  430/500: train=0.000528, validation=0.000642
SB2 epoch  440/500: train=0.000570, validation=0.000675
SB2 epoch  450/500: train=0.000565, validation=0.000623
SB2 epoch  460/500: train=0.000597, validation=0.000656
SB2 epoch  470/500: train=0.000498, validation=0.000576
SB2 epoch  480/500: train=0.000590, validation=0.000618
SB2 epoch  490/500: train=0.000852, validation=0.000926
SB2 epoch  500/500: train=0.000450, validation=0.000521

Training BG1 on original + equal-size global random samples
BG1: concatenated original 10000 + new 2646 samples -> 12646
BG1 epoch   10/500: train=0.023594, validation=0.024059
BG1 epoch   20/500: train=0.021878, validation=0.021592
BG1 epoch   30/500: train=0.014780, validation=0.014411
BG1 epoch   40/500: train=0.009786, validation=0.009662
BG1 epoch   50/500: train=0.007935, validation=0.007892
BG1 epoch   60/500: train=0.004272, validation=0.004329
BG1 epoch   70/500: train=0.003520, validation=0.003565
BG1 epoch   80/500: train=0.003312, validation=0.003368
BG1 epoch   90/500: train=0.003025, validation=0.003100
BG1 epoch  100/500: train=0.005314, validation=0.005385
BG1 epoch  110/500: train=0.001786, validation=0.001848
BG1 epoch  120/500: train=0.001593, validation=0.001613
BG1 epoch  130/500: train=0.001346, validation=0.001364
BG1 epoch  140/500: train=0.001185, validation=0.001215
BG1 epoch  150/500: train=0.001197, validation=0.001231
BG1 epoch  160/500: train=0.001229, validation=0.001250
BG1 epoch  170/500: train=0.001006, validation=0.001045
BG1 epoch  180/500: train=0.000962, validation=0.001002
BG1 epoch  190/500: train=0.000915, validation=0.000942
BG1 epoch  200/500: train=0.000939, validation=0.000969
BG1 epoch  210/500: train=0.000948, validation=0.000987
BG1 epoch  220/500: train=0.000928, validation=0.000966
BG1 epoch  230/500: train=0.000813, validation=0.000842
BG1 epoch  240/500: train=0.000806, validation=0.000833
BG1 epoch  250/500: train=0.000806, validation=0.000839
BG1 epoch  260/500: train=0.002486, validation=0.002523
BG1 epoch  270/500: train=0.000753, validation=0.000784
BG1 epoch  280/500: train=0.000991, validation=0.001029
BG1 epoch  290/500: train=0.000811, validation=0.000846
BG1 epoch  300/500: train=0.000807, validation=0.000842
BG1 epoch  310/500: train=0.000976, validation=0.001011
BG1 epoch  320/500: train=0.000943, validation=0.000986
BG1 epoch  330/500: train=0.000861, validation=0.000897
BG1 epoch  340/500: train=0.000915, validation=0.000946
BG1 epoch  350/500: train=0.000719, validation=0.000751
BG1 epoch  360/500: train=0.000844, validation=0.000874
BG1 epoch  370/500: train=0.000710, validation=0.000749
BG1 epoch  380/500: train=0.000855, validation=0.000874
BG1 epoch  390/500: train=0.000665, validation=0.000700
BG1 epoch  400/500: train=0.000703, validation=0.000734
BG1 epoch  410/500: train=0.000795, validation=0.000820
BG1 epoch  420/500: train=0.000716, validation=0.000746
BG1 epoch  430/500: train=0.000690, validation=0.000718
BG1 epoch  440/500: train=0.000709, validation=0.000738
BG1 epoch  450/500: train=0.000733, validation=0.000764
BG1 epoch  460/500: train=0.000933, validation=0.000959
BG1 epoch  470/500: train=0.000784, validation=0.000821
BG1 epoch  480/500: train=0.000752, validation=0.000778
BG1 epoch  490/500: train=0.000704, validation=0.000743
BG1 epoch  500/500: train=0.000919, validation=0.000945

Training BG2 on original + equal-size global random samples
BG2: concatenated original 10000 + new 1304 samples -> 11304
BG2 epoch   10/500: train=0.021358, validation=0.021906
BG2 epoch   20/500: train=0.009749, validation=0.009924
BG2 epoch   30/500: train=0.009078, validation=0.009176
BG2 epoch   40/500: train=0.006666, validation=0.006712
BG2 epoch   50/500: train=0.004195, validation=0.004303
BG2 epoch   60/500: train=0.003732, validation=0.003839
BG2 epoch   70/500: train=0.003424, validation=0.003513
BG2 epoch   80/500: train=0.003064, validation=0.003163
BG2 epoch   90/500: train=0.002169, validation=0.002321
BG2 epoch  100/500: train=0.002070, validation=0.002241
BG2 epoch  110/500: train=0.001943, validation=0.002131
BG2 epoch  120/500: train=0.001810, validation=0.002013
BG2 epoch  130/500: train=0.001654, validation=0.001857
BG2 epoch  140/500: train=0.001494, validation=0.001661
BG2 epoch  150/500: train=0.001463, validation=0.001582
BG2 epoch  160/500: train=0.001160, validation=0.001279
BG2 epoch  170/500: train=0.001052, validation=0.001165
BG2 epoch  180/500: train=0.000897, validation=0.000982
BG2 epoch  190/500: train=0.000805, validation=0.000893
BG2 epoch  200/500: train=0.000737, validation=0.000811
BG2 epoch  210/500: train=0.000696, validation=0.000772
BG2 epoch  220/500: train=0.000637, validation=0.000714
BG2 epoch  230/500: train=0.000653, validation=0.000717
BG2 epoch  240/500: train=0.000608, validation=0.000683
BG2 epoch  250/500: train=0.000612, validation=0.000683
BG2 epoch  260/500: train=0.000568, validation=0.000647
BG2 epoch  270/500: train=0.000639, validation=0.000708
BG2 epoch  280/500: train=0.000566, validation=0.000653
BG2 epoch  290/500: train=0.000581, validation=0.000659
BG2 epoch  300/500: train=0.000581, validation=0.000662
BG2 epoch  310/500: train=0.000551, validation=0.000632
BG2 epoch  320/500: train=0.000514, validation=0.000599
BG2 epoch  330/500: train=0.000530, validation=0.000619
BG2 epoch  340/500: train=0.000498, validation=0.000592
BG2 epoch  350/500: train=0.000562, validation=0.000650
BG2 epoch  360/500: train=0.000486, validation=0.000577
BG2 epoch  370/500: train=0.000522, validation=0.000612
BG2 epoch  380/500: train=0.000461, validation=0.000557
BG2 epoch  390/500: train=0.000464, validation=0.000563
BG2 epoch  400/500: train=0.000470, validation=0.000562
BG2 epoch  410/500: train=0.000485, validation=0.000577
BG2 epoch  420/500: train=0.000454, validation=0.000551
BG2 epoch  430/500: train=0.000446, validation=0.000544
BG2 epoch  440/500: train=0.000460, validation=0.000556
BG2 epoch  450/500: train=0.000440, validation=0.000542
BG2 epoch  460/500: train=0.000456, validation=0.000555
BG2 epoch  470/500: train=0.000431, validation=0.000524
BG2 epoch  480/500: train=0.000462, validation=0.000550
BG2 epoch  490/500: train=0.000418, validation=0.000514
BG2 epoch  500/500: train=0.000440, validation=0.000538

Training IP1 on original + equal-size global random samples
IP1: concatenated original 10000 + new 2682 samples -> 12682
IP1 epoch   10/500: train=1.447279, validation=1.732840
IP1 epoch   20/500: train=1.121661, validation=1.408433
IP1 epoch   30/500: train=0.895862, validation=1.169069
IP1 epoch   40/500: train=0.758012, validation=1.039286
IP1 epoch   50/500: train=0.696695, validation=0.979471
IP1 epoch   60/500: train=0.597663, validation=0.890198
IP1 epoch   70/500: train=0.545716, validation=0.843111
IP1 epoch   80/500: train=0.526479, validation=0.845287
IP1 epoch   90/500: train=0.492276, validation=0.805961
IP1 epoch  100/500: train=0.466534, validation=0.796176
IP1 epoch  110/500: train=0.440494, validation=0.783081
IP1 epoch  120/500: train=0.417742, validation=0.763860
IP1 epoch  130/500: train=0.402363, validation=0.764364
IP1 epoch  140/500: train=0.391699, validation=0.764982
IP1 epoch  150/500: train=0.373269, validation=0.746831
IP1 epoch  160/500: train=0.362223, validation=0.740611
IP1 epoch  170/500: train=0.355757, validation=0.742247
IP1 epoch  180/500: train=0.345425, validation=0.736969
IP1 epoch  190/500: train=0.336527, validation=0.725385
IP1 epoch  200/500: train=0.328678, validation=0.731275
IP1 epoch  210/500: train=0.318008, validation=0.716182
IP1 epoch  220/500: train=0.306195, validation=0.716059
IP1 epoch  230/500: train=0.303408, validation=0.713723
IP1 epoch  240/500: train=0.300494, validation=0.706556
IP1 epoch  250/500: train=0.291880, validation=0.718994
IP1 epoch  260/500: train=0.292788, validation=0.709276
IP1 epoch  270/500: train=0.281221, validation=0.701933
IP1 epoch  280/500: train=0.284188, validation=0.705502
IP1 epoch  290/500: train=0.274464, validation=0.698376
IP1 epoch  300/500: train=0.270358, validation=0.700796
IP1 epoch  310/500: train=0.266393, validation=0.695431
IP1 epoch  320/500: train=0.269758, validation=0.695901
IP1 epoch  330/500: train=0.262041, validation=0.694034
IP1 epoch  340/500: train=0.261646, validation=0.690440
IP1 epoch  350/500: train=0.256807, validation=0.692244
IP1 epoch  360/500: train=0.254272, validation=0.694241
IP1 epoch  370/500: train=0.245147, validation=0.686837
IP1 epoch  380/500: train=0.248247, validation=0.697016
IP1 epoch  390/500: train=0.251608, validation=0.695883
IP1 epoch  400/500: train=0.255929, validation=0.695795
IP1 epoch  410/500: train=0.240240, validation=0.689172
IP1 epoch  420/500: train=0.236400, validation=0.686257
IP1 epoch  430/500: train=0.236356, validation=0.687194
IP1 epoch  440/500: train=0.237154, validation=0.691342
IP1 epoch  450/500: train=0.234101, validation=0.677987
IP1 epoch  460/500: train=0.234256, validation=0.688963
IP1 epoch  470/500: train=0.237465, validation=0.690820
IP1 epoch  480/500: train=0.222233, validation=0.679173
IP1 epoch  490/500: train=0.231687, validation=0.685482
IP1 epoch  500/500: train=0.225030, validation=0.687536

          train_mse  validation_mse
scenario
SB1        0.000387        0.000444
SB2        0.000450        0.000521
BG1        0.000919        0.000945
BG2        0.000440        0.000538
IP1        0.225030        0.687536

In [11]:
new_nn_config = NNSolverExperimentConfig(
    upper_net=UPPER_NET,
    lower_nets=LOWER_NETS,
    mg_buses=MG_BUSES,
    scenarios=SCENARIOS,
    T=T,
    seed=SEED,
    device="cpu",
    x0=X0,
    steps=NN_STEPS,
    lr=NN_LEARNING_RATE,
    save_every=NN_SAVE_EVERY,
    history_path=str(RESULTS_DIR / "NN_solver_new_ablation_history.csv"),
    evaluate_true=True,
    save_results=True,
    model_tag="new",
)
new_nn_result = run_nn_solver_experiment(new_nn_config)
new_nn_prices = np.asarray(new_nn_result["optimal pi"], dtype=float).reshape(
    len(SCENARIOS), T
)

print("Random-retrained NN history:", new_nn_result["history_path"])
print("Random-retrained NN true objective:", new_nn_result["true_obj"])
print("Random-retrained NN runtime (s):", new_nn_result["runtime_seconds"])

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[0] loss=6010.6826, obj=-1.1225, eq=6.0047, soc=0.0647, bound=0.0646, true_loss=124.0227
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[200] loss=344.0622, obj=46.1120, eq=0.2922, soc=0.0541, bound=0.0322, true_loss=119.8398
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[400] loss=203.9350, obj=70.5633, eq=0.1305, soc=0.0272, bound=0.0103, true_loss=120.6218
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[600] loss=126.8393, obj=72.9153, eq=0.0527, soc=0.0124, bound=0.0029, true_loss=108.3887
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[800] loss=91.1570, obj=68.4977, eq=0.0221, soc=0.0056, bound=0.0007, true_loss=91.0206
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1000] loss=74.7753, obj=62.3103, eq=0.0121, soc=0.0032, bound=0.0002, true_loss=79.7371
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1200] loss=62.8145, obj=53.1130, eq=0.0094, soc=0.0025, bound=0.0001, true_loss=69.4091
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1400] loss=48.6857, obj=41.0768, eq=0.0074, soc=0.0019, bound=0.0001, true_loss=55.9618
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1600] loss=38.9458, obj=31.1098, eq=0.0077, soc=0.0018, bound=0.0001, true_loss=45.2012
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[1800] loss=25.5627, obj=18.6409, eq=0.0067, soc=0.0018, bound=0.0001, true_loss=30.8461
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2000] loss=0.1883, obj=-7.3106, eq=0.0073, soc=0.0018, bound=0.0001, true_loss=5.2821
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2200] loss=-25.1552, obj=-32.3068, eq=0.0070, soc=0.0018, bound=0.0001, true_loss=-19.9433
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2400] loss=-48.9845, obj=-56.7826, eq=0.0076, soc=0.0019, bound=0.0001, true_loss=-42.2009
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2600] loss=-65.8369, obj=-73.3904, eq=0.0074, soc=0.0018, bound=0.0001, true_loss=-60.8541
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[2800] loss=-78.0283, obj=-85.3396, eq=0.0071, soc=0.0019, bound=0.0001, true_loss=-72.7509
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3000] loss=-84.8660, obj=-93.1236, eq=0.0081, soc=0.0019, bound=0.0001, true_loss=-79.9550
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3200] loss=-90.5641, obj=-98.5247, eq=0.0078, soc=0.0019, bound=0.0001, true_loss=-85.0319
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3400] loss=-94.7721, obj=-102.2045, eq=0.0072, soc=0.0019, bound=0.0001, true_loss=-88.2353
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3600] loss=-97.2951, obj=-104.7372, eq=0.0073, soc=0.0019, bound=0.0001, true_loss=-90.9338
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[3800] loss=-99.3113, obj=-106.6200, eq=0.0071, soc=0.0018, bound=0.0001, true_loss=-92.6419
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4000] loss=-100.8982, obj=-108.0596, eq=0.0070, soc=0.0018, bound=0.0001, true_loss=-93.9363
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4200] loss=-101.7302, obj=-109.1462, eq=0.0072, soc=0.0019, bound=0.0001, true_loss=-94.7360
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4400] loss=-102.5797, obj=-109.9895, eq=0.0072, soc=0.0019, bound=0.0001, true_loss=-95.6735
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4600] loss=-103.0657, obj=-110.6365, eq=0.0074, soc=0.0019, bound=0.0001, true_loss=-96.3917
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[4800] loss=-104.2481, obj=-111.1659, eq=0.0067, soc=0.0018, bound=0.0001, true_loss=-96.6653
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5000] loss=-104.4634, obj=-111.5931, eq=0.0069, soc=0.0019, bound=0.0001, true_loss=-97.4602
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

[5200] loss=-105.0365, obj=-111.9474, eq=0.0067, soc=0.0018, bound=0.0001, true_loss=-97.6769
Cardinal Optimizer v8.0.6. Build date Aug  7 2026
Copyright Cardinal Operations 2026. All Rights Reserved

Cardinal Optimizer v8.0.6. Build date Aug  7 2026

## 6. Four-way solution and high-fidelity objective comparison

Lower true objective values are better. The key ablation comparison is between the two equally sized augmented training sets.

In [12]:
tr_saved_paths = tr_result.get("saved_paths", {})
comparison = pd.DataFrame(
    [
        {
            "method": "Original NN",
            "true_objective": float(original_nn_result["true_obj"]),
            "runtime_seconds": float(original_nn_result["runtime_seconds"]),
            "iterations": NN_STEPS,
            "composite_queries": np.nan,
            "history_or_result_path": original_nn_result["history_path"],
        },
        {
            "method": "Trust region",
            "true_objective": tr_objective,
            "runtime_seconds": float(tr_result["elapsed_seconds"]),
            "iterations": int(tr_result["n_iter"]),
            "composite_queries": tr_composite_queries,
            "history_or_result_path": tr_saved_paths.get("json"),
        },
        {
            "method": "NN: original + TR samples",
            "true_objective": float(tr_nn_result["true_obj"]),
            "runtime_seconds": float(tr_nn_result["runtime_seconds"]),
            "iterations": NN_STEPS,
            "composite_queries": np.nan,
            "history_or_result_path": tr_nn_result["history_path"],
        },
        {
            "method": "NN: original + equal global random samples",
            "true_objective": float(new_nn_result["true_obj"]),
            "runtime_seconds": float(new_nn_result["runtime_seconds"]),
            "iterations": NN_STEPS,
            "composite_queries": np.nan,
            "history_or_result_path": new_nn_result["history_path"],
        },
    ]
).set_index("method")

if len(comparison) != 4:
    raise AssertionError(f"Expected four comparison rows, got {len(comparison)}.")
if not np.isfinite(comparison["true_objective"].to_numpy(dtype=float)).all():
    raise ValueError("All four high-fidelity objectives must be finite.")

hour_columns = [f"hour_{hour:02d}" for hour in range(T)]
solution_frames = {
    "Original NN": pd.DataFrame(
        original_nn_prices, index=SCENARIOS, columns=hour_columns
    ),
    "Trust region": pd.DataFrame(
        tr_prices, index=SCENARIOS, columns=hour_columns
    ),
    "NN: original + TR samples": pd.DataFrame(
        tr_nn_prices, index=SCENARIOS, columns=hour_columns
    ),
    "NN: original + equal global random samples": pd.DataFrame(
        new_nn_prices, index=SCENARIOS, columns=hour_columns
    ),
}
solutions = pd.concat(solution_frames, names=["method", "scenario"])
if solutions.shape != (4 * len(SCENARIOS), T):
    raise AssertionError(f"Unexpected solution table shape: {solutions.shape}.")

output_timestamp = time.strftime("%Y%m%d-%H%M%S")
summary_path = RESULTS_DIR / f"retraining_ablation_summary_{output_timestamp}.csv"
solutions_path = RESULTS_DIR / f"retraining_ablation_solutions_{output_timestamp}.csv"
comparison.reset_index().to_csv(summary_path, index=False)
solutions.to_csv(solutions_path)

display(comparison)
display(sample_count_table)
display(solutions)
print("Saved objective summary to:", summary_path)
print("Saved four solution matrices to:", solutions_path)

,true_objective,runtime_seconds,iterations,composite_queries,history_or_result_path
method,,,,,
Original NN,-103.737458,NaN,10000,NaN,/Users/liqi/Desktop/Codes/Surrogated-assisted ...
Trust region,-105.941382,23405.220975,46,2806.0,/Users/liqi/Desktop/Codes/Surrogated-assisted ...
NN: original + TR samples,-88.731244,2166.634291,10000,NaN,/Users/liqi/Desktop/Codes/Surrogated-assisted ...
NN: original + equal global random samples,-100.188921,2217.241330,10000,NaN,/Users/liqi/Desktop/Codes/Surrogated-assisted ...

,original_samples,trust_region_samples,new_random_samples,tr_combined_samples,new_combined_samples
scenario,,,,,
SB1,10000,2748,2748,12748,12748
SB2,10000,2752,2752,12752,12752
BG1,10000,2646,2646,12646,12646
BG2,10000,1304,1304,11304,11304
IP1,10000,2682,2682,12682,12682

                                                          hour_00  \
method                                     scenario
Original NN                                SB1       9.054965e-01
                                           SB2       9.842920e-01
                                           BG1       1.499927e+00
                                           BG2       1.499915e+00
                                           IP1       1.493962e+00
Trust region                               SB1       9.998795e-01
                                           SB2       9.968669e-01
                                           BG1       1.495644e+00
                                           BG2       1.499982e+00
                                           IP1       1.498066e+00
NN: original + TR samples                  SB1       1.499928e+00
                                           SB2       1.188536e-09
                                           BG1       1.499981e+00
                                           BG2       1.499069e+00
                                           IP1       1.499439e+00
NN: original + equal global random samples SB1       9.968435e-01
                                           SB2       1.654597e-09
                                           BG1       1.499954e+00
                                           BG2       1.499952e+00
                                           IP1       1.486897e+00

                                                          hour_01   hour_02  \
method                                     scenario
Original NN                                SB1       9.723950e-01  0.992483
                                           SB2       9.859210e-01  0.971553
                                           BG1       1.499906e+00  1.499724
                                           BG2       1.499862e+00  1.499867
                                           IP1       1.488898e+00  1.495653
Trust region                               SB1       9.979150e-01  0.999420
                                           SB2       1.014724e+00  1.019202
                                           BG1       1.488299e+00  1.451504
                                           BG2       1.499983e+00  1.499984
                                           IP1       1.493433e+00  1.497932
NN: original + TR samples                  SB1       1.499951e+00  1.499834
                                           SB2       4.943811e-10  0.000091
                                           BG1       1.499914e+00  0.000073
                                           BG2       1.499875e+00  1.499869
                                           IP1       1.495921e+00  1.450716
NN: original + equal global random samples SB1       9.813607e-01  1.007961
                                           SB2       3.528125e-01  0.985318
                                           BG1       1.499965e+00  1.499923
                                           BG2       1.470373e+00  1.303163
                                           IP1       1.434057e+00  1.470561

                                                      hour_03   hour_04  \
method                                     scenario
Original NN                                SB1       0.998625  0.982330
                                           SB2       0.977133  0.962063
                                           BG1       1.499684  1.499929
                                           BG2       1.499870  1.499940
                                           IP1       1.494458  1.490675
Trust region                               SB1       0.999871  0.999830
                                           SB2       1.005840  0.994340
                                           BG1       1.478333  1.494318
                                           BG2       1.499982  1.499982
                                           IP1       1.498689  1.498905
NN: original + TR samples                  SB1       0.651487  1.499953
                                           SB2       0.000015  0.318339
                                           BG1       1.499951  1.499965
                                           BG2       1.499941  1.499908
                                           IP1       1.498905  1.391478
NN: original + equal global random samples SB1       0.990024  0.982307
                                           SB2       0.969710  0.972453
                                           BG1       1.499972  1.499970
                                           BG2       1.499928  1.499954
                                           IP1       1.492374  1.497422

                                                      hour_05       hour_06  \
method                                     scenario
Original NN                                SB1       0.981594  1.006895e+00
                                           SB2       0.958349  1.004334e+00
                                           BG1       1.499869  1.499946e+00
                                           BG2       1.499835  1.499953e+00
                                           IP1       1.476853  1.496844e+00
Trust region                               SB1       0.998423  9.998362e-01
                                           SB2       0.974873  1.025706e+00
                                           BG1       1.491532  1.496596e+00
                                           BG2       1.499982  1.499982e+00
                                           IP1       1.489531  1.498856e+00
NN: original + TR samples                  SB1       1.499979  1.110956e+00
                                           SB2       0.983360  9.632502e-07
                                           BG1       1.499924  1.185864e-09
                                           BG2       1.499962  1.499945e+00
                                           IP1       1.496206  1.499454e+00
NN: original + equal global random samples SB1       0.998490  9.904573e-01
                                           SB2       0.979053  2.191939e-01
                                           BG1       1.499970  1.499921e+00
                                           BG2       1.298418  1.499944e+00
                                           IP1       1.438436  1.492671e+00

                                                      hour_07   hour_08  \
method                                     scenario
Original NN                                SB1       1.002889  0.991757
                                           SB2       0.994941  1.498616
                                           BG1       1.499939  1.499915
                                           BG2       1.499933  1.499934
                                           IP1       1.499135  1.499072
Trust region                               SB1       0.999857  0.999970
                                           SB2       0.993327  1.441118
                                           BG1       1.498213  1.499688
                                           BG2       1.499982  1.499982
                                           IP1       1.494334  1.492893
NN: original + TR samples                  SB1       1.347614  1.278348
                                           SB2       0.940650  0.945039
                                           BG1       1.499963  1.499964
                                           BG2       1.499956  1.499939
                                           IP1       1.499094  1.489286
NN: original + equal global random samples SB1       0.999827  0.986911
                                           SB2       0.990189  1.000966
                                           BG1       1.499959  1.499919
                                           BG2       1.499935  1.499954
                                           IP1       1.497849  1.485926

                                                      hour_09  ...  \
method                                     scenario            ...
Original NN                                SB1       1.000325  ...
                                           SB2       0.988460  ...
                                           BG1       1.499948  ...
                                           BG2       1.499927  ...
                                           IP1       1.499319  ...
Trust region                               SB1       0.999969  ...
                                           SB2       0.980396  ...
                                           BG1       1.498753  ...
                                           BG2       1.499982  ...
                                           IP1       1.498209  ...
NN: original + TR samples                  SB1       1.499647  ...
                                           SB2       0.641746  ...
                                           BG1       1.499966  ...
                                           BG2       1.499913  ...
                                           IP1       1.415848  ...
NN: original + equal global random samples SB1       1.003704  ...
                                           SB2       0.981295  ...
                                           BG1       1.499932  ...
                                           BG2       1.499955  ...
                                           IP1       1.498817  ...

                                                          hour_14  \
method                                     scenario
Original NN                                SB1       1.037887e+00
                                           SB2       1.011563e+00
                                           BG1       1.499942e+00
                                           BG2       1.499954e+00
                                           IP1       1.499453e+00
Trust region                               SB1       1.008960e+00
                                           SB2       9.868304e-01
                                           BG1       1.499976e+00
                                           BG2       1.499982e+00
                                           IP1       1.499804e+00
NN: original + TR samples                  SB1       9.249958e-01
                                           SB2       3.284243e-10
                                           BG1       1.499952e+00
                                           BG2       1.499954e+00
                                           IP1       1.498730e+00
NN: original + equal global random samples SB1       1.031120e+00
                                           SB2       9.777641e-01
                                           BG1       1.499929e+00
                                           BG2       1.499954e+00
                                           IP1       1.499639e+00

                                                          hour_15   hour_16  \
method                                     scenario
Original NN                                SB1       1.018056e+00  1.024587
                                           SB2       9.996899e-01  0.996986
                                           BG1       1.499932e+00  1.499939
                                           BG2       1.499947e+00  1.499947
                                           IP1       1.499741e+00  1.499321
Trust region                               SB1       9.997212e-01  1.010079
                                           SB2       9.987085e-01  1.000635
                                           BG1       1.499578e+00  1.499972
                                           BG2       1.499982e+00  1.499982
                                           IP1       1.496693e+00  1.498925
NN: original + TR samples                  SB1       1.244134e+00  1.010030
                                           SB2       2.261258e-10  0.514456
                                           BG1       1.499968e+00  1.499916
                                           BG2       1.499794e+00  1.499953
                                           IP1       1.499121e+00  1.499525
NN: original + equal global random samples SB1       9.979118e-01  1.017826
                                           SB2       9.836208e-01  0.994073
                                           BG1       1.499927e+00  1.499954
                                           BG2       1.499954e+00  1.499967
                                           IP1       1.499596e+00  1.499221

                                                          hour_17   hour_18  \
method                                     scenario
Original NN                                SB1       9.971904e-01  0.993872
                                           SB2       9.818797e-01  1.001129
                                           BG1       1.499932e+00  1.499938
                                           BG2       1.499948e+00  1.499952
                                           IP1       1.497359e+00  1.494321
Trust region                               SB1       9.998697e-01  0.999441
                                           SB2       1.000061e+00  1.000021
                                           BG1       1.499012e+00  1.498827
                                           BG2       1.499982e+00  1.499982
                                           IP1       1.493224e+00  1.493368
NN: original + TR samples                  SB1       1.027170e+00  1.197659
                                           SB2       3.940092e-10  0.888586
                                           BG1       1.499958e+00  1.499961
                                           BG2       1.499952e+00  1.499960
                                           IP1       1.494763e+00  1.458472
NN: original + equal global random samples SB1       9.998387e-01  1.499740
                                           SB2       9.704462e-01  0.981006
                                           BG1       1.499957e+00  1.499904
                                           BG2       1.499951e+00  1.499978
                                           IP1       1.497541e+00  1.497172

                                                      hour_19   hour_20  \
method                                     scenario
Original NN                                SB1       1.024512  1.423613
                                           SB2       1.013935  0.991371
                                           BG1       1.499940  1.499914
                                           BG2       1.499953  1.499886
                                           IP1       1.498004  1.496904
Trust region                               SB1       1.011470  1.497473
                                           SB2       1.002404  1.003564
                                           BG1       1.499741  1.498599
                                           BG2       1.499982  1.499982
                                           IP1       1.498297  1.497186
NN: original + TR samples                  SB1       0.824753  1.499964
                                           SB2       0.944206  0.905824
                                           BG1       1.499985  1.499928
                                           BG2       1.499945  1.498876
                                           IP1       1.489821  1.498718
NN: original + equal global random samples SB1       1.031786  1.004394
                                           SB2       1.008041  0.997380
                                           BG1       1.499964  1.499929
                                           BG2       1.499900  1.499956
                                           IP1       1.499268  1.499046

                                                      hour_21   hour_22  \
method                                     scenario
Original NN                                SB1       1.006008  1.086199
                                           SB2       0.986417  1.089251
                                           BG1       0.261827  1.499944
                                           BG2       1.499871  1.499922
                                           IP1       1.494693  1.498408
Trust region                               SB1       0.999687  1.066518
                                           SB2       0.999755  1.023156
                                           BG1       0.284297  1.499984
                                           BG2       1.499985  1.499983
                                           IP1       1.493133  1.499980
NN: original + TR samples                  SB1       0.995602  0.855901
                                           SB2       0.658214  0.775195
                                           BG1       1.499932  1.499967
                                           BG2       1.499841  1.499893
                                           IP1       1.488264  1.499353
NN: original + equal global random samples SB1       0.999445  1.069420
                                           SB2       0.992901  1.081498
                                           BG1       1.499899  1.499966
                                           BG2       0.961199  1.499967
                                           IP1       1.498477  1.499422

                                                      hour_23
method                                     scenario
Original NN                                SB1       0.996892
                                           SB2       0.993309
                                           BG1       1.499898
                                           BG2       1.499468
                                           IP1       1.498219
Trust region                               SB1       0.999279
                                           SB2       1.005061
                                           BG1       1.498103
                                           BG2       1.499983
                                           IP1       1.498491
NN: original + TR samples                  SB1       1.022760
                                           SB2       0.630300
                                           BG1       1.499845
                                           BG2       1.499933
                                           IP1       1.490616
NN: original + equal global random samples SB1       1.007379
                                           SB2       0.339041
                                           BG1       1.499862
                                           BG2       1.499948
                                           IP1       1.499009

[20 rows x 24 columns]

Saved objective summary to: /Users/liqi/Desktop/Codes/Surrogated-assisted Stackelnerg Game/results/retraining_ablation_summary_20260925-204222.csv
Saved four solution matrices to: /Users/liqi/Desktop/Codes/Surrogated-assisted Stackelnerg Game/results/retraining_ablation_solutions_20260925-204222.csv